<#
Writes the Forever probe's two lists into QCForeverProbe\ (docs/plans/forever.md, phase 1):

  - QuestIDs.lua: every quest ID in the client's QuestV2 table for -Build, from wago.tools.
  - NpcIDs.lua: the creatures CMaNGOS's vanilla database names as givers of those quests, plus the
    NPCs on our old Classic pins, removed in #89 and read from git history.

Rerun with the live build at launch. The CMaNGOS dump (Full_DB in cmangos/classic-db) is downloaded
into -ToolsDir unless -CmangosDump names a copy.
#>
param(
    [string]$ToolsDir = (Join-Path $PSScriptRoot '..'),
    [string]$Build = "1.60.1.70205",
    [string]$CmangosDump = "",
    [string]$LuaExe = "C:\Program Files (x86)\Lua\5.1\lua.exe",
    [switch]$Refresh
)
$ErrorActionPreference = 'Stop'
$ProgressPreference = "SilentlyContinue"
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$addonDir = Join-Path $PSScriptRoot 'QCForeverProbe'

$questCsv = "$ToolsDir\QuestV2-$Build.csv"
if ($Refresh -or -not (Test-Path $questCsv)) {
    Invoke-WebRequest -UseBasicParsing -Uri "https://wago.tools/db2/QuestV2/csv?build=$Build" -OutFile $questCsv
}
$questIds = @(Import-Csv $questCsv | ForEach-Object { [int]$_.ID } | Sort-Object -Unique)
if ($questIds.Count -lt 1000) { throw "QuestV2 for $Build has only $($questIds.Count) rows: is the build right?" }
$inClient = @{}
foreach ($id in $questIds) { $inClient[$id] = $true }

if (-not $CmangosDump) {
    $CmangosDump = Get-ChildItem "$ToolsDir\ClassicDB_*.sql.gz" -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName
    if ($Refresh -or -not $CmangosDump) {
        $listing = Invoke-RestMethod "https://api.github.com/repos/cmangos/classic-db/contents/Full_DB"
        $file = $listing | Where-Object { $_.name -like '*.sql.gz' } | Select-Object -First 1
        $CmangosDump = "$ToolsDir\$($file.name)"
        Invoke-WebRequest -UseBasicParsing -Uri $file.download_url -OutFile $CmangosDump
    }
}

$sql = [System.IO.Path]::GetTempFileName()
try {
    $source = [System.IO.File]::OpenRead($CmangosDump)
    $gzip = New-Object System.IO.Compression.GZipStream($source, [System.IO.Compression.CompressionMode]::Decompress)
    $target = [System.IO.File]::Create($sql)
    $gzip.CopyTo($target)
    $target.Close(); $gzip.Close(); $source.Close()
    $starters = & $LuaExe "$PSScriptRoot\Read-SqlDump.lua" $sql "creature_questrelation" "1,2"
    if ($LASTEXITCODE -ne 0) { throw "Read-SqlDump.lua failed" }
} finally {
    Remove-Item $sql -ErrorAction SilentlyContinue
}

$npcIds = @{}
foreach ($line in $starters) {
    $npc, $quest = $line -split "`t"
    if ($inClient[[int]$quest]) { $npcIds[[int]$npc] = $true }
}
$fromCmangos = $npcIds.Count

$mapId = 0
foreach ($line in (git -C $repoRoot show "a9bc11c^:QuestCompletist/qcPinDB.lua")) {
    if ($line -match '^\t\[(\d+)\] = \{') { $mapId = [int]$Matches[1]; continue }
    if ($mapId -ge 1411 -and $mapId -le 1459 -and $line -match '^\t\t\{\d+,(\d+),' -and $Matches[1] -ne '0') {
        $npcIds[[int]$Matches[1]] = $true
    }
}

function Write-IdList($path, $header, $assignment, $ids) {
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add($header)
    $lines.Add("local _, probe = ...")
    $lines.Add("$assignment = {")
    for ($i = 0; $i -lt $ids.Count; $i += 20) {
        $last = [Math]::Min($i + 19, $ids.Count - 1)
        $lines.Add("`t" + (($ids[$i..$last] | ForEach-Object { "$_" }) -join ",") + ",")
    }
    $lines.Add("}")
    [System.IO.File]::WriteAllText($path, (($lines -join "`r`n") + "`r`n"), (New-Object System.Text.UTF8Encoding $false))
}

Write-IdList "$addonDir\QuestIDs.lua" "-- Generated by tools/ForeverProbe/Build-ProbeLists.ps1: QuestV2, build $Build." "probe.questBuild = `"$Build`"`r`nprobe.questIds" $questIds
$sortedNpcs = @($npcIds.Keys | Sort-Object)
Write-IdList "$addonDir\NpcIDs.lua" "-- Generated by tools/ForeverProbe/Build-ProbeLists.ps1: CMaNGOS givers of build $Build's quests, and our old Classic pins' NPCs." "probe.npcIds" $sortedNpcs

Write-Host ("{0} quests (build {1}); {2} NPCs: {3} CMaNGOS givers, {4} more from our old pins." -f
    $questIds.Count, $Build, $sortedNpcs.Count, $fromCmangos, ($sortedNpcs.Count - $fromCmangos))
