if GetLocale() == "itIT" then
qcLocalize = setmetatable({
	AHNQIRAJWAR = "Guerra di Ahn'Qiraj",
	ASSAULTONTHEDARKPORTAL = "Assault on the Dark Portal", -- Requires localization
	CAMPING = "Camping",
	CENTRALKALIMDOR = "Kalimdor centrale", -- Needs review
	CLASSES = "Classi", -- Needs review
	CLASSQUESTS = "Missioni di classe", -- Needs review
	CLEARUPDATECACHE = "Svuota la cache degli aggiornamenti...", -- Needs review
	CONFIGSUBTITLE = "Queste opzioni permettono di cambiare il modo in cui Quest Completist gestisce e filtra i suoi dati.", -- Needs review
	CONFIGTITLE = "Quest Completist - Configurazione", -- Needs review
	CONTINENTS = "Continenti", -- Needs review
	DAYOFTHEDEAD = "Day of the Dead", -- Requires localization
	ELEMENTALBONDS = "Elemental Bonds", -- Requires localization
	FIRELANDSINVASION = "Firelands Invasion", -- Requires localization
	GARRISONCAMPAIGN = "Garrison Campaign", -- Requires localization
	GARRISONSUPPORT = "Garrison Support", -- Requires localization
	HIDECOMPLETEDQUESTS = "Nascondi missioni completate", -- Needs review
	HIDEDAILYQUEST = "Nascondi missioni giornaliere", -- Needs review
	HIDEINPROGRESSQUESTS = "Nascondi missioni in corso", -- Needs review
	HIDELOWLEVELQUESTS = "Nascondi missioni di basso livello", -- Needs review
	HIDENONACTIVESEASONALQUESTS = "Nascondi missioni stagionali non attive", -- Needs review
	HIDEOTHERFACTIONQUESTS = "Nascondi missioni dell'altra fazione", -- Needs review
	HIDEOTHERPROFESSIONQUESTS = "Nascondi missioni di altre professioni", -- Needs review
	HIDEOTHERRACEANDCLASSQUESTS = "Nascondi missioni di altre razze e classi", -- Needs review
	HIDEOTHERCOVENANTQUESTS = "Nascondi missioni delle altre congreghe", -- Needs review
	HIDEWARBANDS = "Nascondi missioni completate da altri personaggi della brigata", -- Needs review
	HIDEUNAVAILABLE = "Nascondi missioni non più disponibili", -- Needs review
	HIDEREQUIREMENTSNOTMET = "Nascondi missioni con requisiti non soddisfatti", -- Needs review
	HIDENODATA = "Nascondi segnalini senza dati sulla missione", -- Needs review
	HIDEREPEATABLEQUEST = "Nascondi missioni ripetibili", -- Needs review
	HIDEWORLDQUEST = "Nascondi missioni mondiali e settimanali", -- Needs review
	INVASION = "Invasione",
	KHAZMODAN = "Khaz Modan", -- Requires localization
	LANDFALL = "Landfall", -- Requires localization
	LORDAERON = "Lordaeron", -- Requires localization
	LUNARFESTIVAL = "Celebrazione della Luna",
	MIDSUMMER = "Mezza Estate",
	NORTHERNKALIMDOR = "Kalimdor settentrionale", -- Needs review
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Pandaren Campaign", -- Requires localization
	PERFORMSERVERQUERY = "Interroga il server...", -- Needs review
	QUERYREQUESTED = "Un'interrogazione al server è stata richiesta", -- Needs review
	QUESTLIST = "Elenco missioni", -- Needs review
	QUESTSFOUND = "%d missioni trovate", -- Needs review
	SEASONAL = "Stagionale",
	SHOWMAPICONS = "Mostra icone sulla mappa", -- Needs review
	SKETTIS = "Skettis", -- Requires localization
	SORTALPHA = "Ordina: alfabeticamente", -- Needs review
	SORTLEVEL = "Ordina: per livello", -- Needs review
	SOUTHERNKALIMDOR = "Kalimdor meridionale", -- Needs review
	SPECIALS = "Speciali", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "Valle di Rovotorto", -- Needs review
	THEZANDALARI = "The Zandalari", -- Requires localization
	TOURNAMENT = "Tournament", -- Requires localization
	TREASUREMAP = "Mappa del Tesoro",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "Eventi settimanali", -- Needs review
	WORLDEVENTS = "World Events", -- Requires localization
	MACAREE = "Mac'Aree",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
	WORLDPVP = "World Pvp",
	BLACKEMPIRECAMPAIGN = "Black Empire Campaign",
		-- Shadowlands Code
	-- Shadowlands Code
	MAINZONES = "Zone principali", -- Needs review
	OTHERCATEGORIES = "Altre categorie", -- Needs review
	COVENANTASSAULTS = "Covenant Assaults",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
	--TWW
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NORTHRENDCUP = "Northrend Cup",
	UPGRADESYSTEM = "Upgrade System",
	WARBANDS = "Warbands",
	TIMERUNNING = "Timerunning",
	THEHARBINGER = "The Harbinger",
	GILNEASRECLAMATION = "Gilneas Reclamation",
	TIMERIFT = "Time Rift",
	--MID
	NEIGHBORHOOD = "Neighborhood",
	PROGRESS = "%d/%d completate (%d%%)", -- Needs review
	SERVERQUERYRESULT = "Il server segnala %d missioni completate note a Quest Completist, di cui %d appena segnate come completate.", -- Needs review
	CACHECLEARED = "Cache svuotata.", -- Needs review
	CLEARINGCACHE = "Svuotamento della cache degli aggiornamenti...", -- Needs review
	NODETAILS = "Il gioco non fornisce i dettagli della missione", -- Needs review
	QUESTID = "ID missione:", -- Needs review
	STORYLINEPOSITION = "(%d di %d)", -- Needs review
	EARLIERQUESTS = "... %d precedenti", -- Needs review
	LATERQUESTS = "... altre %d", -- Needs review
	THISQUEST = "questa missione", -- Needs review
	REQUIREDQUEST = "Missione richiesta:", -- Needs review
	REQUIREDFACTION = "Fazione richiesta:", -- Needs review
	REQUIREDRENOWN = "Livello di fama richiesto:", -- Needs review
	REQUIREDRANK = "Grado richiesto:", -- Needs review
	REQUIREDSKILL = "Abilità richiesta:", -- Needs review
	RANKLEVEL = "Grado %d", -- Needs review
	QUESTGIVER = "Assegnata da:", -- Needs review
	NOQUESTGIVER = "Sconosciuto, o missione accettata automaticamente", -- Needs review
	REPAMOUNT = "%d reputazione", -- Needs review
	NEWDATAINTRO = "Quest Completist non conosceva le seguenti informazioni. Aiuta a migliorare la precisione dell'addon segnalandole su CurseForge.", -- Needs review
	NEWDATAQUEST = " - La missione non esiste nel database.", -- Needs review
	NEWDATAFACTION = " - QC non sapeva che la tua FAZIONE potesse completare questa missione.", -- Needs review
	NEWDATARACE = " - QC non sapeva che la tua RAZZA potesse completare questa missione.", -- Needs review
	NEWDATACLASS = " - QC non sapeva che la tua CLASSE potesse completare questa missione.", -- Needs review
	NEWDATAALERT = "Trovati nuovi dati - contribuisci!", -- Needs review
	BREADCRUMBAVAILABLE = "1 missione introduttiva disponibile!", -- Needs review
	BREADCRUMBSAVAILABLE = "%d missioni introduttive disponibili!", -- Needs review
	BREADCRUMBQUESTS = "Missioni introduttive", -- Needs review
	MUTUALLYEXCLUSIVE = "Questa missione ne esclude altre: puoi completarne solo una. Le altre missioni sono:", -- Needs review
	NOTINDATABASE = "Missione non presente nel database", -- Needs review
	YOURSELF = "<Te stesso>", -- Needs review
	OTHERQUESTS = "Altre missioni", -- Needs review
	PINDONE = "%d completate", -- Needs review
	PINSHOWDONE = "Maiusc per mostrare", -- Needs review
	PINWAYPOINT = "Clicca per impostare un waypoint di TomTom", -- Needs review
	WELCOME = "Grazie per aver scelto Quest Completist. Hai notato un errore in una missione? Segnalalo su CurseForge.", -- Needs review
	UNAVAILABLEACCEPTED = "La missione %d \"%s\" risulta non più disponibile, ma l'hai appena accettata. Per te viene mostrata normalmente; segnalalo così che l'elenco possa essere corretto.", -- Needs review
	UNAVAILABLETURNEDIN = "La missione %d \"%s\" risulta non più disponibile, ma l'hai appena consegnata. Per te viene mostrata normalmente; segnalalo così che l'elenco possa essere corretto.", -- Needs review
	TOGGLEFRAME = "Mostra/nascondi finestra", -- Needs review
	}, {__index = qcLocalize})

end