if GetLocale() == "zhTW" then
qcLocalize = {
	AHNQIRAJTHEFALLENKINGDOM = "安其拉：沒落的王朝",
	ALCHEMY = "鍊金術", -- Needs review
	ARCHAEOLOGY = "考古學", -- Needs review
	ASSAULTONTHEDARKPORTAL = "Assault on the Dark Portal", -- Requires localization
	AZEROTH = "艾澤拉斯",
	BARADINHOLD = "巴拉丁堡", -- Needs review
	BATTLEGROUNDS = "戰場", -- Needs review
	BATTLEPETS = "戰鬥寵物", -- Needs review
	BLACKSMITHING = "鍛造", -- Needs review
	BLACKWINGDESCENT = "黑翼陷窟", -- Needs review
	BLACKWINGLAIR = "黑翼之巢", -- Needs review
	BRAWLERSGUILD = "Brawler's Guild", -- Requires localization
	BREWFEST = "啤酒節", -- Needs review
	CAVERNSOFTIME = "時光之穴", -- Needs review
	CENTRALKALIMDOR = "Central Kalimdor", -- Requires localization
	CHILDRENSWEEK = "兒童週", -- Needs review
	CLASSES = "職業", -- Needs review
	CLASSQUESTS = "職業任務", -- Needs review
	CLEARUPDATECACHE = "清除更新快取", -- Needs review
	COILFANGRESERVOIR = "盤牙蓄湖", -- Needs review
	COMBINEDMAPANDQUESTFILTERS = "已合併的地圖與任務列表過濾器", -- Needs review
	CONFIGSUBTITLE = "這些選項允許你改變 Quest Completist 對其自身資料處理和過濾的方式", -- Needs review
	CONFIGTITLE = "Quest Completist - 設置", -- Needs review
	CONTINENTS = "地區", -- Needs review
	COOKING = "烹飪", -- Needs review
	DARKMOONFAIRE = "暗月馬戲團", -- Needs review
	DAYOFTHEDEAD = "亡者節", -- Needs review
	DEATHKNIGHT = "死亡騎士", -- Needs review
	DRAENOR = "德拉諾",
	DRAGONSOUL = "巨龍之魂", -- Needs review
	DRUID = "德魯伊", -- Needs review
	DUNGEONSANDRAIDS = "地下城與團隊", -- Needs review
	EASTERNKINGDOMS = "東都王國",
	ELEMENTALBONDS = "元素桎梏", -- Needs review
	ENCHANTING = "附魔", -- Needs review
	ENGINEERING = "工程學", -- Needs review
	FIRELANDS = "火源之界", -- Needs review
	FIRELANDSINVASION = "火源之界進軍行動", -- Needs review
	FIRSTAID = "急救", -- Needs review
	FISHING = "釣魚", -- Needs review
	GARRISONCAMPAIGN = "Garrison Campaign", -- Requires localization
	GARRISONSUPPORT = "Garrison Support", -- Requires localization
	GREENSTONEVILLAGE = "綠石村",
	GRUULSLAIR = "戈魯爾之巢", -- Needs review
	HALLOWSEND = "萬鬼節", -- Needs review
	HARVESTFESTIVAL = "收穫節", -- Needs review
	HELLFIRECITADEL = "地獄火堡壘", -- Needs review
	HERBALISM = "草藥學", -- Needs review
	HIDECOMPLETEDQUESTS = "隱藏已完成的任務", -- Needs review
	HIDEDAILYQUEST = "Hide Daily Quests",
	HIDEINPROGRESSQUESTS = "隱藏進行中的任務", -- Needs review
	HIDELOWLEVELQUESTS = "隱藏低等級的任務", -- Needs review
	HIDENONACTIVESEASONALQUESTS = "隱藏尚未開始的季節性任務", -- Needs review
	HIDENORMALQUEST = "Hide Normal Quests",
	HIDEOTHERFACTIONQUESTS = "隱藏其他陣營的任務", -- Needs review
	HIDEOTHERPROFESSIONQUESTS = "隱藏其他專業的任務", -- Needs review
	HIDEOTHERRACEANDCLASSQUESTS = "隱藏其他種族和職業任務", -- Needs review
	HIDEOTHERCOVENANTQUESTS = "Hide Other Covenant Quests",
	HIDEWARBANDS = "Hide quests done by other warband's characters",
	HIDEREQUIREMENTSNOTMET = "Hide quests with unfinished requirements",
	HIDENODATA = "Hide pins with no quest data available",
	HIDEREPEATABLEQUEST = "Hide Repeatable Quests",
	HIDEWEEKLYQUEST = "Hide Weekly Quests",
	HIDEWORLDQUEST = "Hide World Quests",
	HUNTER = "獵人", -- Needs review
	INSCRIPTION = "銘文學", -- Needs review
	ISLEOFGIANTS = "巨獸島",
	JADETEMPLEGROUNDS = "Jade Temple Grounds", -- Requires localization
	JEWELCRAFTING = "珠寶設計", -- Needs review
	KALIMDOR = "卡林多",
	KHAZMODAN = "Khaz Modan", -- Requires localization
	LANDFALL = "Landfall", -- Requires localization
	LEATHERWORKING = "製皮", -- Needs review
	LEGENDARY = "傳奇", -- Needs review
	LORDAERON = "Lordaeron", -- Requires localization
	LOVEISINTHEAIR = "愛就在身邊", -- Needs review
	LUNARFESTIVAL = "新年慶典", -- Needs review
	MAGE = "法師", -- Needs review
	MAPFILTERS = "地圖過濾器", -- Needs review
	MIDSUMMERFIREFESTIVAL = "仲夏火焰節", -- Needs review
	MINING = "採礦", -- Needs review
	MISCELLANEOUS = "雜項", -- Needs review
	MOGUSHANVAULTS = "魔古山寶庫",
	MONK = "武僧", -- Needs review
	NAGRAND = "納葛蘭",
	NEWYEARSEVE = "除夕夜", -- Needs review
	NOBLEGARDEN = "貴族花園", -- Needs review
	NORTHERNKALIMDOR = "Northern Kalimdor", -- Requires localization
	NORTHREND = "北裂境",
	ONYXIASLAIR = "奧妮克希亞的巢穴", -- Needs review
	OPTIONS = "選項", -- Needs review
	OUTLAND = "外域",
	PALACEOFTHEHEAVENS = "魔古山宮", -- Needs review
	PALADIN = "聖騎士", -- Needs review
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Pandaren Campaign", -- Requires localization
	PANDARIA = "潘達利亞",
	PEAKOFSERENITY = "Peak of Serenity", -- Requires localization
	PERFORMSERVERQUERY = "進行伺服器查詢中...", -- Needs review
	PILGRIMSBOUNTY = "旅人豐年祭", -- Needs review
	PRIEST = "牧師", -- Needs review
	PROFESSIONS = "專業", -- Needs review
	QUERYREQUESTED = "已經對伺服器進行查詢的要求...", -- Needs review
	QUESTLISTFILTERS = "任務列表過濾器", -- Needs review
	QUESTSFOUND = "已找到 %d 個任務", -- Needs review
	RAIDS = "團隊", -- Needs review
	REGIONS = "Regions", -- Requires localization
	RIDING = "Riding", -- Requires localization
	ROGUE = "盜賊", -- Needs review
	RUINSOFGILNEASCITY = "吉爾尼斯城廢墟",
	SCENARIO = "Scenario", -- Requires localization
	SEASONAL = "季節性", -- Needs review
	SERPENTSHRINECAVERN = "毒蛇神殿洞穴", -- Needs review
	SHADOWMOONVALLEY = "影月谷", -- Needs review
	SHAMAN = "薩滿", -- Needs review
	SHOWMAPICONS = "顯示地圖小圖示", -- Needs review
	SKETTIS = "Skettis", -- Requires localization
	SKINNING = "剝皮", -- Needs review
	SORTALPHA = "排序：以字母順序", -- Needs review
	SORTLEVEL = "排序：以等級", -- Needs review
	SOUTHERNKALIMDOR = "Southern Kalimdor", -- Requires localization
	SPECIAL = "特殊", -- Needs review
	SPECIALS = "特殊", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "荊棘谷", -- Needs review
	SUNKENTEMPLE = "沉沒的神廟", -- Needs review
	TAILORING = "裁縫", -- Needs review
	TEMPLEOFTHEREDCRANE = "紅鶴寺", -- Needs review
	THEARBORETUM = "The Arboretum", -- Requires localization
	THEBASTIONOFTWILIGHT = "暮光堡壘", -- Needs review
	THEBLACKMORASS = "黑色沼澤", -- Needs review
	THEEVERBLOOM = "永茂林",
	THEEYE = "風暴核心", -- Needs review
	THEGATEOFTHESETTINGSUN = "日暮之門", -- Needs review
	THEHALFHILLMARKET = "半丘市集", -- Needs review
	THEMAELSTROM = "大漩渦", -- Needs review
	THEOBSIDIANSANCTUM = "黑曜聖所", -- Needs review
	THETEMPLEOFTHEJADESERPENT = "玉蛟寺", -- Needs review
	THEVIOLETHOLD = "紫羅蘭堡", -- Needs review
	THEZANDALARI = "贊達拉", -- Needs review
	THRONEOFTHEFOURWINDS = "四風王座", -- Needs review
	TOURNAMENT = "全球爭霸戰", -- Needs review
	UPPERBLACKROCKSPIRE = "黑石塔上層",
	VASHJIR = "瓦許伊爾", -- Needs review
	VAULTOFARCHAVON = "亞夏梵穹殿", -- Needs review
	WARLOCK = "術士", -- Needs review
	WARRIOR = "戰士", -- Needs review
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WINTERVEIL = "冬幕節", -- Needs review
	WORLDEVENTS = "世界事件", -- Needs review
	THEBROKENISLES = "The Broken Isles",
	THEDREAMGROVE = "幻夢之林",
	DEMONHUNTER = "惡魔獵人",
	CONTESTCOMMING = "Contest comming shows wrong zone",
	HALLOFTHEGUARDIAN = "守護者殿堂",
	MARDUMTHESHATTEREDABYSS = "Mardum, the Shattered Abyss",
	NETHERLIGHTTEMPLE = "虛空之光神殿",
	SKYHOLD = "擎天堡",
	THEHEARTOFAZERTH = "The Heart of Azeroth",
	THEWANDERINGISLE = "The Wandering Isle Monk",
	TRUESHOTLODGE = "Trueshot Lodge Hunter",
	MAWOFSOULS = "靈魂之喉",
	LEGIONUNCATEQUEST = "Legion Uncategorized Quests",
	RETURNTOKARAZHAN = "重返卡拉贊",
	MACAREE = "Mac'Aree",
	DREADSCARRIFT = "懼痕裂隙",
	HELHEIM = "黑爾海姆",
	EMERALDDREAMWAY = "Emerald Dreamway",
	BFA = "決戰艾澤拉斯",
	BFAUNCATEQUEST = "BFA Uncategorized Quests",
	ZANDALAR = "Zandalar",
	KULTIRAS = "Kul Tiras",
	THUNDERTOTEM = "Thunder Totem",
	KINGSREST = "諸王之眠",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	THRUNDERROT = "The Underrot",
	THEDEATHOFCHROMIE = "The Deaths Of Chromie",
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	THEDRAGONSSPINE = "The Dragon`s Spine",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	CLASSCAMPAINS = "Class Campains",
	TERRACEOFENLESSSPRINGS = "豐泉台",
	PLAYERVSPLAYER = "Player Vs Player",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
	WORLDPVP = "World Pvp",
	NYALOTHATHEWALKINGCITY = "奈奧羅薩，甦醒之城",
	VISIONSOFNZOTH = "Visions of N'Zoth",
	BLACKEMPIRECAMPAIGN = "Black Empire Campaign",
	WORLDQUEST = "World Quests",
	-- Shadowlands Code
	-- Shadowlands Code
	SHADOWLANDS = "暗影之境",
	SHADOWLANDSUNCATEQUEST = "Shadowlands Uncategorized Quests",
	COVENANTCALLINGS = "Covenant Callings",
	KYRIAN = "Kyrian",
	NECROLORD = "Necrolord",
	NIGHTFAE = "Night Fae",
	VENTHYR = "Venthyr",
	MAINZONES = "Main Zones",
	OTHERCATEGORIES	= "Other Categories",
	NINEONECAMPAIGN = "9.1 Campaign",
	ABOMINABLESTICHING = "憎惡縫合術",
	COVENANTASSAULTS = "Covenant Assaults",
	COVENANTSANCTUARY = "Covenant Sanctuary",
	COVENANTSANCTUM = "Covenant Sanctum",
	EMBERCOURT = "Ember Court",
	KEEPERSRESPITE = "守衛者歇息地",
	PATHOFASCENSION = "Path of Ascension",
	TAZAVESH = "Tazavesh",
	THEARCHIVISTSCODEX = "The Archivists' Codex",
	TORGHASTTOWEROFTHEDAMNED = "『譴罪之塔』托迦司",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
	AZEROTHIANARCHIVES = "Azerothian Archives",
	AZMERLOTH = "Azmerloh",
	BRACKENHIDEWATERHOLE = "Brackenhide Waterhole",
	DRAGONISLE = "Dragon Isle",
	DRAGONFLIGHT = "巨龍崛起",
	DRAGONSCALEBASECAMP = "Dragonscale Basecamp",
	DRAGONSCALEEXPEDITION = "Dragonscale Expedition",
	DUNGEONS = "Dungeons",
	EMERALDARDENS = "Emerald Gardens",
	HORNSWOGHOLLOW = "Hornswog Hollow",
	ISKAARATUSKARR = "Iskaara Tuskarr",
	LOSTRUINS = "Lost Ruins",
	MARUUKCENTAUR = "Maruuk Centaur",
	OBSIDIANCITADEL = "黑曜龍堡", 
	PASSAGEOFTIME = "時光通道",
	PRIMALISTSTORMS = "Primalist Storms",
	PRIMORDIALALE = "Primordial Vale",
	RUBYLIFEPOOLS = "晶紅生命之池",
	RUBYLIFESHRINE = "Ruby Lifeshrine",
	SHADOWLEDGE = "Shadow Legde",
	TEMPESTUNLEASHED = "Tempest Unleashed",
	THEPRIMAISTFUTURE = "The Primalist Future",
	THERONSWATCH = "Theron`s Watch",
	VALDRAKKENACCORD = "Valdrakken Accord",
	WHALLERSNOOK = "Whaler`s Nook",
	KORRAKSREVENGE = "Korrak`s Revenge",
	--TWW
	TWW = "地心之戰",
	AWAKENINGTHEMACHINE = "甦醒機械",
	DEEPHAULRAVINE = "礦運深谷",	
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NERUBARPALACE = "奈幽巴宮殿",
	NORTHRENDCUP = "Northrend Cup",
	RAMBLESHIRE = "漫步郡",
	UPGRADESYSTEM = "Upgrade System",
	WARBANDS = "Warbands",
	ARATHIHIGHLANDSTWW = "Arathi Highlands TWW",
	DELVESHEADQUARTERS = "探究者總部",
	DELVES = "Delves",
	THERAMORESFALLS = "Theramore`s  Fall",
	TIMERUNNING = "Timerunning",
	THEHARBINGER = "The Harbinger",
	GILNEASRECLAMATION = "Gilneas Reclamation",
	LITTLESCALESDAYCARE = "Little Scales Daycare",
	TIMERIFT = "Time Rift",
	AMIRDRASIL = "Amirdrasil",
	AMIRDRASILTHEDREAMSHOPE = "『夢境希望』埃達希爾",
	THEOASIS = "綠洲",
	--MID
	MIDNIGHT = "至暗之夜",
	FOUNDERSPOINT = "開拓角",
	NEIGHBORHOOD = "Neighborhood",
	RAZORWINDSHORES = "烈風海岸",
	SLAYERSRISE = "殺戮者高崗",
	WESTSANCTUM = "西部聖所",	
	}

end