if GetLocale() == "koKR" then
qcLocalize = setmetatable({
	AHNQIRAJTHEFALLENKINGDOM = "안퀴라즈: 무너진 왕국", -- Needs review
	ALCHEMY = "연금술", -- Needs review
	ARCHAEOLOGY = "고고학", -- Needs review
	ASSAULTONTHEDARKPORTAL = "Assault on the Dark Portal", -- Requires localization
	AZEROTH = "아제로스",
	BARADINHOLD = "바라딘 요새",
	BATTLEGROUNDS = "전장", -- Needs review
	BATTLEPETS = "전투 펫", -- Needs review
	BLACKSMITHING = "대장기술", -- Needs review
	BLACKWINGDESCENT = "검은날개 강림지",
	BLACKWINGLAIR = "검은날개 둥지",
	BRAWLERSGUILD = "Brawler's Guild", -- Requires localization
	BREWFEST = "가을 축제", -- Needs review
	CAVERNSOFTIME = "시간의 동굴",
	CENTRALKALIMDOR = "중부 칼림도어", -- Needs review
	CHILDRENSWEEK = "어린이 주간", -- Needs review
	CLASSES = "직업", -- Needs review
	CLASSQUESTS = "직업 퀘스트", -- Needs review
	CLEARUPDATECACHE = "업데이트 캐쉬 초기화", -- Needs review
	COILFANGRESERVOIR = "갈퀴송곳니 저수지", -- Needs review
	CONFIGSUBTITLE = "Quest Completist에서 항목 분류를 통해서 원하는 정보를 빠르게 볼 수 있습니다.", -- Needs review
	CONFIGTITLE = "Quest Completist - 설정", -- Needs review
	CONTINENTS = "대륙", -- Needs review
	COOKING = "요리", -- Needs review
	DARKMOONFAIRE = "다크문 축제", -- Needs review
	DAYOFTHEDEAD = "망자의 날", -- Needs review
	DEATHKNIGHT = "죽음의 기사", -- Needs review
	DRAENOR = "드레노어",
	DRAGONSOUL = "용의 영혼",
	DRUID = "드루이드", -- Needs review
	DUNGEONSANDRAIDS = "던전 & 공격대", -- Needs review
	EASTERNKINGDOMS = "동부 왕국", -- Needs review
	ELEMENTALBONDS = "Elemental Bonds", -- Requires localization
	ENCHANTING = "마법부여", -- Needs review
	ENGINEERING = "기계공학", -- Needs review
	FIRELANDS = "불의 땅",
	FIRELANDSINVASION = "Firelands Invasion", -- Requires localization
	FIRSTAID = "응급치료", -- Needs review
	FISHING = "낚시", -- Needs review
	GARRISONCAMPAIGN = "Garrison Campaign", -- Requires localization
	GARRISONSUPPORT = "Garrison Support", -- Requires localization
	GREENSTONEVILLAGE = "녹옥 마을",
	GRUULSLAIR = "그룰의 둥지",
	HALLOWSEND = "할로윈 축제", -- Needs review
	HARVESTFESTIVAL = "가을 축제", -- Needs review
	HELLFIRECITADEL = "지옥불 성채", -- Needs review
	HERBALISM = "약초채집", -- Needs review
	HIDECOMPLETEDQUESTS = "완료된 퀘스트 숨김", -- Needs review
	HIDEDAILYQUEST = "일일 퀘스트 숨김", -- Needs review
	HIDEINPROGRESSQUESTS = "진행중인 퀘스트 숨김", -- Needs review
	HIDELOWLEVELQUESTS = "저레벨 퀘스트 숨김", -- Needs review
	HIDENONACTIVESEASONALQUESTS = "진행중이지 않은 계절 축제 퀘스트 숨김", -- Needs review
	HIDENORMALQUEST = "Hide Normal Quests",
	HIDEOTHERFACTIONQUESTS = "상대진영 퀘스트 숨김", -- Needs review
	HIDEOTHERPROFESSIONQUESTS = "다른 전문기술 퀘스트 숨김", -- Needs review
	HIDEOTHERRACEANDCLASSQUESTS = "다른 종족 및 직업 퀘스트 숨김", -- Needs review
	HIDEOTHERCOVENANTQUESTS = "다른 성약의 단 퀘스트 숨김", -- Needs review
	HIDEWARBANDS = "전투부대의 다른 캐릭터가 완료한 퀘스트 숨김", -- Needs review
	HIDEUNAVAILABLE = "더 이상 받을 수 없는 퀘스트 숨김", -- Needs review
	HIDEREQUIREMENTSNOTMET = "조건을 충족하지 못한 퀘스트 숨김", -- Needs review
	HIDENODATA = "퀘스트 정보가 없는 표시 숨김", -- Needs review
	HIDEREPEATABLEQUEST = "반복 퀘스트 숨김", -- Needs review
	HIDEWORLDQUEST = "전역 퀘스트 및 주간 퀘스트 숨김", -- Needs review
	HUNTER = "사냥꾼", -- Needs review
	INSCRIPTION = "주문각인", -- Needs review
	ISLEOFGIANTS = "괴수의 섬",
	JADETEMPLEGROUNDS = "Jade Temple Grounds", -- Requires localization
	JEWELCRAFTING = "보석세공", -- Needs review
	KALIMDOR = "칼림도어", -- Needs review
	KHAZMODAN = "카즈 모단", -- Needs review
	LANDFALL = "Landfall", -- Requires localization
	LEATHERWORKING = "가죽세공", -- Needs review
	LEGENDARY = "전설", -- Needs review
	LORDAERON = "로데론", -- Needs review
	LOVEISINTHEAIR = "온누리에 사랑을", -- Needs review
	LUNARFESTIVAL = "달의 축제", -- Needs review
	MAGE = "마법사", -- Needs review
	MIDSUMMERFIREFESTIVAL = "한여름 불꽃 축제", -- Needs review
	MINING = "채광", -- Needs review
	MISCELLANEOUS = "기타", -- Needs review
	MOGUSHANVAULTS = "모구샨 금고",
	MONK = "수도사", -- Needs review
	NAGRAND = "나그란드",
	NEWYEARSEVE = "New Year's Eve", -- Requires localization
	NOBLEGARDEN = "귀족의 정원", -- Needs review
	NORTHERNKALIMDOR = "북부 칼림도어", -- Needs review
	NORTHREND = "노스렌드", -- Needs review
	ONYXIASLAIR = "오닉시아의 둥지",
	OPTIONS = "설정", -- Needs review
	OUTLAND = "아웃랜드", -- Needs review
	PALACEOFTHEHEAVENS = "Palace of the Heavens", -- Requires localization
	PALADIN = "성기사", -- Needs review
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Pandaren Campaign", -- Requires localization
	PANDARIA = "판다리아", -- Needs review
	PEAKOFSERENITY = "Peak of Serenity", -- Requires localization
	PERFORMSERVERQUERY = "서버 질의를 진행합니다...", -- Needs review
	PILGRIMSBOUNTY = "Pilgrim's Bounty", -- Requires localization
	PRIEST = "사제", -- Needs review
	PROFESSIONS = "전문기술", -- Needs review
	QUERYREQUESTED = "서버 질의에 응답했습니다...", -- Needs review
	QUESTLIST = "퀘스트 목록", -- Needs review
	QUESTSFOUND = "%d 퀘스트 찾음", -- Needs review
	RAIDS = "공격대", -- Needs review
	REGIONS = "Regions", -- Requires localization
	RIDING = "Riding", -- Requires localization
	ROGUE = "도적", -- Needs review
	RUINSOFGILNEASCITY = "길니아스 시 폐허",
	SCENARIO = "Scenario", -- Requires localization
	SEASONAL = "계절 축제", -- Needs review
	SERPENTSHRINECAVERN = "불뱀 제단",
	SHADOWMOONVALLEY = "어둠달 골짜기",
	SHAMAN = "주술사", -- Needs review
	SHOWMAPICONS = "지도 아이콘 표시", -- Needs review
	SKETTIS = "Skettis", -- Requires localization
	SKINNING = "무두질", -- Needs review
	SORTALPHA = "정렬 : 가나다 순", -- Needs review
	SORTLEVEL = "정렬 : 레벨 순", -- Needs review
	SOUTHERNKALIMDOR = "남부 칼림도어", -- Needs review
	SPECIAL = "특수", -- Needs review
	SPECIALS = "특수", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "가시덤불 골짜기",
	TAILORING = "재봉술", -- Needs review
	TEMPLEOFTHEREDCRANE = "주학사", -- Needs review
	THEARBORETUM = "The Arboretum", -- Requires localization
	THEBASTIONOFTWILIGHT = "황혼의 요새",
	THEBLACKMORASS = "검은늪",
	THEEVERBLOOM = "상록숲",
	THEEYE = "폭풍우 눈", -- Needs review
	THEGATEOFTHESETTINGSUN = "The Gate of the Setting Sun", -- Requires localization
	THEHALFHILLMARKET = "언덕골 시장", -- Needs review
	THEMAELSTROM = "혼돈의 소용돌이",
	THEOBSIDIANSANCTUM = "흑요석 성소",
	THETEMPLEOFTHEJADESERPENT = "옥룡사", -- Needs review
	THEVIOLETHOLD = "보랏빛 요새",
	THEZANDALARI = "잔달라", -- Needs review
	THRONEOFTHEFOURWINDS = "네 바람의 왕좌",
	TOURNAMENT = "토너먼트", -- Needs review
	UPPERBLACKROCKSPIRE = "검은바위 첨탑 상층",
	UNCATEGORIZED = "미분류", -- Needs review
	VASHJIR = "바쉬르",
	VAULTOFARCHAVON = "아카본 석실",
	WARLOCK = "흑마법사", -- Needs review
	WARRIOR = "전사", -- Needs review
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "주간 이벤트", -- Needs review
	WINTERVEIL = "겨울마이 축제", -- Needs review
	WORLDEVENTS = "월드 이벤트", -- Needs review
	THEBROKENISLES = "The Broken Isles",
	THEDREAMGROVE = "꿈숲",
	DEMONHUNTER = "악마사냥꾼",
	CONTESTCOMMING = "Contest comming shows wrong zone",
	HALLOFTHEGUARDIAN = "수호자의 전당",
	MARDUMTHESHATTEREDABYSS = "Mardum, the Shattered Abyss",
	NETHERLIGHTTEMPLE = "황천빛 사원",
	SKYHOLD = "하늘보루",
	THEHEARTOFAZERTH = "The Heart of Azeroth",
	THEWANDERINGISLE = "The Wandering Isle Monk",
	TRUESHOTLODGE = "Trueshot Lodge Hunter",
	MAWOFSOULS = "영혼의 아귀",
	LEGIONUNCATEQUEST = "Legion Uncategorized Quests",
	RETURNTOKARAZHAN = "다시 찾은 카라잔",
	MACAREE = "Mac'Aree",
	DREADSCARRIFT = "공포흉터 균열",
	HELHEIM = "헬하임",
	EMERALDDREAMWAY = "Emerald Dreamway",
	BFA = "격전의 아제로스",
	ZANDALAR = "Zandalar",
	KULTIRAS = "Kul Tiras",
	THUNDERTOTEM = "Thunder Totem",
	KINGSREST = "왕들의 안식처",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	THRUNDERROT = "The Underrot",
	THEDEATHOFCHROMIE = "The Deaths Of Chromie",
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	THEDRAGONSSPINE = "The Dragon`s Spine",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	TERRACEOFENLESSSPRINGS = "영원한 봄의 정원",
	PLAYERVSPLAYER = "Player Vs Player",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
	WORLDPVP = "World Pvp",
	NYALOTHATHEWALKINGCITY = "깨어난 도시 나이알로사",
	VISIONSOFNZOTH = "Visions of N'Zoth",
	BLACKEMPIRECAMPAIGN = "Black Empire Campaign",
	WORLDQUEST = "World Quests",
		-- Shadowlands Code
	-- Shadowlands Code
	SHADOWLANDS = "어둠땅",
	SHADOWLANDSUNCATEQUEST = "Shadowlands Uncategorized Quests",
	COVENANTCALLINGS = "Covenant Callings",
	KYRIAN = "Kyrian",
	NECROLORD = "Necrolord",
	NIGHTFAE = "Night Fae",
	VENTHYR = "Venthyr",
	MAINZONES = "주요 지역", -- Needs review
	OTHERCATEGORIES = "기타 분류", -- Needs review
	NINEONECAMPAIGN = "9.1 Campaign",
	ABOMINABLESTICHING = "누더기 봉합술",
	COVENANTASSAULTS = "Covenant Assaults",
	COVENANTSANCTUARY = "Covenant Sanctuary",
	COVENANTSANCTUM = "Covenant Sanctum",
	EMBERCOURT = "Ember Court",
	KEEPERSRESPITE = "수호자의 안식처",
	PATHOFASCENSION = "Path of Ascension",
	THEARCHIVISTSCODEX = "The Archivists' Codex",
	TORGHASTTOWEROFTHEDAMNED = "저주받은 자의 탑 토르가스트",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
	AZEROTHIANARCHIVES = "Azerothian Archives",
	AZMERLOTH = "Azmerloh",
	BRACKENHIDEWATERHOLE = "Brackenhide Waterhole",
	DRAGONISLE = "Dragon Isle",
	DRAGONFLIGHT = "용군단",
	DRAGONSCALEBASECAMP = "Dragonscale Basecamp",
	DRAGONSCALEEXPEDITION = "Dragonscale Expedition",
	DUNGEONS = "Dungeons",
	EMERALDARDENS = "Emerald Gardens",
	HORNSWOGHOLLOW = "Hornswog Hollow",
	ISKAARATUSKARR = "Iskaara Tuskarr",
	LOSTRUINS = "Lost Ruins",
	MARUUKCENTAUR = "Maruuk Centaur",
	OBSIDIANCITADEL = "흑요석 성채", 
	PASSAGEOFTIME = "시간의 통로",
	PRIMALISTSTORMS = "Primalist Storms",
	PRIMORDIALALE = "Primordial Vale",
	RUBYLIFEPOOLS = "루비 생명의 웅덩이",
	RUBYLIFESHRINE = "Ruby Lifeshrine",
	SHADOWLEDGE = "Shadow Legde",
	TEMPESTUNLEASHED = "Tempest Unleashed",
	THEPRIMAISTFUTURE = "The Primalist Future",
	THERONSWATCH = "Theron`s Watch",
	VALDRAKKENACCORD = "Valdrakken Accord",
	KORRAKSREVENGE = "Korrak`s Revenge",
	--TWW
	TWW = "내부 전쟁",
	AWAKENINGTHEMACHINE = "기계의 각성",
	DEEPHAULRAVINE = "깊은광혈 협곡",	
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NERUBARPALACE = "네룹아르 궁전",
	NORTHRENDCUP = "Northrend Cup",
	RAMBLESHIRE = "산책골",
	UPGRADESYSTEM = "Upgrade System",
	WARBANDS = "Warbands",
	ARATHIHIGHLANDSTWW = "Arathi Highlands TWW",
	DELVESHEADQUARTERS = "구렁 탐험가 본부",
	DELVES = "Delves",
	THERAMORESFALLS = "Theramore`s  Fall",
	TIMERUNNING = "Timerunning",
	THEHARBINGER = "The Harbinger",
	GILNEASRECLAMATION = "Gilneas Reclamation",
	LITTLESCALESDAYCARE = "Little Scales Daycare",
	TIMERIFT = "Time Rift",
	AMIRDRASIL = "Amirdrasil",
	AMIRDRASSILTHEDREAMSHOPE = "꿈의 희망 아미드랏실",
	THEOASIS = "오아시스",
	--MID
	MIDNIGHT = "한밤",
	FOUNDERSPOINT = "개척자의 터전",
	NEIGHBORHOOD = "Neighborhood",
	RAZORWINDSHORES = "칼끝바람 해안",
	SLAYERSRISE = "학살자의 오름길",
	WESTSANCTUM = "서부 성소",	
	DEADMINES = "죽음의 폐광",
	LOWERBLACKROCKSPIRE = "검은바위 첨탑 하층",
	THETEMPLEOFATALHAKKAR = "아탈학카르 신전",
	THEBATTLEFORMOUNTHYJAL = "하이잘 산 전투",
	SEATOFTHETRIUMVIRATE = "삼두정의 권좌",
	TAZAVESHTHEVEILEDMARKET = "미지의 시장 타자베쉬",
	ASSAULTONVIOLETHOLD = "보랏빛 요새 침공",
	DIREMAULCAPITALGARDENS = "혈투의 전장 - 수도 정원",
	STRATHOLMEMAINGATE = "스트라솔름 - 정문",
	TEMPLEOFAHNQIRAJ = "안퀴라즈 사원",
	DIREMAULWARPWOODQUARTER = "혈투의 전장 - 굽이나무 지구",
	DIREMAULGORDOKCOMMONS = "혈투의 전장 - 고르독 광장",
	STRATHOLMESERVICEENTRANCE = "스트라솔름 - 공무용 입구",
	WINDRUNNERSPIRE = "윈드러너 첨탑",
	MAGISTERSTERRACE = "마법학자의 정원",
	MURDERROW = "죽음의 골목",
	THEVOIDSPIRE = "공허첨탑",
	THEBLINDINGVALE = "눈부신 골짜기",
	DENOFNALORAKK = "날로라크의 소굴",
	VOIDSCARARENA = "공허흉터 투기장",
	THEDREAMRIFT = "꿈의 균열",
	MAISARACAVERNS = "마이사라 동굴",
	NEXUSPOINTXENAS = "공결탑 제나스",
	PROGRESS = "%d/%d 완료 (%d%%)", -- Needs review
	SEARCHRESULTS = "검색 결과", -- Needs review
	SERVERQUERYRESULT = "서버에 Quest Completist가 아는 완료한 퀘스트가 %d개 있으며, 그중 %d개를 새로 완료로 표시했습니다.", -- Needs review
	CACHECLEARED = "캐시를 비웠습니다.", -- Needs review
	CLEARINGCACHE = "업데이트 캐시를 비우는 중...", -- Needs review
	NODETAILS = "게임에서 퀘스트 정보를 받지 못했습니다", -- Needs review
	QUESTID = "퀘스트 ID:", -- Needs review
	STORYLINE = "퀘스트 라인:", -- Needs review
	STORYLINEPOSITION = "(%d/%d)", -- Needs review
	EARLIERQUESTS = "... 이전 %d개", -- Needs review
	LATERQUESTS = "... %d개 더", -- Needs review
	THISQUEST = "이 퀘스트", -- Needs review
	UNKNOWNQUEST = "알 수 없는 퀘스트", -- Needs review
	REQUIREDQUEST = "필요 퀘스트:", -- Needs review
	UNKNOWNFACTION = "알 수 없는 세력", -- Needs review
	REQUIREDFACTION = "필요 세력:", -- Needs review
	REQUIREDRENOWN = "필요 명성 레벨:", -- Needs review
	REQUIREDRANK = "필요 등급:", -- Needs review
	RANKLEVEL = "%d등급", -- Needs review
	DATAUNAVAILABLE = "데이터 없음", -- Needs review
	QUESTGIVER = "퀘스트 제공자:", -- Needs review
	UNKNOWNNPC = "알 수 없는 NPC", -- Needs review
	NOQUESTGIVER = "알 수 없음 또는 자동 수락 퀘스트", -- Needs review
	REPAMOUNT = "평판 %d", -- Needs review
	NEWDATAINTRO = "Quest Completist가 다음 정보를 알지 못했습니다. CurseForge에 알려 주시면 애드온의 정확도를 높이는 데 도움이 됩니다.", -- Needs review
	NEWDATAQUEST = " - 데이터베이스에 없는 퀘스트입니다.", -- Needs review
	NEWDATAFACTION = " - QC는 당신의 진영이 이 퀘스트를 완료할 수 있다는 것을 몰랐습니다.", -- Needs review
	NEWDATARACE = " - QC는 당신의 종족이 이 퀘스트를 완료할 수 있다는 것을 몰랐습니다.", -- Needs review
	NEWDATACLASS = " - QC는 당신의 직업이 이 퀘스트를 완료할 수 있다는 것을 몰랐습니다.", -- Needs review
	NEWDATAALERT = "새 데이터 발견 - 제보해 주세요!", -- Needs review
	BREADCRUMBAVAILABLE = "연결 퀘스트 1개를 받을 수 있습니다!", -- Needs review
	BREADCRUMBSAVAILABLE = "연결 퀘스트 %d개를 받을 수 있습니다!", -- Needs review
	BREADCRUMBQUESTS = "연결 퀘스트", -- Needs review
	MUTUALLYEXCLUSIVE = "이 퀘스트는 다른 퀘스트와 함께 완료할 수 없어, 그중 하나만 완료할 수 있습니다. 다른 퀘스트:", -- Needs review
	NOTINDATABASE = "데이터베이스에 없는 퀘스트", -- Needs review
	YOURSELF = "<자신>", -- Needs review
	OTHERQUESTS = "기타 퀘스트", -- Needs review
	PINDONE = "%d개 완료", -- Needs review
	PINSHOWDONE = "Shift로 보기", -- Needs review
	PINWAYPOINT = "클릭하여 TomTom 웨이포인트 설정", -- Needs review
	WELCOME = "Quest Completist를 사용해 주셔서 감사합니다. 퀘스트 정보에 오류가 있나요? CurseForge에 알려 주세요.", -- Needs review
	UNAVAILABLEACCEPTED = "퀘스트 %d \"%s\"은(는) 더 이상 받을 수 없는 퀘스트로 표시되어 있지만 방금 수락했습니다. 당신에게는 정상적으로 표시됩니다. 목록을 바로잡을 수 있도록 알려 주세요.", -- Needs review
	UNAVAILABLETURNEDIN = "퀘스트 %d \"%s\"은(는) 더 이상 받을 수 없는 퀘스트로 표시되어 있지만 방금 완료했습니다. 당신에게는 정상적으로 표시됩니다. 목록을 바로잡을 수 있도록 알려 주세요.", -- Needs review
	TOGGLEFRAME = "창 표시/숨기기", -- Needs review
	UNKNOWNZONE = "알 수 없는 지역", -- Needs review
	}, {__index = qcLocalize})

end