if GetLocale() == "deDE" then
qcLocalize = setmetatable({
	AHNQIRAJTHEFALLENKINGDOM = "Ahn'Qiraj: Das Gefallene Königreich",
	ALCHEMY = "Alchemie",
	ARCHAEOLOGY = "Archäologie",
	ASSAULTONTHEDARKPORTAL = "Angriff auf das Dunkle Portal",
	AZEROTH = "Azeroth",
	BARADINHOLD = "Baradinfestung",
	BATTLEGROUNDS = "Schlachtfelder",
	BATTLEPETS = "Kampfhaustiere",
	BLACKSMITHING = "Schmiedekunst",
	BLACKWINGDESCENT = "Pechschwingenabstieg",
	BLACKWINGLAIR = "Pechschwingenhort",
	BRAWLERSGUILD = "Kampfgilde",
	BREWFEST = "Braufest",
	CAVERNSOFTIME = "Höhlen der Zeit",
	CENTRALKALIMDOR = "Zentral Kalimdor",
	CHILDRENSWEEK = "Kinderwoche",
	CLASSES = "Klassen",
	CLASSQUESTS = "Klassenquests",
	CLEARUPDATECACHE = "Lösche und aktualisiere Cache...",
	COILFANGRESERVOIR = "Echsenkessel",
	COMBINEDMAPANDQUESTFILTERS = "Kombinierte Karten- und Questlisten-Filter",
	CONFIGSUBTITLE = "Diese Option erlaubt dir die Art und Weise zu ändern, wie Quest Completist seine Daten verwendet und filtert.",
	CONFIGTITLE = "Quest Completist - Konfiguration",
	CONTINENTS = "Kontinente",
	COOKING = "Kochkunst",
	DARKMOONFAIRE = "Dunkelmond-Jahrmarkt",
	DAYOFTHEDEAD = "Tag der Toten",
	DEATHKNIGHT = "Todesritter",
	DRAENOR = "Draenor",
	DRAGONSOUL = "Drachenseele",
	DRUID = "Druide",
	DUNGEONSANDRAIDS = "Dungeons und Schlachtzüge",
	EASTERNKINGDOMS = "Östliche Königreiche",
	ELEMENTALBONDS = "Elementare Bande",
	ENCHANTING = "Verzauberkunst",
	ENGINEERING = "Ingenieurskunst",
	FIRELANDS = "Feuerlande",
	FIRELANDSINVASION = "Die Invasion der Feuerlande",
	FIRSTAID = "Erste Hilfe",
	FISHING = "Angeln",
	GARRISONCAMPAIGN = "Garnisonskampagne",
	GARRISONSUPPORT = "Unterstützung der Garnison",
	GREENSTONEVILLAGE = "Grünstein",
	GRUULSLAIR = "Gruuls Unterschlupf",
	HALLOWSEND = "Schlotternächte",
	HARVESTFESTIVAL = "Erntedankfest",
	HELLFIRECITADEL = "Höllenfeuerzitadelle",
	HERBALISM = "Kräuterkunde",
	HIDECOMPLETEDQUESTS = "Verstecke abgeschlossene Quests",
	HIDEDAILYQUEST = "Verstecke Tägliche Quests",
	HIDEINPROGRESSQUESTS = "Verstecke laufende Quests",
	HIDELOWLEVELQUESTS = "Verstecke niedrigstufige Quests",
	HIDENONACTIVESEASONALQUESTS = "Verstecke nicht aktive saisonale Quests",
	HIDEOTHERFACTIONQUESTS = "Verstecke Quests der anderen Fraktion",
	HIDEOTHERPROFESSIONQUESTS = "Verstecke Quests anderer Berufe",
	HIDEOTHERRACEANDCLASSQUESTS = "Verstecke Quests anderer Rassen und Klassen",
	HIDEOTHERCOVENANTQUESTS = "Verstecke Quests anderer Covenant",
	HIDEWARBANDS = "Verstecke Quests, die andere Charaktere deiner Kriegsmeute erledigt haben", -- Needs review
	HIDEUNAVAILABLE = "Verstecke Quests, die nicht mehr verfügbar sind", -- Needs review
	HIDEREQUIREMENTSNOTMET = "Verstecke Quests mit unerfüllten Voraussetzungen", -- Needs review
	HIDENODATA = "Verstecke Markierungen ohne Questdaten", -- Needs review
	HIDEREPEATABLEQUEST = "Verstecke wiederholbare Quests", -- Needs review
	HIDEWEEKLYQUEST = "Hide Weekly Quests",
	HIDEWORLDQUEST = "Verstecke Weltquest",
	HUNTER = "Jäger",
	INSCRIPTION = "Inschriftenkunde",
	ISLEOFGIANTS = "Insel der Riesen",
	JADETEMPLEGROUNDS = "Jade Temple Grounds", -- Requires localization
	JEWELCRAFTING = "Juwelierskunst",
	KALIMDOR = "Kalimdor",
	KHAZMODAN = "Khaz Modan",
	LANDFALL = "Landung",
	LEATHERWORKING = "Lederverarbeitung",
	LEGENDARY = "Legendär",
	LORDAERON = "Lordaeron",
	LOVEISINTHEAIR = "Liebe liegt in der Luft",
	LUNARFESTIVAL = "Mondfest",
	MAGE = "Magier",
	MAPFILTERS = "Kartenfilter",
	MIDSUMMERFIREFESTIVAL = "Sonnenwendfest",
	MINING = "Bergbau",
	MISCELLANEOUS = "Verschiedenes",
	MOGUSHANVAULTS = "Mogu'shangewölbe",
	MONK = "Mönch",
	NAGRAND = "Nagrand",
	NEWYEARSEVE = "Silvester",
	NOBLEGARDEN = "Nobelgartenfest",
	NORTHERNKALIMDOR = "Nördliches Kalimdor",
	NORTHREND = "Nordend",
	ONYXIASLAIR = "Onyxias Hort",
	OPTIONS = "Optionen",
	OUTLAND = "Scherbenwelt",
	PALACEOFTHEHEAVENS = "Himmelspalast",
	PALADIN = "Paladin",
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Pandarenkampagne",
	PANDARIA = "Pandaria",
	PEAKOFSERENITY = "Peak of Serenity", -- Requires localization
	PERFORMSERVERQUERY = "Server-Abfrage durchführen...",
	PILGRIMSBOUNTY = "Pilgerfreudenfest",
	PRIEST = "Priester",
	PROFESSIONS = "Berufe",
	QUERYREQUESTED = "Eine Serverabfrage wird durchgeführt...",
	QUESTLISTFILTERS = "Questlisten-Filter",
	QUESTSFOUND = "%d gefundene Quests",
	RAIDS = "Schlachtzüge",
	REGIONS = "Gebiete",
	RIDING = "Riding", -- Requires localization
	ROGUE = "Schurke",
	RUINSOFGILNEASCITY = "Ruinen der Stadt Gilneas",
	SCENARIO = "Scenario", -- Requires localization
	SEASONAL = "Saisonal",
	SERPENTSHRINECAVERN = "Höhle des Schlangenschreins",
	SHADOWMOONVALLEY = "Schattenmondtal",
	SHAMAN = "Schamane",
	SHOWMAPICONS = "Zeige Kartensymbole",
	SKETTIS = "Skettis", -- Requires localization
	SKINNING = "Kürschnerei",
	SORTALPHA = "Sortierung: Alphabetisch",
	SORTLEVEL = "Sortierung: Stufe",
	SOUTHERNKALIMDOR = "Südliches Kalimdor",
	SPECIAL = "Besonderes",
	SPECIALS = "Spezielles", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "Schlingendorntal",
	TAILORING = "Schneiderei",
	TEMPLEOFTHEREDCRANE = "Temple des Roten Kranichs",
	THEARBORETUM = "The Arboretum", -- Requires localization
	THEBASTIONOFTWILIGHT = "Die Bastion des Zwielichts",
	THEBLACKMORASS = "Der Schwarze Morast",
	THEEVERBLOOM = "Der Immergrüne Flor",
	THEEYE = "Das Auge",
	THEGATEOFTHESETTINGSUN = "Das Tor der untergehenden Sonne",
	THEHALFHILLMARKET = "Der Halbhügel Markt",
	THEMAELSTROM = "Der Mahlstrom",
	THEOBSIDIANSANCTUM = "Das Obsidiansanktum",
	THETEMPLEOFTHEJADESERPENT = "Der Tempel der Jadeschlange",
	THEVIOLETHOLD = "Die Violette Festung",
	THEZANDALARI = "Die Zandalari",
	THRONEOFTHEFOURWINDS = "Thron der vier Winde",
	TOURNAMENT = "Turnier",
	UPPERBLACKROCKSPIRE = "Obere Schwarzfelsspitze",
	UNCATEGORIZED = "Nicht kategorisiert", -- Needs review
	VASHJIR = "Vashj'ir",
	VAULTOFARCHAVON = "Archavons Kammer",
	WARLOCK = "Hexenmeister",
	WARRIOR = "Krieger",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "Wöchentliche Events", -- Needs review
	WINTERVEIL = "Winterhauchfest",
	WORLDEVENTS = "Weltereignisse",
	THEBROKENISLES = "The Broken Isles",	
	THEDREAMGROVE = "Der Hain der Träume",
	DEMONHUNTER = "Dämonenjäger",
	CONTESTCOMMING = "Contest comming shows wrong zone",
	HALLOFTHEGUARDIAN = "Die Halle des Wächters",
	MARDUMTHESHATTEREDABYSS = "Mardum, the Shattered Abyss",
	NETHERLIGHTTEMPLE = "Der Netherlichttempel",
	SKYHOLD = "Die Himmelsfeste",
	THEHEARTOFAZERTH = "The Heart of Azeroth",
	THEWANDERINGISLE = "The Wandering Isle Monk",
	TRUESHOTLODGE = "Trueshot Lodge Hunter",
	MAWOFSOULS = "Der Seelenschlund",
	LEGIONUNCATEQUEST = "Legion Uncategorized Quests",
	RETURNTOKARAZHAN = "Rückkehr nach Karazhan",
	MACAREE = "Mac'Aree",
	DREADSCARRIFT = "Die Schreckensnarbe",
	HELHEIM = "Helheim",
	EMERALDDREAMWAY = "Emerald Dreamway",
	BFA = "Battle For Azeroth",
	ZANDALAR = "Zandalar",
	KULTIRAS = "Kul Tiras",
	THUNDERTOTEM = "Thunder Totem",
	KINGSREST = "Die Königsruh",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	THRUNDERROT = "The Underrot",
	THEDEATHOFCHROMIE = "The Deaths Of Chromie",
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	THEDRAGONSSPINE = "The Dragon`s Spine",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	TERRACEOFENLESSSPRINGS = "Terrasse d. Endlosen Frühlings",
	PLAYERVSPLAYER = "Player Vs Player",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
	WORLDPVP = "World Pvp",
	NYALOTHATHEWALKINGCITY = "Ny'alotha, die Erwachte Stadt",
	VISIONSOFNZOTH = "Visions of N'Zoth",
	BLACKEMPIRECAMPAIGN = "Black Empire Campaign",
	WORLDQUEST = "World Quests",
	-- Shadowlands Code
	SHADOWLANDS = "Shadowlands",
	SHADOWLANDSUNCATEQUEST = "Shadowlands Uncategorized Quests",
	COVENANTCALLINGS = "Covenant Callings",
	KYRIAN = "Kyrian",
	NECROLORD = "Necrolord",
	NIGHTFAE = "Night Fae",
	VENTHYR = "Venthyr",
	MAINZONES = "Hauptzonen", -- Needs review
	OTHERCATEGORIES = "Weitere Kategorien", -- Needs review
	NINEONECAMPAIGN = "9.1 Campaign",
	ABOMINABLESTICHING = "Monstrositätenflickerei",
	COVENANTASSAULTS = "Covenant Assaults",
	COVENANTSANCTUARY = "Covenant Sanctuary",
	COVENANTSANCTUM = "Covenant Sanctum",
	EMBERCOURT = "Ember Court",
	KEEPERSRESPITE = "Zuflucht des Hüters",
	PATHOFASCENSION = "Path of Ascension",
	THEARCHIVISTSCODEX = "The Archivists' Codex",
	TORGHASTTOWEROFTHEDAMNED = "Torghast, Turm der Verdammten",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
	AZEROTHIANARCHIVES = "Azerothian Archives",
	AZMERLOTH = "Azmerloh",
	BRACKENHIDEWATERHOLE = "Brackenhide Waterhole",
	DRAGONISLE = "Dragon Isle",
	DRAGONFLIGHT = "Dragonflight",
	DRAGONSCALEBASECAMP = "Dragonscale Basecamp",
	DRAGONSCALEEXPEDITION = "Dragonscale Expedition",
	DUNGEONS = "Dungeons",
	EMERALDARDENS = "Emerald Gardens",
	HORNSWOGHOLLOW = "Hornswog Hollow",
	ISKAARATUSKARR = "Iskaara Tuskarr",
	LOSTRUINS = "Lost Ruins",
	MARUUKCENTAUR = "Maruuk Centaur",
	OBSIDIANCITADEL = "Obsidianzitadelle", 
	PASSAGEOFTIME = "Zeitenfluss",
	PRIMALISTSTORMS = "Primalist Storms",
	PRIMORDIALALE = "Primordial Vale",
	RUBYLIFEPOOLS = "Rubinlebensbecken",
	RUBYLIFESHRINE = "Ruby Lifeshrine",
	SHADOWLEDGE = "Shadow Legde",
	TEMPESTUNLEASHED = "Tempest Unleashed",
	THEPRIMAISTFUTURE = "The Primalist Future",
	THERONSWATCH = "Theron`s Watch",
	VALDRAKKENACCORD = "Valdrakken Accord",
	KORRAKSREVENGE = "Korrak`s Revenge",
		--TWW
	--TWW
	TWW = "The War Within",
	AWAKENINGTHEMACHINE = "Erweckung der Maschine",
	DEEPHAULRAVINE = "Tiefbeuteschlucht",	
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NERUBARPALACE = "Palast der Nerub'ar",
	NORTHRENDCUP = "Northrend Cup",
	RAMBLESHIRE = "Bummelgau",
	UPGRADESYSTEM = "Upgrade System",
	WARBANDS = "Warbands",
	ARATHIHIGHLANDSTWW = "Arathi Highlands TWW",
	DELVESHEADQUARTERS = "Tiefenforscherhauptquartier",
	DELVES = "Delves",
	THERAMORESFALLS = "Theramore`s  Fall",
	TIMERUNNING = "Timerunning",
	THEHARBINGER = "The Harbinger",
	GILNEASRECLAMATION = "Gilneas Reclamation",
	LITTLESCALESDAYCARE = "Little Scales Daycare",
	TIMERIFT = "Time Rift",
	AMIRDRASIL = "Amirdrasil",
	AMIRDRASSILTHEDREAMSHOPE = "Amirdrassil, Hoffnung des Traums",
	THEOASIS = "Die Oase",
	--MID
	MIDNIGHT = "Midnight",
	FOUNDERSPOINT = "Gründerspitze",
	NEIGHBORHOOD = "Neighborhood",
	RAZORWINDSHORES = "Klingenschluchtküste",
	SLAYERSRISE = "Schlächteranhöhe",
	WESTSANCTUM = "Sanktum des Westens",	
	DEADMINES = "Todesminen",
	LOWERBLACKROCKSPIRE = "Untere Schwarzfelsspitze",
	THETEMPLEOFATALHAKKAR = "Der Tempel von Atal'Hakkar",
	THEBATTLEFORMOUNTHYJAL = "Die Schlacht um den Hyjal",
	SEATOFTHETRIUMVIRATE = "Sitz des Triumvirats",
	TAZAVESHTHEVEILEDMARKET = "Tazavesh, der Verhüllte Markt",
	ASSAULTONVIOLETHOLD = "Sturm auf die Violette Festung",
	DIREMAULCAPITALGARDENS = "Düsterbruch - Hauptstadtgärten",
	STRATHOLMEMAINGATE = "Stratholme - Haupttor",
	TEMPLEOFAHNQIRAJ = "Tempel von Ahn'Qiraj",
	DIREMAULWARPWOODQUARTER = "Düsterbruch - Wucherborkenviertel",
	DIREMAULGORDOKCOMMONS = "Düsterbruch - Gordokhallen",
	STRATHOLMESERVICEENTRANCE = "Stratholme - Dienstboteneingang",
	WINDRUNNERSPIRE = "Windläuferturm",
	MAGISTERSTERRACE = "Terrasse der Magister",
	MURDERROW = "Mördergasse",
	THEVOIDSPIRE = "Die Leerenspitze",
	THEBLINDINGVALE = "Das blendende Tal",
	DENOFNALORAKK = "Nalorakks Bau",
	VOIDSCARARENA = "Arena der Leerennarbe",
	THEDREAMRIFT = "Der Traumriss",
	MAISARACAVERNS = "Maisarakavernen",
	NEXUSPOINTXENAS = "Nexuspunkt Xenas",
	PROGRESS = "%d/%d abgeschlossen (%d%%)", -- Needs review
	SEARCHRESULTS = "Suchergebnisse", -- Needs review
	SERVERQUERYRESULT = "Der Server meldet %d abgeschlossene Quests, die Quest Completist kennt, davon %d neu als abgeschlossen markiert.", -- Needs review
	CACHECLEARED = "Cache geleert.", -- Needs review
	CLEARINGCACHE = "Dein Update-Cache wird geleert...", -- Needs review
	NODETAILS = "Das Spiel liefert keine Questdetails", -- Needs review
	QUESTID = "Quest-ID:", -- Needs review
	STORYLINE = "Questreihe:", -- Needs review
	STORYLINEPOSITION = "(%d von %d)", -- Needs review
	EARLIERQUESTS = "... %d frühere", -- Needs review
	LATERQUESTS = "... %d weitere", -- Needs review
	ONQUEST = "Du hast diese Quest", -- Needs review
	COMPLETED = "Abgeschlossen", -- Needs review
	NOTCOMPLETED = "Nicht abgeschlossen", -- Needs review
	UNKNOWNQUEST = "Unbekannte Quest", -- Needs review
	REQUIREDQUEST = "Benötigte Quest:", -- Needs review
	UNKNOWNFACTION = "Unbekannte Fraktion", -- Needs review
	REQUIREDFACTION = "Benötigte Fraktion:", -- Needs review
	REQUIREDRENOWN = "Benötigte Ruhmstufe:", -- Needs review
	RENOWNMET = "%d (erfüllt)", -- Needs review
	RENOWNNOTMET = "%d (nicht erfüllt)", -- Needs review
	DATAUNAVAILABLE = "Daten nicht verfügbar", -- Needs review
	QUESTGIVER = "Questgeber:", -- Needs review
	UNKNOWNNPC = "Unbekannter NSC", -- Needs review
	NOQUESTGIVER = "Unbekannt, oder automatisch angenommene Quest", -- Needs review
	REPAMOUNT = "%d Ruf", -- Needs review
	NEWDATAINTRO = "Quest Completist kannte die folgenden Informationen noch nicht. Bitte hilf, das Addon genauer zu machen, indem du sie auf CurseForge meldest.", -- Needs review
	NEWDATAQUEST = " - Die Quest fehlt in der Datenbank.", -- Needs review
	NEWDATAFACTION = " - QC wusste nicht, dass deine FRAKTION diese Quest abschließen kann.", -- Needs review
	NEWDATARACE = " - QC wusste nicht, dass deine RASSE diese Quest abschließen kann.", -- Needs review
	NEWDATACLASS = " - QC wusste nicht, dass deine KLASSE diese Quest abschließen kann.", -- Needs review
	NEWDATAALERT = "Neue Daten gefunden - bitte melden!", -- Needs review
	BREADCRUMBAVAILABLE = "1 Brotkrumen-Quest verfügbar!", -- Needs review
	BREADCRUMBSAVAILABLE = "%d Brotkrumen-Quests verfügbar!", -- Needs review
	BREADCRUMBQUESTS = "Brotkrumen-Quests", -- Needs review
	MUTUALLYEXCLUSIVE = "Diese Quest schließt andere aus: Du kannst nur eine davon abschließen. Die anderen Quests sind:", -- Needs review
	NOTINDATABASE = "Quest nicht in der Datenbank", -- Needs review
	YOURSELF = "<Du selbst>", -- Needs review
	OTHERQUESTS = "Weitere Quests", -- Needs review
	PINDONE = "%d erledigt", -- Needs review
	PINSHOWDONE = "Umschalt zum Anzeigen", -- Needs review
	WELCOME = "Danke, dass du Quest Completist nutzt. Ist dir ein Fehler bei einer Quest aufgefallen? Bitte melde ihn auf CurseForge.", -- Needs review
	UNAVAILABLEACCEPTED = "Quest %d \"%s\" ist als nicht mehr verfügbar eingetragen, aber du hast sie gerade angenommen. Bei dir wird sie normal angezeigt; bitte melde es, damit die Liste korrigiert werden kann.", -- Needs review
	UNAVAILABLETURNEDIN = "Quest %d \"%s\" ist als nicht mehr verfügbar eingetragen, aber du hast sie gerade abgegeben. Bei dir wird sie normal angezeigt; bitte melde es, damit die Liste korrigiert werden kann.", -- Needs review
	TOGGLEFRAME = "Fenster ein-/ausblenden", -- Needs review
	UNKNOWNZONE = "Unbekannte Zone", -- Needs review
	}, {__index = qcLocalize})

end