if GetLocale() == "esMX" then
qcLocalize = setmetatable({
	AHNQIRAJWAR = "Guerra de Ahn'Qiraj",
	ASSAULTONTHEDARKPORTAL = "Asalto al Portal Oscuro",
	CAMPING = "Campamento",
	CENTRALKALIMDOR = "Kalimdor central", -- Needs review
	CLASSES = "Clases", -- Needs review
	CLASSQUESTS = "Misiones de clase", -- Needs review
	CLEARUPDATECACHE = "Limpiar la data del caché", -- Needs review
	CONFIGSUBTITLE = "Estas opciones te permiten cambiar la manera en que Quest Completlist maneja y filtra la información", -- Needs review
	CONFIGTITLE = "Quest Completlist - Configuración", -- Needs review
	CONTINENTS = "Continentes", -- Needs review
	DAYOFTHEDEAD = "Festividad de los Muertos",
	DEATHRISING = "La muerte acecha",
	ELEMENTALBONDS = "Vínculos elementales",
	FIRELANDSINVASION = "Invasión de las Tierras de Fuego",
	GARRISONCAMPAIGN = "Campaña de fortaleza",
	GARRISONSUPPORT = "Soporte para fortaleza",
	HIDECOMPLETEDQUESTS = "Esconder misiones completadas", -- Needs review
	HIDEDAILYQUEST = "Ocultar misiones diarias", -- Needs review
	HIDEINPROGRESSQUESTS = "Esconder misiones en progreso", -- Needs review
	HIDELOWLEVELQUESTS = "Esconder misiones de bajo nivel", -- Needs review
	HIDENONACTIVESEASONALQUESTS = "Esconder misiones inactivas de festividades", -- Needs review
	HIDEOTHERFACTIONQUESTS = "Esconder misiones de otras facciones", -- Needs review
	HIDEOTHERPROFESSIONQUESTS = "Esconder misiones de otras profesiones", -- Needs review
	HIDEOTHERRACEANDCLASSQUESTS = "Esconder misiones de otras razas y clases", -- Needs review
	HIDEOTHERCOVENANTQUESTS = "Ocultar misiones de otras curias", -- Needs review
	HIDEWARBANDS = "Ocultar misiones hechas por otros personajes de la banda guerrera", -- Needs review
	HIDEUNAVAILABLE = "Ocultar misiones que ya no están disponibles", -- Needs review
	HIDEREQUIREMENTSNOTMET = "Ocultar misiones con requisitos sin cumplir", -- Needs review
	HIDENODATA = "Ocultar marcadores sin datos de misión", -- Needs review
	HIDEREPEATABLEQUEST = "Ocultar misiones repetibles", -- Needs review
	HIDEWORLDQUEST = "Ocultar misiones de mundo y semanales", -- Needs review
	INVASION = "Invasión",
	KHAZMODAN = "Khaz Modan", -- Requires localization
	LANDFALL = "Desembarco",
	LORDAERON = "Lordaeron", -- Requires localization
	LUNARFESTIVAL = "Festival Lunar",
	MIDSUMMER = "Verano",
	NORTHERNKALIMDOR = "Kalimdor del norte", -- Needs review
	PANDARENBREWMASTERS = "Maestros cerveceros pandaren",
	PANDARENCAMPAIGN = "Campaña pandaren",
	PERFORMSERVERQUERY = "Hacer una búsqueda en el servidor", -- Needs review
	QUERYREQUESTED = "Se ha solicitado una búsqueda en el servidor...", -- Needs review
	QUESTLIST = "Lista de misiones", -- Needs review
	QUESTSFOUND = "%d misiones encontradas", -- Needs review
	SEASONAL = "Estacional",
	SHOWMAPICONS = "Mostrar iconos en el mapa", -- Needs review
	SKETTIS = "Skettis", -- Requires localization
	SORTALPHA = "Ordenar: Alfabéticamente", -- Needs review
	SORTLEVEL = "Ordenar: Por nivel", -- Needs review
	SOUTHERNKALIMDOR = "Kalimdor del sur", -- Needs review
	SPECIALS = "Especiales", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "Vega de Tuercespina", -- Needs review
	THEZANDALARI = "Los Zandalari",
	TOURNAMENT = "Torneo",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "Eventos semanales", -- Needs review
	WORLDEVENTS = "Eventos del Mundo", -- Needs review
	MACAREE = "Mac'Aree",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	ALLIANCEWARCAMPAIGN = "Campaña de guerra de la Alianza",
	HORDEWARCAMPAIGN = "Campaña de guerra de la Horda",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	HERITAGE = "Legado",
	RATEDPVP = "JcJ puntuado",
	WORLDPVP = "JcJ en el mundo",
	BLACKEMPIRECAMPAIGN = "Campaña del Imperio Negro",
	-- Shadowlands Code
	MAINZONES = "Zonas principales", -- Needs review
	OTHERCATEGORIES = "Otras categorías", -- Needs review
	COVENANTASSAULTS = "Asaltos de pactos",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
	--TWW
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NORTHRENDCUP = "Copa de Rasganorte",
	UPGRADESYSTEM = "Sistema de mejoras",
	WARBANDS = "Tropas",
	TIMERUNNING = "Cronotravesía",
	THEHARBINGER = "La Emisaria",
	GILNEASRECLAMATION = "La recuperación de Gilneas",
	TIMERIFT = "Time Rift",
	--MID
	NEIGHBORHOOD = "Neighborhood",
	PROGRESS = "%d/%d completadas (%d%%)", -- Needs review
	SERVERQUERYRESULT = "El servidor reporta %d misiones completadas que Quest Completist conoce, %d de ellas marcadas como completadas por primera vez.", -- Needs review
	CACHECLEARED = "Caché vaciada.", -- Needs review
	CLEARINGCACHE = "Vaciando tu caché de actualización...", -- Needs review
	NODETAILS = "El juego no ofrece los detalles de la misión", -- Needs review
	QUESTID = "ID de misión:", -- Needs review
	STORYLINEPOSITION = "(%d de %d)", -- Needs review
	CAMPAIGNCHAPTER = "(Capítulo %d de %d)", -- Needs review
	EARLIERQUESTS = "... %d anteriores", -- Needs review
	LATERQUESTS = "... %d más", -- Needs review
	THISQUEST = "esta misión", -- Needs review
	REQUIREDQUEST = "Misión necesaria:", -- Needs review
	REQUIREDFACTION = "Facción necesaria:", -- Needs review
	REQUIREDRENOWN = "Nivel de renombre necesario:", -- Needs review
	REQUIREDRANK = "Rango necesario:", -- Needs review
	REQUIREDSKILL = "Habilidad necesaria:", -- Needs review
	RANKLEVEL = "Rango %d", -- Needs review
	QUESTGIVER = "Ofrece la misión:", -- Needs review
	NOQUESTGIVER = "Desconocido, o misión aceptada automáticamente", -- Needs review
	REPAMOUNT = "%d de reputación", -- Needs review
	NEWDATAINTRO = "Quest Completist no conocía la siguiente información. Ayuda a mejorar la precisión del addon publicándola en CurseForge.", -- Needs review
	NEWDATAQUEST = " - La misión no existe en la base de datos.", -- Needs review
	NEWDATAFACTION = " - QC no sabía que tu FACCIÓN podía completar esta misión.", -- Needs review
	NEWDATARACE = " - QC no sabía que tu RAZA podía completar esta misión.", -- Needs review
	NEWDATACLASS = " - QC no sabía que tu CLASE podía completar esta misión.", -- Needs review
	NEWDATAALERT = "¡Datos nuevos encontrados - contribuye!", -- Needs review
	BREADCRUMBAVAILABLE = "¡1 misión de introducción disponible!", -- Needs review
	BREADCRUMBSAVAILABLE = "¡%d misiones de introducción disponibles!", -- Needs review
	BREADCRUMBQUESTS = "Misiones de introducción", -- Needs review
	MUTUALLYEXCLUSIVE = "Esta misión excluye a otras: solo puedes completar una de ellas. Las otras misiones son:", -- Needs review
	NOTINDATABASE = "Misión fuera de la base de datos", -- Needs review
	YOURSELF = "<Tú mismo>", -- Needs review
	OTHERQUESTS = "Otras misiones", -- Needs review
	PINDONE = "%d completadas", -- Needs review
	PINSHOWDONE = "Mayús para mostrar", -- Needs review
	PINWAYPOINT = "Haz clic para poner un punto de ruta de TomTom", -- Needs review
	WELCOME = "Gracias por usar Quest Completist. ¿Viste un error en una misión? Repórtalo en CurseForge.", -- Needs review
	UNAVAILABLEACCEPTED = "La misión %d \"%s\" figura como ya no disponible, pero acabas de aceptarla. Se te muestra con normalidad; repórtalo para que se corrija la lista.", -- Needs review
	UNAVAILABLETURNEDIN = "La misión %d \"%s\" figura como ya no disponible, pero acabas de entregarla. Se te muestra con normalidad; repórtalo para que se corrija la lista.", -- Needs review
	TOGGLEFRAME = "Mostrar/ocultar ventana", -- Needs review
	}, {__index = qcLocalize})
end