if GetLocale() == "frFR" then
qcLocalize = setmetatable({
	ASSAULTONTHEDARKPORTAL = "Assaut sur la Porte des ténèbres",
	CENTRALKALIMDOR = "Centre de Kalimdor",
	CLASSES = "Classes",
	CLASSQUESTS = "Quêtes de classes",
	CLEARUPDATECACHE = "Effacer le cache des quêtes...",
	CONFIGSUBTITLE = "Ces options vous permettent de modifier la façon dont Quests Completist gère et filtre les données.",
	CONFIGTITLE = "Quest Completist - Configuration",
	CONTINENTS = "Continents",
	DAYOFTHEDEAD = "Jour des morts",
	ELEMENTALBONDS = "Liens élémentaires",
	FIRELANDSINVASION = "Invasion des terres de Feu",
	GARRISONCAMPAIGN = "Campagne de Fief",
	GARRISONSUPPORT = "Support de Fief",
	HIDECOMPLETEDQUESTS = "Cacher les quêtes achevées",
	HIDEDAILYQUEST = "Cacher les quêtes journalières", -- Needs review
	HIDEINPROGRESSQUESTS = "Cacher les quêtes en cours",
	HIDELOWLEVELQUESTS = "Cacher les quêtes de bas niveau",
	HIDENONACTIVESEASONALQUESTS = "Cacher les quêtes saisonnière non disponible",
	HIDEOTHERFACTIONQUESTS = "Cacher les quêtes des autres factions",
	HIDEOTHERPROFESSIONQUESTS = "Cacher les quêtes des autres métiers",
	HIDEOTHERRACEANDCLASSQUESTS = "Cacher les quêtes des autres classe / races                                                  |cff1784d1Translated by: Deadse-Voljin EU|r",
	HIDEOTHERCOVENANTQUESTS = "Cacher les quêtes des autres congrégations", -- Needs review
	HIDEWARBANDS = "Cacher les quêtes faites par d'autres personnages du bataillon", -- Needs review
	HIDEUNAVAILABLE = "Cacher les quêtes qui ne sont plus disponibles", -- Needs review
	HIDEREQUIREMENTSNOTMET = "Cacher les quêtes aux conditions non remplies", -- Needs review
	HIDENODATA = "Cacher les marqueurs sans données de quête", -- Needs review
	HIDEREPEATABLEQUEST = "Cacher les quêtes répétables", -- Needs review
	HIDEWORLDQUEST = "Cacher les expéditions et les quêtes hebdomadaires", -- Needs review
	KHAZMODAN = "Khaz Modan",
	LANDFALL = "Accostage",
	LORDAERON = "Lordaeron",
	LUNARFESTIVAL = "Fête lunaire",
	MIDSUMMER = "Solstice d'été",
	NORTHERNKALIMDOR = "Nord de Kalimdor",
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Campagne Pandaren",
	PERFORMSERVERQUERY = "Effectuer une requête serveur...",
	QUERYREQUESTED = "Une requête serveur a été demandé...",
	QUESTLIST = "Liste des quêtes", -- Needs review
	QUESTSFOUND = "%d quêtes trouvées", -- Needs review
	SEASONAL = "Saisonnier",
	SHOWMAPICONS = "Afficher les points d'exclamations sur la carte du monde",
	SKETTIS = "Skettis", -- Requires localization
	SORTALPHA = "Trier par: Ordre alphabétique",
	SORTLEVEL = "Trier par: Niveau",
	SOUTHERNKALIMDOR = "Sud de Kalimdor",
	SPECIALS = "Spécials",
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "Vallée de Strangleronce",
	THEZANDALARI = "Les zandalari",
	TOURNAMENT = "Tournoi",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "Évènements hebdomadaires", -- Needs review
	WORLDEVENTS = "Évènements mondiaux",
	MACAREE = "Mac'Aree",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
	WORLDPVP = "World Pvp",
	BLACKEMPIRECAMPAIGN = "Black Empire Campaign",
	-- Shadowlands Code
	MAINZONES = "Zones principales", -- Needs review
	OTHERCATEGORIES = "Autres catégories", -- Needs review
	COVENANTASSAULTS = "Covenant Assaults",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
	--TWW
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NORTHRENDCUP = "Northrend Cup",
	UPGRADESYSTEM = "Upgrade System",
	WARBANDS = "Warbands",
	TIMERUNNING = "Timerunning",
	THEHARBINGER = "The Harbinger",
	GILNEASRECLAMATION = "Gilneas Reclamation",
	TIMERIFT = "Time Rift",
	--MID
	NEIGHBORHOOD = "Neighborhood",
	PROGRESS = "%d/%d terminées (%d%%)", -- Needs review
	SEARCHRESULTS = "Résultats de la recherche", -- Needs review
	SERVERQUERYRESULT = "Le serveur signale %d quêtes terminées connues de Quest Completist, dont %d nouvellement marquées comme terminées.", -- Needs review
	CACHECLEARED = "Cache vidé.", -- Needs review
	CLEARINGCACHE = "Vidage de votre cache de mise à jour...", -- Needs review
	NODETAILS = "Le jeu ne fournit pas les détails de la quête", -- Needs review
	QUESTID = "ID de quête :", -- Needs review
	STORYLINE = "Suite de quêtes :", -- Needs review
	STORYLINEPOSITION = "(%d sur %d)", -- Needs review
	EARLIERQUESTS = "... %d précédentes", -- Needs review
	LATERQUESTS = "... %d de plus", -- Needs review
	THISQUEST = "cette quête", -- Needs review
	UNKNOWNQUEST = "Quête inconnue", -- Needs review
	REQUIREDQUEST = "Quête requise :", -- Needs review
	UNKNOWNFACTION = "Faction inconnue", -- Needs review
	REQUIREDFACTION = "Faction requise :", -- Needs review
	REQUIREDRENOWN = "Niveau de renom requis :", -- Needs review
	REQUIREDRANK = "Rang requis :", -- Needs review
	REQUIREDSKILL = "Compétence requise :", -- Needs review
	RANKLEVEL = "Rang %d", -- Needs review
	DATAUNAVAILABLE = "Données indisponibles", -- Needs review
	QUESTGIVER = "Donneur de quête :", -- Needs review
	UNKNOWNNPC = "PNJ inconnu", -- Needs review
	NOQUESTGIVER = "Inconnu, ou quête acceptée automatiquement", -- Needs review
	REPAMOUNT = "%d de réputation", -- Needs review
	NEWDATAINTRO = "Quest Completist ignorait les informations suivantes. Aidez à améliorer la précision de l'addon en les signalant sur CurseForge.", -- Needs review
	NEWDATAQUEST = " - La quête n'existe pas dans la base de données.", -- Needs review
	NEWDATAFACTION = " - QC ignorait que votre FACTION pouvait terminer cette quête.", -- Needs review
	NEWDATARACE = " - QC ignorait que votre RACE pouvait terminer cette quête.", -- Needs review
	NEWDATACLASS = " - QC ignorait que votre CLASSE pouvait terminer cette quête.", -- Needs review
	NEWDATAALERT = "Nouvelles données trouvées - contribuez !", -- Needs review
	BREADCRUMBAVAILABLE = "1 quête d'introduction disponible !", -- Needs review
	BREADCRUMBSAVAILABLE = "%d quêtes d'introduction disponibles !", -- Needs review
	BREADCRUMBQUESTS = "Quêtes d'introduction", -- Needs review
	MUTUALLYEXCLUSIVE = "Cette quête en exclut d'autres : vous ne pouvez en terminer qu'une seule. Les autres quêtes sont :", -- Needs review
	NOTINDATABASE = "Quête absente de la base de données", -- Needs review
	YOURSELF = "<Vous-même>", -- Needs review
	OTHERQUESTS = "Autres quêtes", -- Needs review
	PINDONE = "%d terminées", -- Needs review
	PINSHOWDONE = "Maj pour afficher", -- Needs review
	PINWAYPOINT = "Cliquez pour placer un point de passage TomTom", -- Needs review
	WELCOME = "Merci d'utiliser Quest Completist. Vous avez repéré une erreur sur une quête ? Signalez-la sur CurseForge.", -- Needs review
	UNAVAILABLEACCEPTED = "La quête %d « %s » est indiquée comme n'étant plus disponible, mais vous venez de l'accepter. Elle s'affiche normalement pour vous ; signalez-le pour que la liste soit corrigée.", -- Needs review
	UNAVAILABLETURNEDIN = "La quête %d « %s » est indiquée comme n'étant plus disponible, mais vous venez de la rendre. Elle s'affiche normalement pour vous ; signalez-le pour que la liste soit corrigée.", -- Needs review
	TOGGLEFRAME = "Afficher/masquer la fenêtre", -- Needs review
	UNKNOWNZONE = "Zone inconnue", -- Needs review
	}, {__index = qcLocalize})

end