if GetLocale() == "koKR" then
qcLocalize = {
	ABYSSALDEPTHS = "심연의 나락", -- Needs review
	AHNKAHETTHEOLDKINGDOM = "안카헤트: 고대 왕국",
	AHNQIRAJ = "안퀴라즈",
	AHNQIRAJTHEFALLENKINGDOM = "안퀴라즈: 무너진 왕국", -- Needs review
	ALCHEMY = "연금술", -- Needs review
	ALTERACVALLEY = "알터랙 계곡",
	ARATHIBASIN = "아라시 분지",
	ARATHIHIGHLANDS = "아라시 고원", -- Needs review
	ARCHAEOLOGY = "고고학", -- Needs review
	ASHENVALE = "잿빛 골짜기", -- Needs review
	ASHRAN = "아쉬란",
	ASSAULTONTHEDARKPORTAL = "Assault on the Dark Portal", -- Requires localization
	AUCHENAICRYPTS = "아키나이 납골당",
	AUCHINDOUN = "아킨둔",
	AZEROTH = "아제로스",
	AZJOLNERUB = "아졸네룹",
	AZSHARA = "아즈샤라", -- Needs review
	AZUREMYSTISLE = "하늘안개 섬", -- Needs review
	BADLANDS = "황야의 땅", -- Needs review
	BARADINHOLD = "바라딘 요새",
	BATTLEGROUNDS = "전장", -- Needs review
	BATTLEPETS = "전투 펫", -- Needs review
	BLACKFATHOMDEEPS = "검은심연 나락",
	BLACKROCKCAVERNS = "검은바위 동굴",
	BLACKROCKDEPTHS = "검은바위 나락",
	BLACKROCKFOUNDRY = "검은바위 용광로",
	BLACKROCKSPIRE = "검은바위 첨탑",
	BLACKSMITHING = "대장기술", -- Needs review
	BLACKTEMPLE = "검은 사원",
	BLACKWINGDESCENT = "검은날개 강림지",
	BLACKWINGLAIR = "검은날개 둥지",
	BLADESEDGEMOUNTAINS = "칼날 산맥", -- Needs review
	BLASTEDLANDS = "저주받은 땅", -- Needs review
	BLOODMAULSLAGMINES = "피망치 잿가루 광산",
	BLOODMYSTISLE = "핏빛안개 섬", -- Needs review
	BOREANTUNDRA = "북풍의 땅", -- Needs review
	BRAWLERSGUILD = "Brawler's Guild", -- Requires localization
	BREWFEST = "가을 축제", -- Needs review
	BREWMOONFESTIVAL = "맥주달 축제",
	BURNINGSTEPPES = "불타는 평원", -- Needs review
	CAVERNSOFTIME = "시간의 동굴",
	CENTRALKALIMDOR = "Central Kalimdor", -- Requires localization
	CHILDRENSWEEK = "어린이 주간", -- Needs review
	CLASSES = "직업", -- Needs review
	CLASSQUESTS = "직업 퀘스트", -- Needs review
	CLEARUPDATECACHE = "업데이트 캐쉬 초기화", -- Needs review
	COILFANGRESERVOIR = "갈퀴송곳니 저수지", -- Needs review
	COMBINEDMAPANDQUESTFILTERS = "맵과 퀘스트 목록 혼합 분류", -- Needs review
	CONFIGSUBTITLE = "Quest Completist에서 항목 분류를 통해서 원하는 정보를 빠르게 볼 수 있습니다.", -- Needs review
	CONFIGTITLE = "Quest Completist - 설정", -- Needs review
	CONTINENTS = "대륙", -- Needs review
	COOKING = "요리", -- Needs review
	CRYSTALSONGFOREST = "수정노래 숲", -- Needs review
	DALARAN = "달라란", -- Needs review
	DARKMOONFAIRE = "다크문 축제", -- Needs review
	DARKSHORE = "어둠해안", -- Needs review
	DARNASSUS = "다르나서스", -- Needs review
	DAYOFTHEDEAD = "망자의 날", -- Needs review
	DEADWINDPASS = "저승바람 고개", -- Needs review
	DEATHKNIGHT = "죽음의 기사", -- Needs review
	DEEPHOLM = "심원의 영지", -- Needs review
	DEEPRUNTRAM = "깊은굴 지하철", -- Needs review
	DESOLACE = "잊혀진 땅", -- Needs review
	DIREMAUL = "혈투의 전장",
	DRAENOR = "드레노어",
	DRAGONBLIGHT = "용의 안식처", -- Needs review
	DRAGONSOUL = "용의 영혼",
	DRAKTHARONKEEP = "드락타론 성채",
	DREADWASTES = "공포의 황무지", -- Needs review
	DRUID = "드루이드", -- Needs review
	DUNGEONSANDRAIDS = "던전 & 공격대", -- Needs review
	DUNMOROGH = "던 모로", -- Needs review
	DUROTAR = "듀로타", -- Needs review
	DUSKWOOD = "그늘숲", -- Needs review
	DUSTWALLOWMARSH = "먼지진흙 습지대", -- Needs review
	EASTERNKINGDOMS = "동부 왕국", -- Needs review
	EASTERNPLAGUELANDS = "동부 역병지대", -- Needs review
	ELEMENTALBONDS = "Elemental Bonds", -- Requires localization
	ELWYNNFOREST = "엘윈 숲", -- Needs review
	ENCHANTING = "마법부여", -- Needs review
	ENDTIME = "시간의 끝",
	ENGINEERING = "기계공학", -- Needs review
	EVERSONGWOODS = "영원노래 숲", -- Needs review
	EYEOFTHESTORM = "폭풍의 눈",
	FELWOOD = "악령숲", -- Needs review
	FERALAS = "페랄라스", -- Needs review
	FIRELANDS = "불의 땅",
	FIRELANDSINVASION = "Firelands Invasion", -- Requires localization
	FIRSTAID = "응급치료", -- Needs review
	FISHING = "낚시", -- Needs review
	FROSTFIRERIDGE = "서리불꽃 마루",
	GARRISONCAMPAIGN = "Garrison Campaign", -- Requires localization
	GARRISONSUPPORT = "Garrison Support", -- Requires localization
	GATEOFTHESETTINGSUN = "석양문",
	GHOSTLANDS = "유령의 땅", -- Needs review
	GILNEAS = "길니아스",
	GILNEASCITY = "길니아스 시",
	GNOMEREGAN = "놈리건",
	GORGROND = "고르그론드",
	GREENSTONEVILLAGE = "녹옥 마을",
	GRIMBATOL = "그림 바톨",
	GRIMRAILDEPOT = "파멸철로 정비소",
	GRIZZLYHILLS = "회색 구릉지", -- Needs review
	GRUULSLAIR = "그룰의 둥지",
	GUNDRAK = "군드락",
	HALLOWSEND = "할로윈 축제", -- Needs review
	HALLSOFLIGHTNING = "번개의 전당",
	HALLSOFORIGINATION = "시초의 전당",
	HALLSOFREFLECTION = "투영의 전당",
	HALLSOFSTONE = "돌의 전당",
	HARVESTFESTIVAL = "가을 축제", -- Needs review
	HELLFIRECITADEL = "지옥불 성채", -- Needs review
	HELLFIREPENINSULA = "지옥불 반도", -- Needs review
	HELLFIRERAMPARTS = "지옥불 성루",
	HERBALISM = "약초채집", -- Needs review
	HIDECOMPLETEDQUESTS = "완료된 퀘스트 숨김", -- Needs review
	HIDEDAILYQUEST = "Hide Daily Quests",
	HIDEINPROGRESSQUESTS = "진행중인 퀘스트 숨김", -- Needs review
	HIDELOWLEVELQUESTS = "저레벨 퀘스트 숨김", -- Needs review
	HIDENONACTIVESEASONALQUESTS = "진행중이지 않은 계절 축제 퀘스트 숨김", -- Needs review
	HIDENORMALQUEST = "Hide Normal Quests",
	HIDEOTHERFACTIONQUESTS = "상대진영 퀘스트 숨김", -- Needs review
	HIDEOTHERPROFESSIONQUESTS = "다른 전문기술 퀘스트 숨김", -- Needs review
	HIDEOTHERRACEANDCLASSQUESTS = "다른 종족 및 직업 퀘스트 숨김", -- Needs review
	HIDEOTHERCOVENANTQUESTS = "Hide Other Covenant Quests",
	HIDEWARBANDS = "Hide quests done by other warband's characters",
	HIDEREQUIREMENTSNOTMET = "Hide quests with unfinished requirements",
	HIDENODATA = "Hide pins with no quest data available",
	HIDEREPEATABLEQUEST = "Hide Repeatable Quests",
	HIDEWEEKLYQUEST = "Hide Weekly Quests",
	HIDEWORLDQUEST = "Hide World Quests",
	HIGHMAUL = "높은망치",
	HILLSBRADFOOTHILLS = "언덕마루 구릉지", -- Needs review
	HOUROFTWILIGHT = "황혼의 시간",
	HOWLINGFJORD = "울부짖는 협만", -- Needs review
	HROTHGARSLANDING = "호로스가르 상륙지", -- Needs review
	HUNTER = "사냥꾼", -- Needs review
	HYJALSUMMIT = "하이잘 정상",
	ICECROWN = "얼음왕관", -- Needs review
	ICECROWNCITADEL = "얼음왕관 성채",
	INSCRIPTION = "주문각인", -- Needs review
	IRONDOCKS = "강철 선착장",
	IRONFORGE = "아이언포지", -- Needs review
	ISLEOFCONQUEST = "정복의 섬",
	ISLEOFGIANTS = "괴수의 섬",
	ISLEOFQUELDANAS = "쿠엘다나스 섬", -- Needs review
	ISLEOFTHUNDER = "천둥의 섬",
	JADETEMPLEGROUNDS = "Jade Temple Grounds", -- Requires localization
	JEWELCRAFTING = "보석세공", -- Needs review
	KALIMDOR = "칼림도어", -- Needs review
	KARAZHAN = "카라잔",
	KELPTHARFOREST = "켈프타르 숲", -- Needs review
	KEZAN = "케잔", -- Needs review
	KHAZMODAN = "Khaz Modan", -- Requires localization
	KRASARANGWILDS = "크라사랑 밀림",
	KUNLAISUMMIT = "쿤라이 봉우리",
	LANDFALL = "Landfall", -- Requires localization
	LEATHERWORKING = "가죽세공", -- Needs review
	LEGENDARY = "전설", -- Needs review
	LOCHMODAN = "모단 호수",
	LORDAERON = "Lordaeron", -- Requires localization
	LOSTCITYOFTHETOLVIR = "톨비르의 잃어버린 도시",
	LOVEISINTHEAIR = "온누리에 사랑을", -- Needs review
	LUNARFESTIVAL = "달의 축제", -- Needs review
	MAGE = "마법사", -- Needs review
	MAGISTERSTERRACE = "마법학자의 정원",
	MAGTHERIDONSLAIR = "마그테리돈의 둥지",
	MANATOMBS = "마나 무덤",
	MAPFILTERS = "맵 분류", -- Needs review
	MARAUDON = "마라우돈",
	MIDSUMMERFIREFESTIVAL = "한여름 불꽃 축제", -- Needs review
	MINING = "채광", -- Needs review
	MISCELLANEOUS = "기타", -- Needs review
	MOGUSHANPALACE = "모구샨 궁전",
	MOGUSHANVAULTS = "모구샨 금고",
	MOLTENCORE = "화산 심장부",
	MOLTENFRONT = "녹아내린 전초지",
	MONK = "수도사", -- Needs review
	MOONGLADE = "달숲", -- Needs review
	MOUNTHYJAL = "하이잘 산", -- Needs review
	MULGORE = "멀고어", -- Needs review
	NAGRAND = "나그란드",
	NAXXRAMAS = "낙스라마스",
	NETHERSTORM = "황천의 폭풍",
	NEWYEARSEVE = "New Year's Eve", -- Requires localization
	NOBLEGARDEN = "귀족의 정원", -- Needs review
	NORTHERNBARRENS = "북부 불모의 땅", -- Needs review
	NORTHERNKALIMDOR = "Northern Kalimdor", -- Requires localization
	NORTHERNSTRANGLETHORN = "북부 가시덤불", -- Needs review
	NORTHREND = "노스렌드", -- Needs review
	OLDHILLSBRADFOOTHILLS = "옛 언덕마루 구릉지",
	ONYXIASLAIR = "오닉시아의 둥지",
	OPTIONS = "설정", -- Needs review
	ORGRIMMAR = "오그리마", -- Needs review
	OUTLAND = "아웃랜드", -- Needs review
	PALACEOFTHEHEAVENS = "Palace of the Heavens", -- Requires localization
	PALADIN = "성기사", -- Needs review
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Pandaren Campaign", -- Requires localization
	PANDARIA = "판다리아", -- Needs review
	PEAKOFSERENITY = "Peak of Serenity", -- Requires localization
	PERFORMSERVERQUERY = "서버 질의를 진행합니다...", -- Needs review
	PILGRIMSBOUNTY = "Pilgrim's Bounty", -- Requires localization
	PITOFSARON = "사론의 구덩이",
	PRIEST = "사제", -- Needs review
	PROFESSIONS = "전문기술", -- Needs review
	PROVINGGROUNDS = "Proving Grounds", -- Requires localization
	QUERYREQUESTED = "서버 질의에 응답했습니다...", -- Needs review
	QUESTLISTFILTERS = "퀘스트 목록 분류", -- Needs review
	QUESTSFOUND = "%d 퀘스트 찾음", -- Needs review
	RAGEFIRECHASM = "성난불길 협곡",
	RAIDS = "공격대", -- Needs review
	RAZORFENDOWNS = "가시덩굴 구릉",
	RAZORFENKRAUL = "가시덩굴 우리",
	REDRIDGEMOUNTAINS = "붉은마루 산맥",
	REGIONS = "Regions", -- Requires localization
	RIDING = "Riding", -- Requires localization
	ROGUE = "도적", -- Needs review
	RUINSOFAHNQIRAJ = "안퀴라즈 폐허",
	RUINSOFGILNEAS = "길니아스 폐허",
	RUINSOFGILNEASCITY = "길니아스 시 폐허",
	SCARLETHALLS = "붉은십자군 전당",
	SCARLETMONASTERY = "붉은십자군 수도원",
	SCENARIO = "Scenario", -- Requires localization
	SCHOLOMANCE = "스칼로맨스",
	SEARINGGORGE = "이글거리는 협곡",
	SEASONAL = "계절 축제", -- Needs review
	SERPENTSHRINECAVERN = "불뱀 제단",
	SETHEKKHALLS = "세데크 전당",
	SHADOPANMONASTERY = "음영파 수도원", -- Needs review
	SHADOWFANGKEEP = "그림자송곳니 성채",
	SHADOWLABYRINTH = "어둠의 미궁",
	SHADOWMOONBURIALGROUNDS = "어둠달 지하묘지",
	SHADOWMOONVALLEY = "어둠달 골짜기",
	SHAMAN = "주술사", -- Needs review
	SHATTRATHCITY = "샤트라스",
	SHIMMERINGEXPANSE = "흐린빛 벌판", -- Needs review
	SHOLAZARBASIN = "숄라자르 분지",
	SHOWMAPICONS = "지도 아이콘 표시", -- Needs review
	SIEGEOFNIUZAOTEMPLE = "니우짜오 사원 공성전투",
	SIEGEOFORGRIMMAR = "오그리마 공성전",
	SILITHUS = "실리더스", -- Needs review
	SILVERMOONCITY = "실버문",
	SILVERPINEFOREST = "은빛소나무 숲",
	SILVERSHARDMINES = "은빛수정 광산", -- Needs review
	SKETTIS = "Skettis", -- Requires localization
	SKINNING = "무두질", -- Needs review
	SKYREACH = "하늘탑",
	SORTALPHA = "정렬 : 가나다 순", -- Needs review
	SORTLEVEL = "정렬 : 레벨 순", -- Needs review
	SOUTHERNBARRENS = "남부 불모의 땅", -- Needs review
	SOUTHERNKALIMDOR = "Southern Kalimdor", -- Requires localization
	SPECIAL = "특수", -- Needs review
	SPECIALS = "특수", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	SPIRESOFARAK = "아라크 첨탑",
	STONETALONMOUNTAINS = "돌발톱 산맥", -- Needs review
	STORMSHIELD = "폭풍방패",
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STORMSTOUTBREWERY = "스톰스타우트 양조장",
	STORMWINDCITY = "스톰윈드",
	STRANDOFTHEANCIENTS = "고대의 해안",
	STRANGLETHORNVALE = "가시덤불 골짜기",
	STRATHOLME = "스트라솔름",
	SUNKENTEMPLE = "가라앉은 사원",
	SUNSTRIDERISLE = "선스트라이더 섬",
	SUNWELLPLATEAU = "태양샘 고원",
	SWAMPOFSORROWS = "슬픔의 늪",
	TAILORING = "재봉술", -- Needs review
	TALADOR = "탈라도르",
	TANAANJUNGLE = "타나안 밀림",
	TANARIS = "타나리스", -- Needs review
	TELDRASSIL = "텔드랏실", -- Needs review
	TEMPESTKEEP = "폭풍우 요새",
	TEMPLEOFAHNQIRAJ = "안퀴라즈 사원", -- Needs review
	TEMPLEOFKOTMOGU = "코트모구 사원",
	TEMPLEOFTHEJADESERPENT = "옥룡사",
	TEMPLEOFTHEREDCRANE = "주학사", -- Needs review
	TEROKKARFOREST = "테로카르 숲",
	THEARBORETUM = "The Arboretum", -- Requires localization
	THEARCATRAZ = "알카트라즈",
	THEBASTIONOFTWILIGHT = "황혼의 요새",
	THEBATTLEFORGILNEAS = "길니아스 전투지",
	THEBLACKMORASS = "검은늪",
	THEBLOODFURNACE = "피의 용광로",
	THEBOTANICA = "신록의 정원",
	THECAPEOFSTRANGLETHORN = "가시덤불 곶", -- Needs review
	THECULLINGOFSTRATHOLME = "옛 스트라솔름",
	THEDEADMINES = "죽음의 폐광",
	THEEVERBLOOM = "상록숲",
	THEEXODAR = "엑소다르", -- Needs review
	THEEYE = "폭풍우 눈", -- Needs review
	THEEYEOFETERNITY = "영원의 눈",
	THEFORGEOFSOULS = "영혼의 제련소",
	THEGATEOFTHESETTINGSUN = "The Gate of the Setting Sun", -- Requires localization
	THEHALFHILLMARKET = "언덕골 시장", -- Needs review
	THEHINTERLANDS = "동부 내륙지",
	THEJADEFOREST = "비취 숲",
	THELOSTISLES = "잃어버린 섬",
	THEMAELSTROM = "혼돈의 소용돌이",
	THEMECHANAR = "메카나르",
	THENEXUS = "마력의 탑",
	THEOBSIDIANSANCTUM = "흑요석 성소",
	THEOCULUS = "마력의 눈",
	THERUBYSANCTUM = "루비 성소",
	THESHATTEREDHALLS = "으스러진 손의 전당",
	THESLAVEPENS = "강제 노역소",
	THESTEAMVAULT = "증기 저장고",
	THESTOCKADE = "스톰윈드 지하감옥",
	THESTONECORE = "바위심장부",
	THESTORMPEAKS = "폭풍우 봉우리",
	THETEMPLEOFTHEJADESERPENT = "옥룡사", -- Needs review
	THEUNDERBOG = "지하수렁",
	THEVEILEDSTAIR = "장막의 계단", -- Needs review
	THEVIOLETHOLD = "보랏빛 요새",
	THEVORTEXPINNACLE = "소용돌이 누각",
	THEZANDALARI = "잔달라", -- Needs review
	THOUSANDNEEDLES = "버섯구름 봉우리", -- Needs review
	THRONEOFTHEFOURWINDS = "네 바람의 왕좌",
	THRONEOFTHETIDES = "파도의 왕좌",
	THRONEOFTHUNDER = "천둥의 왕좌",
	THUNDERBLUFF = "썬더 블러프", -- Needs review
	TIMELESSISLE = "영원의 섬",
	TIRISFALGLADES = "티리스팔 숲",
	TOLBARAD = "톨 바라드",
	TOLBARADPENINSULA = "톨 바라드 반도",
	TOURNAMENT = "토너먼트", -- Needs review
	TOWNLONGSTEPPES = "탕랑 평원",
	TRIALOFTHECHAMPION = "용사의 시험장",
	TRIALOFTHECRUSADER = "십자군의 시험장",
	TWILIGHTHIGHLANDS = "황혼의 고원",
	TWINPEAKS = "쌍둥이 봉우리",
	ULDAMAN = "울다만",
	ULDUAR = "울두아르",
	ULDUM = "울둠", -- Needs review
	UNDERCITY = "언더시티",
	UNGAINGOO = "웅가 잉구",
	UNGOROCRATER = "운고로 분화구", -- Needs review
	UPPERBLACKROCKSPIRE = "검은바위 첨탑 상층",
	UTGARDEKEEP = "우트가드 성채",
	UTGARDEPINNACLE = "우트가드 첨탑",
	VALEOFETERNALBLOSSOMS = "영원꽃 골짜기",
	VALLEYOFTHEFOURWINDS = "네 바람의 계곡",
	VASHJIR = "바쉬르",
	VAULTOFARCHAVON = "아카본 석실",
	WAILINGCAVERNS = "통곡의 동굴",
	WARLOCK = "흑마법사", -- Needs review
	WARRIOR = "전사", -- Needs review
	WARSONGGULCH = "전쟁노래 협곡",
	WARSPEAR = "전쟁의 창",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WELLOFETERNITY = "영원의 샘",
	WESTERNPLAGUELANDS = "서부 역병지대",
	WESTFALL = "서부 몰락지대",
	WETLANDS = "저습지",
	WINTERGRASP = "겨울손아귀 호수",
	WINTERSPRING = "여명의 설원", -- Needs review
	WINTERVEIL = "겨울마이 축제", -- Needs review
	WORLDEVENTS = "월드 이벤트", -- Needs review
	ZANGARMARSH = "장가르 습지대",
	ZULAMAN = "줄아만",
	ZULDRAK = "줄드락",
	ZULFARRAK = "줄파락",
	ZULGURUB = "줄구룹",
	THEBROKENISLES = "The Broken Isles",
	THEDREAMGROVE = "꿈숲",
	AZSUNA = "아즈스나",
	HIGHMOUNTAIN = "높은산",
	STORMHEIM = "스톰하임",
	SURAMAR = "수라마르",
	VALSHARAH = "발샤라",
	DEMONHUNTER = "악마사냥꾼",
	CONTESTCOMMING = "Contest comming shows wrong zone",
	HALLOFTHEGUARDIAN = "수호자의 전당",
	MARDUMTHESHATTEREDABYSS = "Mardum, the Shattered Abyss",
	NETHERLIGHTTEMPLE = "황천빛 사원",
	SKYHOLD = "하늘보루",
	THEHEARTOFAZERTH = "The Heart of Azeroth",
	THEWANDERINGISLE = "The Wandering Isle Monk",
	TRUESHOTLODGE = "Trueshot Lodge Hunter",
	ACHERUSTHEEBONHOLD = "아케루스: 칠흑의 요새",
	BLACKOOKHOLD = "검은 떼까마귀 요새",
	COURTOFSTARS = "별의 궁정",
	DARKHEARTTHICKET = "어둠심장 숲",
	EYEOFAZSHARA = "아즈샤라의 눈",
	HALLSOFVALOR = "용맹의 전당",
	MAWOFSOULS = "영혼의 아귀",
	NELTHARIONSLAIR = "넬타리온의 둥지",
	THEARCWAY = "비전로", 
	VAULTOFTHEWARDENS = "감시관의 금고",
	VIOLETHOLD = "보랏빛 요새",
	THEEMERALDNIGHTMARE = "에메랄드의 악몽",
	TRIALOFVALOR = "용맹의 시험",
	THENIGHTHOLD = "밤의 요새",
	BROKENSHORE = "부서진 해변",
	LEGIONUNCATEQUEST = "Legion Uncategorized Quests",
	CATHEDRALOFETERNALNIGHT = "영원한 밤의 대성당", 
	RETURNTOKARAZHAN = "다시 찾은 카라잔",
 	TOMBOFSARGERAS = "살게라스의 무덤",
	KROKUUN = "크로쿠운",
	ANTORANWASTES = "안토란 황무지",
	ARGUS = "Argus",
	MACAREE = "Mac'Aree",
	DREADSCARRIFT = "공포흉터 균열",
	ANTORUSTHEBURNINGTHRONE = "안토러스 - 불타는 왕좌",
	HELHEIM = "헬하임",
	THESEATOFTHETRIUMVIRATE = "삼두정의 권좌",
	EMERALDDREAMWAY = "Emerald Dreamway",
	BFA = "격전의 아제로스",
	BFAUNCATEQUEST = "BFA Uncategorized Quests",
	ZANDALAR = "Zandalar",
	KULTIRAS = "Kul Tiras",
	THUNDERTOTEM = "Thunder Totem",
	DRUSTVAR = "드러스트바",
	STORMSONGVALLEY = "스톰송 계곡",
	TIRAGARDESOUND = "티라가드 해협",
	NAZMIR = "나즈미르",
	VOLDUN = "볼둔",
	ZULDAZAR = "줄다자르",
	ATALDAZAR = "아탈다자르",	 	
	CRUCIBLEOFSTORMS = "폭풍의 용광로",	
	FREEHOLD = "자유지대",		
	KINGSREST = "왕들의 안식처",
	SHRINEOFTHESTORM = "폭풍의 사원",
	SIEGEOFBORAUS = "보랄러스 공성전",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	TEMPLEOFSETHRALISS = "세스랄리스 사원",
	THRUNDERROT = "The Underrot",
	TOLDAGOR = "톨 다고르",
	ULDIR = "울디르",
	WAYCRESTMANOR = "웨이크레스트 저택",
	THEDEATHOFCHROMIE = "The Deaths Of Chromie",
	THEMOTHERLOAD = "The Motherload!!",
	BATTLEOFDAZARALOR = "다자알로 전투",
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	CHAMBEROFHEART = "심장의 방",
	THEDRAGONSSPINE = "The Dragon`s Spine",
	MECHAGONISLAND = "Mechagon Island",
	NAZJATAR = "나즈자타",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	CLASSCAMPAINS = "Class Campains",
	TERRACEOFENLESSSPRINGS = "영원한 봄의 정원",
	TEMP = "Temp",
	PLAYERVSPLAYER = "Player Vs Player",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
	WORLDPVP = "World Pvp",
	THEETERNALPALACE = "영원한 궁전",
	NYALOTHATHEWALKINGCITY = "깨어난 도시 나이알로사",
	VISIONSOFNZOTH = "Visions of N'Zoth",
	BLACKEMPIRECAMPAIGN = "Black Empire Campaign",
	WORLDQUEST = "World Quests",
		-- Shadowlands Code
	-- Shadowlands Code
	SHADOWLANDS = "어둠땅",
	ARDENWEALD = "몽환숲",
	BASTION = "승천의 보루",
	EXILESREACH	= "추방자의 해안",
	MALDRAXXUS = "말드락서스",
	ORIBOSTHEETERNALCITY = "Oribos, the Eternal City",
	REVENDRETH = "레벤드레스",
	THEMAW = "나락",
	SHADOWLANDSUNCATEQUEST = "Shadowlands Uncategorized Quests",
	COVENANTCALLINGS = "Covenant Callings",
	KYRIAN = "Kyrian",
	NECROLORD = "Necrolord",
	NIGHTFAE = "Night Fae",
	VENTHYR = "Venthyr",
	MAINZONES = "Main Zones",
	OTHERCATEGORIES	= "Other Categories",
	NINEONECAMPAIGN = "9.1 Campaign",
	ABOMINABLESTICHING = "누더기 봉합술",
	COVENANTASSAULTS = "Covenant Assaults",
	COVENANTSANCTUARY = "Covenant Sanctuary",
	COVENANTSANCTUM = "Covenant Sanctum",
	EMBERCOURT = "Ember Court",
	KEEPERSRESPITE = "수호자의 안식처",
	KORTHIA = "코르시아",
	PATHOFASCENSION = "Path of Ascension",
	QUEENSCONSERVATORY = "여왕의 정원",
	TAZAVESH = "Tazavesh",
	THEARCHIVISTSCODEX = "The Archivists' Codex",
	TORGHASTTOWEROFTHEDAMNED = "저주받은 자의 탑 토르가스트",
	ZERETHMORTIS = "제레스 모르티스",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
	AZEROTHIANARCHIVES = "Azerothian Archives",
	AZMERLOTH = "Azmerloh",
	BRACKENHIDEWATERHOLE = "Brackenhide Waterhole",
	DRAGONISLE = "Dragon Isle",
	DRAGONFLIGHT = "용군단",
	DRAGONSCALEBASECAMP = "Dragonscale Basecamp",
	DRAGONSCALEEXPEDITION = "Dragonscale Expedition",
	DUNGEONS = "Dungeons",
	EMERALDARDENS = "Emerald Gardens",
	HORNSWOGHOLLOW = "Hornswog Hollow",
	ISKAARATUSKARR = "Iskaara Tuskarr",
	LOSTRUINS = "Lost Ruins",
	MARUUKCENTAUR = "Maruuk Centaur",
	OBSIDIANCITADEL = "흑요석 성채", 
	OHNAHRANPLAINS = "온아라 평야",
	PASSAGEOFTIME = "시간의 통로",
	PRIMALISTSTORMS = "Primalist Storms",
	PRIMORDIALALE = "Primordial Vale",
	RUBYLIFEPOOLS = "루비 생명의 웅덩이",
	RUBYLIFESHRINE = "Ruby Lifeshrine",
	SHADOWLEDGE = "Shadow Legde",
	TEMPESTUNLEASHED = "Tempest Unleashed",
	THALDRASZUS = "탈드라서스",
	THEAZURESPAN = "하늘빛 평원",
	THEFORBIDDENREACH = "금지된 해안",
	THEPRIMAISTFUTURE = "The Primalist Future",
	THEWALKINGSHORES = "깨어나는 해안",
	THERONSWATCH = "Theron`s Watch",
	VALDRAKKEN = "발드라켄",
	VALDRAKKENACCORD = "Valdrakken Accord",
	WHALLERSNOOK = "Whaler`s Nook",
	ZARALEKCAVERN = "자랄레크 동굴",
	EMERALDDREAM = "에메랄드의 꿈",
	KORRAKSREVENGE = "Korrak`s Revenge",
	--TWW
	TWW = "내부 전쟁",
	AWAKENINGTHEMACHINE = "기계의 각성",
	AZJKAHET = "아즈카헤트",
	CITYOFTHREADS = "실타래의 도시",	
	DEEPHAULRAVINE = "깊은광혈 협곡",	
	DHARBANDAR = "Dhar Bandar",	
	DORNOGAL = "도르노갈", --2339
	EARTHEN = "Earthen",
	HALLOWFALL = "신성한 협곡",
	ISLEOFDORN = "도른의 섬", --2248
	MOURNINGRISE = "Mourning Rise",
	NERUBARPALACE = "네룹아르 궁전",
	NORTHRENDCUP = "Northrend Cup",
	RAMBLESHIRE = "산책골",
	SIRENISLE = "세이렌의 섬",
	THERINGINGDEEPS = "울리는 심연",	
	UPGRADESYSTEM = "Upgrade System",
	WARBANDS = "Warbands",
	UNDERMINE = "언더마인",
	ARATHIHIGHLANDSTWW = "Arathi Highlands TWW",
	DELVESHEADQUARTERS = "구렁 탐험가 본부",
	DELVES = "Delves",
	THERAMORESFALLS = "Theramore`s  Fall",
	TIMERUNNING = "Timerunning",
	THEHARBINGER = "The Harbinger",
	GILNEASRECLAMATION = "Gilneas Reclamation",
	LITTLESCALESDAYCARE = "Little Scales Daycare",
	TIMERIFT = "Time Rift",
	AMIRDRASIL = "Amirdrasil",
	AMIRDRASILTHEDREAMSHOPE = "꿈의 희망 아미드랏실",
	THEOASIS = "오아시스",
	KARESH = "크아레쉬",
	--MID
	MIDNIGHT = "한밤",
	FOUNDERSPOINT = "개척자의 터전",
	HARANDAR = "하란다르",
	NEIGHBORHOOD = "Neighborhood",
	RAZORWINDSHORES = "칼끝바람 해안",
	SLAYERSRISE = "학살자의 오름길",
	STORMFILEDS = "Storm Fileds",
	VOIDSTORM = "공허폭풍",
	WESTSANCTUM = "서부 성소",	
	}

end