if GetLocale() == "esMX" then
qcLocalize = {
	AHNQIRAJTHEFALLENKINGDOM = "Ahn'Qiraj: El Reino Caído",
	ALCHEMY = "Alquimia", -- Needs review
	ARCHAEOLOGY = "Arqueología", -- Needs review
	ASSAULTONTHEDARKPORTAL = "Assault on the Dark Portal", -- Requires localization
	AZEROTH = "Azeroth",
	BARADINHOLD = "Bastión de Baradin", -- Needs review
	BATTLEGROUNDS = "Los Campos de Batalla", -- Needs review
	BATTLEPETS = "Mascotas de Duelo", -- Needs review
	BLACKSMITHING = "Herrería", -- Needs review
	BLACKWINGDESCENT = "Descenso de Alanegra", -- Needs review
	BLACKWINGLAIR = "Guarida de Alanegra", -- Needs review
	BRAWLERSGUILD = "Brawler's Guild", -- Requires localization
	BREWFEST = "Fiesta de la Cerveza", -- Needs review
	CAVERNSOFTIME = "Cavernas del Tiempo", -- Needs review
	CENTRALKALIMDOR = "Central Kalimdor", -- Requires localization
	CHILDRENSWEEK = "La Semana de los Niños", -- Needs review
	CLASSES = "Clases", -- Needs review
	CLASSQUESTS = "Misiones de clase", -- Needs review
	CLEARUPDATECACHE = "Limpiar la data del caché", -- Needs review
	COILFANGRESERVOIR = "Reserva Colmillo Torcido", -- Needs review
	COMBINEDMAPANDQUESTFILTERS = "Filtros combinados de mapas y listas de misiones", -- Needs review
	CONFIGSUBTITLE = "Estas opciones te permiten cambiar la manera en que Quest Completlist maneja y filtra la información", -- Needs review
	CONFIGTITLE = "Quest Completlist - Configuración", -- Needs review
	CONTINENTS = "Continentes", -- Needs review
	COOKING = "Cocina", -- Needs review
	DARKMOONFAIRE = "Feria de la Luna Negra", -- Needs review
	DAYOFTHEDEAD = "Festividad de los muertos ", -- Needs review
	DEATHKNIGHT = "Caballero de la Muerte", -- Needs review
	DRAENOR = "Draenor",
	DRAGONSOUL = "Alma de Dragón", -- Needs review
	DRUID = "Druida", -- Needs review
	DUNGEONSANDRAIDS = "Calabozos y bandas", -- Needs review
	EASTERNKINGDOMS = "Reinos del Este",
	ELEMENTALBONDS = "Vínclos elementales", -- Needs review
	ENCHANTING = "Encantamiento", -- Needs review
	ENGINEERING = "Ingeniería", -- Needs review
	FIRELANDS = "Tierras de Fuego", -- Needs review
	FIRELANDSINVASION = "Invasión de las Tierras de Fuego", -- Needs review
	FIRSTAID = "Primeros auxilios", -- Needs review
	FISHING = "Pesca", -- Needs review
	GARRISONCAMPAIGN = "Garrison Campaign", -- Requires localization
	GARRISONSUPPORT = "Garrison Support", -- Requires localization
	GREENSTONEVILLAGE = "Aldea Verdemar",
	GRUULSLAIR = "Guarida de Gruul", -- Needs review
	HALLOWSEND = "Halloween", -- Needs review
	HARVESTFESTIVAL = "Festival de la Cosecha", -- Needs review
	HELLFIRECITADEL = "Ciudadela del Fuego Infernal", -- Needs review
	HERBALISM = "Herboristería", -- Needs review
	HIDECOMPLETEDQUESTS = "Esconder misiones completadas", -- Needs review
	HIDEDAILYQUEST = "Hide Daily Quests",
	HIDEINPROGRESSQUESTS = "Esconder misiones en progreso", -- Needs review
	HIDELOWLEVELQUESTS = "Esconder misiones de bajo nivel", -- Needs review
	HIDENONACTIVESEASONALQUESTS = "Esconder misiones inactivas de festividades", -- Needs review
	HIDENORMALQUEST = "Hide Normal Quests",
	HIDEOTHERFACTIONQUESTS = "Esconder misiones de otras facciones", -- Needs review
	HIDEOTHERPROFESSIONQUESTS = "Esconder misiones de otras profesiones", -- Needs review
	HIDEOTHERRACEANDCLASSQUESTS = "Esconder misiones de otras razas y clases", -- Needs review
	HIDEOTHERCOVENANTQUESTS = "Hide Other Covenant Quests",
	HIDEWARBANDS = "Hide quests done by other warband's characters",
	HIDEREQUIREMENTSNOTMET = "Hide quests with unfinished requirements",
	HIDENODATA = "Hide pins with no quest data available",
	HIDEREPEATABLEQUEST = "Hide Repeatable Quests",
	HIDEWEEKLYQUEST = "Hide Weekly Quests",
	HIDEWORLDQUEST = "Hide World Quests",
	HUNTER = "Cazador", -- Needs review
	ICECROWNCITADEL = [=[Ciudadela de la Corona de Hielo
]=], -- Needs review
	INSCRIPTION = "Inscripción", -- Needs review
	ISLEOFGIANTS = "Isla de los Gigantes",
	JADETEMPLEGROUNDS = "Jade Temple Grounds", -- Requires localization
	JEWELCRAFTING = "Joyería", -- Needs review
	KALIMDOR = "Kalimdor",
	KHAZMODAN = "Khaz Modan", -- Requires localization
	LANDFALL = "Landfall", -- Requires localization
	LEATHERWORKING = "Peletería", -- Needs review
	LEGENDARY = "Legendario", -- Needs review
	LORDAERON = "Lordaeron", -- Requires localization
	LOVEISINTHEAIR = "Amor en el Aire", -- Needs review
	LUNARFESTIVAL = "Festival Lunar", -- Needs review
	MAGE = "Mago", -- Needs review
	MAPFILTERS = "Filtros de mapas", -- Needs review
	MIDSUMMERFIREFESTIVAL = "Festival de Fuego del Solsticio de Verano", -- Needs review
	MINING = "Minería", -- Needs review
	MISCELLANEOUS = "Miscelaneo", -- Needs review
	MOGUSHANVAULTS = "Cámaras Mogu'shan", -- Needs review
	MONK = "Monje", -- Needs review
	NAGRAND = "Nagrand", -- Needs review
	NEWYEARSEVE = "Víspera de Año Nuevo", -- Needs review
	NOBLEGARDEN = "Jardín Noble", -- Needs review
	NORTHERNKALIMDOR = "Northern Kalimdor", -- Requires localization
	NORTHREND = "Rasganorte", -- Needs review
	ONYXIASLAIR = "Guarida de Onyxia", -- Needs review
	OPTIONS = "Opciones", -- Needs review
	OUTLAND = "Terrallende", -- Needs review
	PALACEOFTHEHEAVENS = "Palacio de los Cielos", -- Needs review
	PALADIN = "Paladín", -- Needs review
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Pandaren Campaign", -- Requires localization
	PANDARIA = "Pandaria", -- Needs review
	PEAKOFSERENITY = "Peak of Serenity", -- Requires localization
	PERFORMSERVERQUERY = "Hacer una búsqueda en el servidor", -- Needs review
	PILGRIMSBOUNTY = "Generosidad del Peregrino", -- Needs review
	PRIEST = "Sacerdote", -- Needs review
	PROFESSIONS = "Profesiones", -- Needs review
	QUERYREQUESTED = "Se ha solicitado una búsqueda en el servidor...", -- Needs review
	QUESTLISTFILTERS = "Filtros de lista de misiones", -- Needs review
	QUESTSFOUND = "Misión encontrada", -- Needs review
	RAIDS = "Bandas", -- Needs review
	REGIONS = "Regions", -- Requires localization
	RIDING = "Riding", -- Requires localization
	ROGUE = "Pícaro", -- Needs review
	RUINSOFGILNEASCITY = "Ruinas de la Ciudad de Gilneas", -- Needs review
	SCENARIO = "Scenario", -- Requires localization
	SEASONAL = "Estacional", -- Needs review
	SERPENTSHRINECAVERN = "Caverna Santuario Serpiente", -- Needs review
	SHADOWMOONVALLEY = "Valle Sombraluna", -- Needs review
	SHAMAN = "Chamán", -- Needs review
	SHOWMAPICONS = "Mostrar iconos en el mapa", -- Needs review
	SKETTIS = "Skettis", -- Requires localization
	SKINNING = "Desuello", -- Needs review
	SORTALPHA = "Ordenar: Alfabéticamente", -- Needs review
	SORTLEVEL = "Ordenar: Por nivel", -- Needs review
	SOUTHERNKALIMDOR = "Southern Kalimdor", -- Requires localization
	SPECIAL = "Especial", -- Needs review
	SPECIALS = "Especiales", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "Vega de Tuercespina", -- Needs review
	SUNKENTEMPLE = "Templo Sumergido", -- Needs review
	TAILORING = "Sastrería", -- Needs review
	TEMPLEOFTHEREDCRANE = "Templo de la Grulla Roja", -- Needs review
	THEARBORETUM = "The Arboretum", -- Requires localization
	THEBASTIONOFTWILIGHT = "El Bastión del Crepúsculo", -- Needs review
	THEBLACKMORASS = "La Ciénaga Negra", -- Needs review
	THEEVERBLOOM = "El Sempibrote",
	THEEYE = "El Ojo", -- Needs review
	THEGATEOFTHESETTINGSUN = "Puerta del Sol Poniente", -- Needs review
	THEHALFHILLMARKET = "El Mercado del Alcor", -- Needs review
	THEMAELSTROM = "La Vorágine", -- Needs review
	THEOBSIDIANSANCTUM = "El Sagrario Obsidiana", -- Needs review
	THETEMPLEOFTHEJADESERPENT = "El Templo de la Serpiente de Jade", -- Needs review
	THEVIOLETHOLD = "El Bastión Violeta", -- Needs review
	THEZANDALARI = "Los Zandalari", -- Needs review
	THRONEOFTHEFOURWINDS = "Trono de los Cuatro Vientos", -- Needs review
	TOURNAMENT = "Torneo", -- Needs review
	UPPERBLACKROCKSPIRE = "Cumbre de Roca Negra superior",
	UNCATEGORIZED = "Sin categoría", -- Needs review
	VASHJIR = "Vashj'ir", -- Needs review
	VAULTOFARCHAVON = "La Cámara de Archavon", -- Needs review
	WARLOCK = "Brujo", -- Needs review
	WARRIOR = "Guerrero", -- Needs review
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "Eventos semanales", -- Needs review
	WINTERVEIL = "El festín del Festival de Invierno", -- Needs review
	WORLDEVENTS = "Eventos del Mundo", -- Needs review
	THEBROKENISLES = "The Broken Isles",
	THEDREAMGROVE = "La Arboleda de los Sueños",
	DEMONHUNTER = "Cazador de demonios",
	CONTESTCOMMING = "Contest comming shows wrong zone",
	HALLOFTHEGUARDIAN = "Salón del Guardián",
	MARDUMTHESHATTEREDABYSS = "Mardum, the Shattered Abyss",
	NETHERLIGHTTEMPLE = "Templo Luz Abisal",
	SKYHOLD = "Bastión del Cielo",
	THEHEARTOFAZERTH = "The Heart of Azeroth",
	THEWANDERINGISLE = "The Wandering Isle Monk",
	TRUESHOTLODGE = "Trueshot Lodge Hunter",
	MAWOFSOULS = "Fauces de almas",
	LEGIONUNCATEQUEST = "Legion Uncategorized Quests",
	RETURNTOKARAZHAN = "Regreso a Karazhan",
	MACAREE = "Mac'Aree",
	DREADSCARRIFT = "Falla Cicatriz Aterradora",
	HELHEIM = "Helheim",
	EMERALDDREAMWAY = "Emerald Dreamway",
	BFA = "Battle For Azeroth",
	BFAUNCATEQUEST = "BFA Uncategorized Quests",
	ZANDALAR = "Zandalar",
	KULTIRAS = "Kul Tiras",
	THUNDERTOTEM = "Thunder Totem",
	KINGSREST = "Reposo de los Reyes",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	THRUNDERROT = "The Underrot",
	THEDEATHOFCHROMIE = "The Deaths Of Chromie",
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	THEDRAGONSSPINE = "The Dragon`s Spine",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	TERRACEOFENLESSSPRINGS = "Veranda de la Primavera Eterna",
	PLAYERVSPLAYER = "Player Vs Player",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
	WORLDPVP = "World Pvp",
	NYALOTHATHEWALKINGCITY = "Ny'alotha, la Ciudad Despierta",
	VISIONSOFNZOTH = "Visions of N'Zoth",
	BLACKEMPIRECAMPAIGN = "Black Empire Campaign",
	WORLDQUEST = "World Quests",
	-- Shadowlands Code
	SHADOWLANDS = "Shadowlands",
	SHADOWLANDSUNCATEQUEST = "Shadowlands Uncategorized Quests",
	COVENANTCALLINGS = "Covenant Callings",
	KYRIAN = "Kyrian",
	NECROLORD = "Necrolord",
	NIGHTFAE = "Night Fae",
	VENTHYR = "Venthyr",
	MAINZONES = "Main Zones",
	OTHERCATEGORIES	= "Other Categories",
	NINEONECAMPAIGN = "9.1 Campaign",
	ABOMINABLESTICHING = "Costura abominable",
	COVENANTASSAULTS = "Covenant Assaults",
	COVENANTSANCTUARY = "Covenant Sanctuary",
	COVENANTSANCTUM = "Covenant Sanctum",
	EMBERCOURT = "Ember Court",
	KEEPERSRESPITE = "Descanso del Vigilante",
	PATHOFASCENSION = "Path of Ascension",
	TAZAVESH = "Tazavesh",
	THEARCHIVISTSCODEX = "The Archivists' Codex",
	TORGHASTTOWEROFTHEDAMNED = "Torghast, la Torre de los Condenados",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
	AZEROTHIANARCHIVES = "Azerothian Archives",
	AZMERLOTH = "Azmerloh",
	BRACKENHIDEWATERHOLE = "Brackenhide Waterhole",
	DRAGONISLE = "Dragon Isle",
	DRAGONFLIGHT = "Dragonflight",
	DRAGONSCALEBASECAMP = "Dragonscale Basecamp",
	DRAGONSCALEEXPEDITION = "Dragonscale Expedition",
	DUNGEONS = "Dungeons",
	EMERALDARDENS = "Emerald Gardens",
	HORNSWOGHOLLOW = "Hornswog Hollow",
	ISKAARATUSKARR = "Iskaara Tuskarr",
	LOSTRUINS = "Lost Ruins",
	MARUUKCENTAUR = "Maruuk Centaur",
	OBSIDIANCITADEL = "Ciudadela Obsidiana", 
	PASSAGEOFTIME = "Paso del Tiempo",
	PRIMALISTSTORMS = "Primalist Storms",
	PRIMORDIALALE = "Primordial Vale",
	RUBYLIFEPOOLS = "Estanques de Vida Rubí",
	RUBYLIFESHRINE = "Ruby Lifeshrine",
	SHADOWLEDGE = "Shadow Legde",
	TEMPESTUNLEASHED = "Tempest Unleashed",
	THEPRIMAISTFUTURE = "The Primalist Future",
	THERONSWATCH = "Theron`s Watch",
	VALDRAKKENACCORD = "Valdrakken Accord",
	KORRAKSREVENGE = "Korrak`s Revenge",
	--TWW
	TWW = "The War Within",
	AWAKENINGTHEMACHINE = "Despertar de la Máquina",
	DEEPHAULRAVINE = "Barranco de Infrabundancia",	
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NERUBARPALACE = "Palacio Nerub-ar",
	NORTHRENDCUP = "Northrend Cup",
	RAMBLESHIRE = "Comarca de los Carneros",
	UPGRADESYSTEM = "Upgrade System",
	WARBANDS = "Warbands",
	ARATHIHIGHLANDSTWW = "Arathi Highlands TWW",
	DELVESHEADQUARTERS = "Cuartel de Surcabismos",
	DELVES = "Delves",
	THERAMORESFALLS = "Theramore`s  Fall",
	TIMERUNNING = "Timerunning",
	THEHARBINGER = "The Harbinger",
	GILNEASRECLAMATION = "Gilneas Reclamation",
	LITTLESCALESDAYCARE = "Little Scales Daycare",
	TIMERIFT = "Time Rift",
	AMIRDRASIL = "Amirdrasil",
	AMIRDRASSILTHEDREAMSHOPE = "Amirdrassil, la Esperanza del Sueño",
	THEOASIS = "El Oasis",
	--MID
	MIDNIGHT = "Midnight",
	FOUNDERSPOINT = "Punto del Fundador",
	NEIGHBORHOOD = "Neighborhood",
	RAZORWINDSHORES = "Costas del Ventajo",
	SLAYERSRISE = "Alto del Asesino",
	WESTSANCTUM = "Sagrario del Oeste",	
	DEADMINES = "Minas de la Muerte",
	LOWERBLACKROCKSPIRE = "Cumbre de Roca Negra inferior",
	THETEMPLEOFATALHAKKAR = "El Templo de Atal'Hakkar",
	THEBATTLEFORMOUNTHYJAL = "La Batalla del Monte Hyjal",
	SEATOFTHETRIUMVIRATE = "Trono del Triunvirato",
	TAZAVESHTHEVEILEDMARKET = "Tazavesh, el Mercado Velado",
	ASSAULTONVIOLETHOLD = "Ataque al Bastión Violeta",
	DIREMAULCAPITALGARDENS = "La Masacre - Jardines de la Capital",
	STRATHOLMEMAINGATE = "Stratholme - Entrada Principal",
	TEMPLEOFAHNQIRAJ = "Templo de Ahn'Qiraj",
	DIREMAULWARPWOODQUARTER = "La Masacre - Barrio Alabeo",
	DIREMAULGORDOKCOMMONS = "La Masacre - Ágora de Gordok",
	STRATHOLMESERVICEENTRANCE = "Stratholme - Entrada de Servicio",
	WINDRUNNERSPIRE = "Aguja Brisaveloz",
	MAGISTERSTERRACE = "Bancal del Magister",
	MURDERROW = "El Frontal de la Muerte",
	THEVOIDSPIRE = "La Aguja del Vacío",
	THEBLINDINGVALE = "El Valle Enceguecedor",
	DENOFNALORAKK = "Guarida de Nalorakk",
	VOIDSCARARENA = "Arena Rajavacío",
	THEDREAMRIFT = "La Onirifalla",
	MAISARACAVERNS = "Cavernas de Maisara",
	NEXUSPOINTXENAS = "Punto del Nexo Xenas",
	}
end