if GetLocale() == "deDE" then
qcLocalize = setmetatable({
	AHNQIRAJWAR = "Krieg von Ahn'Qiraj",
	ASSAULTONTHEDARKPORTAL = "Angriff auf das Dunkle Portal",
	CAMPING = "Lager aufschlagen",
	CENTRALKALIMDOR = "Zentral Kalimdor",
	CLASSES = "Klassen",
	CLASSQUESTS = "Klassenquests",
	CLEARUPDATECACHE = "Lösche und aktualisiere Cache...",
	CONFIGSUBTITLE = "Diese Option erlaubt dir die Art und Weise zu ändern, wie Quest Completist seine Daten verwendet und filtert.",
	CONFIGTITLE = "Quest Completist - Konfiguration",
	CONTINENTS = "Kontinente",
	DAYOFTHEDEAD = "Tag der Toten",
	DEATHRISING = "Die Flut des Todes",
	ELEMENTALBONDS = "Elementare Bande",
	FIRELANDSINVASION = "Einmarsch in die Feuerlande",
	GARRISONCAMPAIGN = "Garnisonskampagne",
	GARRISONSUPPORT = "Unterstützung der Garnison",
	HIDECOMPLETEDQUESTS = "Verstecke abgeschlossene Quests",
	HIDEDAILYQUEST = "Verstecke Tägliche Quests",
	HIDEINPROGRESSQUESTS = "Verstecke laufende Quests",
	HIDELOWLEVELQUESTS = "Verstecke niedrigstufige Quests",
	HIDENONACTIVESEASONALQUESTS = "Verstecke nicht aktive saisonale Quests",
	HIDEOTHERFACTIONQUESTS = "Verstecke Quests der anderen Fraktion",
	HIDEOTHERPROFESSIONQUESTS = "Verstecke Quests anderer Berufe",
	HIDEOTHERRACEANDCLASSQUESTS = "Verstecke Quests anderer Rassen und Klassen",
	HIDEOTHERCOVENANTQUESTS = "Verstecke Quests anderer Covenant",
	HIDEWARBANDS = "Verstecke Quests, die andere Charaktere deiner Kriegsmeute erledigt haben", -- Needs review
	HIDEUNAVAILABLE = "Verstecke Quests, die nicht mehr verfügbar sind", -- Needs review
	HIDEREQUIREMENTSNOTMET = "Verstecke Quests mit unerfüllten Voraussetzungen", -- Needs review
	HIDENODATA = "Verstecke Markierungen ohne Questdaten", -- Needs review
	HIDEREPEATABLEQUEST = "Verstecke wiederholbare Quests", -- Needs review
	HIDEWORLDQUEST = "Verstecke Welt- und Wochenquests", -- Needs review
	INVASION = "Invasion der Geißel",
	KHAZMODAN = "Khaz Modan",
	LANDFALL = "Landung",
	LORDAERON = "Lordaeron",
	LUNARFESTIVAL = "Mondfest",
	MIDSUMMER = "Sonnenwendfest",
	NORTHERNKALIMDOR = "Nördliches Kalimdor",
	PANDARENBREWMASTERS = "Pandarische Braumeister",
	PANDARENCAMPAIGN = "Pandarenkampagne",
	PERFORMSERVERQUERY = "Server-Abfrage durchführen...",
	QUERYREQUESTED = "Eine Serverabfrage wird durchgeführt...",
	QUESTLIST = "Questliste", -- Needs review
	QUESTSFOUND = "%d gefundene Quests",
	SEASONAL = "Saisonbedingt",
	SHOWMAPICONS = "Zeige Kartensymbole",
	SKETTIS = "Skettis", -- Requires localization
	SORTALPHA = "Sortierung: Alphabetisch",
	SORTLEVEL = "Sortierung: Stufe",
	SOUTHERNKALIMDOR = "Südliches Kalimdor",
	SPECIALS = "Spezielles", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "Schlingendorntal",
	THEZANDALARI = "Die Zandalari",
	TOURNAMENT = "Turnier",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "Wöchentliche Events", -- Needs review
	WORLDEVENTS = "Weltereignisse",
	MACAREE = "Mac'Aree",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	ALLIANCEWARCAMPAIGN = "Kriegskampagne der Allianz",
	HORDEWARCAMPAIGN = "Kriegskampagne der Horde",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	HERITAGE = "Tradition",
	RATEDPVP = "Gewertetes PvP",
	WORLDPVP = "Welt-PvP",
	BLACKEMPIRECAMPAIGN = "Kampagne gegen das Schwarze Imperium",
	-- Shadowlands Code
	MAINZONES = "Hauptzonen", -- Needs review
	OTHERCATEGORIES = "Weitere Kategorien", -- Needs review
	COVENANTASSAULTS = "Paktangriffe",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
		--TWW
	--TWW
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NORTHRENDCUP = "Nordendpokal",
	UPGRADESYSTEM = "Aufwertungssystem",
	WARBANDS = "Kriegsmeuten",
	TIMERUNNING = "Zeitläufer",
	THEHARBINGER = "Die Vorbotin",
	GILNEASRECLAMATION = "Rückeroberung von Gilneas",
	TIMERIFT = "Time Rift",
	--MID
	NEIGHBORHOOD = "Neighborhood",
	PROGRESS = "%d/%d abgeschlossen (%d%%)", -- Needs review
	SERVERQUERYRESULT = "Der Server meldet %d abgeschlossene Quests, die Quest Completist kennt, davon %d neu als abgeschlossen markiert.", -- Needs review
	CACHECLEARED = "Cache geleert.", -- Needs review
	CLEARINGCACHE = "Dein Update-Cache wird geleert...", -- Needs review
	NODETAILS = "Das Spiel liefert keine Questdetails", -- Needs review
	QUESTID = "Quest-ID:", -- Needs review
	STORYLINEPOSITION = "(%d von %d)", -- Needs review
	CAMPAIGNCHAPTER = "(Kapitel %d von %d)", -- Needs review
	EARLIERQUESTS = "... %d frühere", -- Needs review
	LATERQUESTS = "... %d weitere", -- Needs review
	THISQUEST = "diese Quest", -- Needs review
	REQUIREDQUEST = "Benötigte Quest:", -- Needs review
	REQUIREDFACTION = "Benötigte Fraktion:", -- Needs review
	REQUIREDRENOWN = "Benötigte Ruhmstufe:", -- Needs review
	REQUIREDRANK = "Benötigter Rang:", -- Needs review
	REQUIREDSKILL = "Benötigte Fertigkeit:", -- Needs review
	RANKLEVEL = "Rang %d", -- Needs review
	QUESTGIVER = "Questgeber:", -- Needs review
	NOQUESTGIVER = "Unbekannt, oder automatisch angenommene Quest", -- Needs review
	REPAMOUNT = "%d Ruf", -- Needs review
	NEWDATAINTRO = "Quest Completist kannte die folgenden Informationen noch nicht. Bitte hilf, das Addon genauer zu machen, indem du sie auf CurseForge meldest.", -- Needs review
	NEWDATAQUEST = " - Die Quest fehlt in der Datenbank.", -- Needs review
	NEWDATAFACTION = " - QC wusste nicht, dass deine FRAKTION diese Quest abschließen kann.", -- Needs review
	NEWDATARACE = " - QC wusste nicht, dass deine RASSE diese Quest abschließen kann.", -- Needs review
	NEWDATACLASS = " - QC wusste nicht, dass deine KLASSE diese Quest abschließen kann.", -- Needs review
	NEWDATAALERT = "Neue Daten gefunden - bitte melden!", -- Needs review
	BREADCRUMBAVAILABLE = "1 Brotkrumen-Quest verfügbar!", -- Needs review
	BREADCRUMBSAVAILABLE = "%d Brotkrumen-Quests verfügbar!", -- Needs review
	BREADCRUMBQUESTS = "Brotkrumen-Quests", -- Needs review
	MUTUALLYEXCLUSIVE = "Diese Quest schließt andere aus: Du kannst nur eine davon abschließen. Die anderen Quests sind:", -- Needs review
	NOTINDATABASE = "Quest nicht in der Datenbank", -- Needs review
	YOURSELF = "<Du selbst>", -- Needs review
	OTHERQUESTS = "Weitere Quests", -- Needs review
	PINDONE = "%d erledigt", -- Needs review
	PINSHOWDONE = "Umschalt zum Anzeigen", -- Needs review
	PINWAYPOINT = "Klicken, um einen TomTom-Wegpunkt zu setzen", -- Needs review
	WELCOME = "Danke, dass du Quest Completist nutzt. Ist dir ein Fehler bei einer Quest aufgefallen? Bitte melde ihn auf CurseForge.", -- Needs review
	UNAVAILABLEACCEPTED = "Quest %d \"%s\" ist als nicht mehr verfügbar eingetragen, aber du hast sie gerade angenommen. Bei dir wird sie normal angezeigt; bitte melde es, damit die Liste korrigiert werden kann.", -- Needs review
	UNAVAILABLETURNEDIN = "Quest %d \"%s\" ist als nicht mehr verfügbar eingetragen, aber du hast sie gerade abgegeben. Bei dir wird sie normal angezeigt; bitte melde es, damit die Liste korrigiert werden kann.", -- Needs review
	TOGGLEFRAME = "Fenster ein-/ausblenden", -- Needs review
	SHOWMINIMAPBUTTON = "Minikartensymbol anzeigen", -- Needs review
	MINIMAPLEFTCLICK = "Linksklick: Questliste ein-/ausblenden", -- Needs review
	MINIMAPRIGHTCLICK = "Rechtsklick: Optionen öffnen", -- Needs review
	MINIMAPDRAG = "Ziehen: Symbol um die Minikarte bewegen", -- Needs review
	}, {__index = qcLocalize})

end