if GetLocale() == "itIT" then
qcLocalize = {
	AHNQIRAJTHEFALLENKINGDOM = "Ahn'Qiraj: Il Regno Perduto", -- Needs review
	ALCHEMY = "Alchimia", -- Needs review
	ARCHAEOLOGY = "Archeologia", -- Needs review
	ASSAULTONTHEDARKPORTAL = "Assault on the Dark Portal", -- Requires localization
	AZEROTH = "Azeroth",
	BARADINHOLD = "Forte di Baradin",
	BATTLEGROUNDS = "Campo di Battaglia", -- Needs review
	BATTLEPETS = "Battle Pets", -- Requires localization
	BLACKSMITHING = "Forgiatura", -- Needs review
	BLACKWINGDESCENT = "Sotterranei dell'Ala Nera",
	BLACKWINGLAIR = "Fortezza dell'Ala Nera",
	BRAWLERSGUILD = "Brawler's Guild", -- Requires localization
	BREWFEST = "Brewfest", -- Requires localization
	CAVERNSOFTIME = "Caverne del Tempo",
	CENTRALKALIMDOR = "Central Kalimdor", -- Requires localization
	CHILDRENSWEEK = "Children's Week", -- Requires localization
	CLASSES = "Classes", -- Requires localization
	CLASSQUESTS = "Class Quests", -- Requires localization
	CLEARUPDATECACHE = "Clear Update Cache...", -- Requires localization
	COILFANGRESERVOIR = "Coilfang Reservoir", -- Requires localization
	COMBINEDMAPANDQUESTFILTERS = "Combined Map & Quest List Filters", -- Requires localization
	CONFIGSUBTITLE = "These options allow you to change the way that Quest Completist handles and filters its data.", -- Requires localization
	CONFIGTITLE = "Quest Completist - Configuration", -- Requires localization
	CONTINENTS = "Continents", -- Requires localization
	COOKING = "Cucina",
	DARKMOONFAIRE = "Darkmoon Faire", -- Requires localization
	DAYOFTHEDEAD = "Day of the Dead", -- Requires localization
	DEATHKNIGHT = "Cavaliere della Morte",
	DRAENOR = "Draenor",
	DRAGONSOUL = "Anima del Drago",
	DRUID = "Druido",
	DUNGEONSANDRAIDS = "Dungeons & Raids", -- Requires localization
	EASTERNKINGDOMS = "Regni Orientali", -- Needs review
	ELEMENTALBONDS = "Elemental Bonds", -- Requires localization
	ENCHANTING = "Incantamento",
	ENGINEERING = "Ingegneria",
	FIRELANDS = "Terre del Fuoco",
	FIRELANDSINVASION = "Firelands Invasion", -- Requires localization
	FIRSTAID = "First Aid", -- Requires localization
	FISHING = "Pesca",
	GARRISONCAMPAIGN = "Garrison Campaign", -- Requires localization
	GARRISONSUPPORT = "Garrison Support", -- Requires localization
	GREENSTONEVILLAGE = "Pietraverde",
	GRUULSLAIR = "Antro di Gruul",
	HALLOWSEND = "Hallow's End", -- Requires localization
	HARVESTFESTIVAL = "Harvest Festival", -- Requires localization
	HELLFIRECITADEL = "Cittadella del Fuoco Infernale",
	HERBALISM = "Erbalismo",
	HIDECOMPLETEDQUESTS = "Hide Completed Quests", -- Requires localization
	HIDEDAILYQUEST = "Hide Daily Quests",
	HIDEINPROGRESSQUESTS = "Hide In-Progress Quests", -- Requires localization
	HIDELOWLEVELQUESTS = "Hide Low Level Quests", -- Requires localization
	HIDENONACTIVESEASONALQUESTS = "Hide Non-Active Seasonal Quests", -- Requires localization
	HIDENORMALQUEST = "Hide Normal Quests",
	HIDEOTHERFACTIONQUESTS = "Hide Other Faction Quests", -- Requires localization
	HIDEOTHERPROFESSIONQUESTS = "Hide Other Profession Quests", -- Requires localization
	HIDEOTHERRACEANDCLASSQUESTS = "Hide Other Race & Class Quests", -- Requires localization
	HIDEOTHERCOVENANTQUESTS = "Hide Other Covenant Quests",
	HIDEWARBANDS = "Hide quests done by other warband's characters",
	HIDEREQUIREMENTSNOTMET = "Hide quests with unfinished requirements",
	HIDENODATA = "Hide pins with no quest data available",
	HIDEREPEATABLEQUEST = "Hide Repeatable Quests",
	HIDEWEEKLYQUEST = "Hide Weekly Quests",
	HIDEWORLDQUEST = "Hide World Quests",
	HUNTER = "Cacciatore",
	INSCRIPTION = "Runografia",
	ISLEOFGIANTS = "Isola dei Giganti",
	JADETEMPLEGROUNDS = "Jade Temple Grounds", -- Requires localization
	JEWELCRAFTING = "Oreficeria",
	KALIMDOR = "Kalimdor", -- Needs review
	KHAZMODAN = "Khaz Modan", -- Requires localization
	LANDFALL = "Landfall", -- Requires localization
	LEATHERWORKING = "Conciatura",
	LEGENDARY = "Legendary", -- Requires localization
	LORDAERON = "Lordaeron", -- Requires localization
	LOVEISINTHEAIR = "Love is in the Air", -- Requires localization
	LUNARFESTIVAL = "Lunar Festival", -- Requires localization
	MAGE = "Mago",
	MAPFILTERS = "Map Filters", -- Requires localization
	MIDSUMMERFIREFESTIVAL = "Midsummer Fire Festival", -- Requires localization
	MINING = "Estrazione",
	MISCELLANEOUS = "Varie", -- Needs review
	MOGUSHANVAULTS = "Segrete Mogu'shan",
	MONK = "Monaco",
	NAGRAND = "Nagrand", -- Needs review
	NEWYEARSEVE = "New Year's Eve", -- Requires localization
	NOBLEGARDEN = "Noblegarden", -- Requires localization
	NORTHERNKALIMDOR = "Northern Kalimdor", -- Requires localization
	NORTHREND = "Nordania", -- Needs review
	ONYXIASLAIR = "Antro di Onyxia",
	OPTIONS = "Options", -- Requires localization
	OUTLAND = "Terre Esterne", -- Needs review
	PALACEOFTHEHEAVENS = "Palace of the Heavens", -- Requires localization
	PALADIN = "Paladino",
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Pandaren Campaign", -- Requires localization
	PANDARIA = "Pandaria", -- Needs review
	PEAKOFSERENITY = "Peak of Serenity", -- Requires localization
	PERFORMSERVERQUERY = "Perform Server Query...", -- Requires localization
	PILGRIMSBOUNTY = "Pilgrim's Bounty", -- Requires localization
	PRIEST = "Sacerdote",
	PROFESSIONS = "Professions", -- Requires localization
	QUERYREQUESTED = "Un'interrogazione al server è stata richiesta", -- Needs review
	QUESTLISTFILTERS = "Quest List Filters", -- Requires localization
	QUESTSFOUND = "%d Quests Found", -- Requires localization
	RAIDS = "Raids", -- Requires localization
	REGIONS = "Regions", -- Requires localization
	RIDING = "Riding", -- Requires localization
	ROGUE = "Ladro",
	RUINSOFGILNEASCITY = "Rovine della città di Gilneas", -- Needs review
	SCENARIO = "Scenario", -- Requires localization
	SEASONAL = "Seasonal", -- Requires localization
	SERPENTSHRINECAVERN = "Caverna di Sacrespire",
	SHADOWMOONVALLEY = "Valle di Torvaluna", -- Needs review
	SHAMAN = "Sciamano",
	SHOWMAPICONS = "Show Map Icons", -- Requires localization
	SKETTIS = "Skettis", -- Requires localization
	SKINNING = "Scuoiatura",
	SORTALPHA = "Sort: Alphabetically", -- Requires localization
	SORTLEVEL = "Sort: Level", -- Requires localization
	SOUTHERNKALIMDOR = "Southern Kalimdor", -- Requires localization
	SPECIAL = "Special", -- Requires localization
	SPECIALS = "Specials", -- Requires localization
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "Valle di Rovotorto", -- Needs review
	SUNKENTEMPLE = "Sunken Temple", -- Requires localization
	TAILORING = "Sartoria",
	TEMPLEOFTHEREDCRANE = "Temple of the Red Crane", -- Requires localization
	THEARBORETUM = "The Arboretum", -- Requires localization
	THEBASTIONOFTWILIGHT = "Bastione del Crepuscolo",
	THEBLACKMORASS = "Palude Nera",
	THEEVERBLOOM = "Verdeterno",
	THEEYE = "Occhio della Tempesta",
	THEGATEOFTHESETTINGSUN = "The Gate of the Setting Sun", -- Requires localization
	THEHALFHILLMARKET = "The Halfhill Market", -- Requires localization
	THEMAELSTROM = "Maelstrom", -- Needs review
	THEOBSIDIANSANCTUM = "Santuario di Ossidiana",
	THETEMPLEOFTHEJADESERPENT = "The Temple of the Jade Serpent", -- Requires localization
	THEVIOLETHOLD = "Fortezza Violacea",
	THEZANDALARI = "The Zandalari", -- Requires localization
	THRONEOFTHEFOURWINDS = "Trono dei Quattro Venti",
	TOURNAMENT = "Tournament", -- Requires localization
	UPPERBLACKROCKSPIRE = "Bastioni di Roccianera Superiori",
	VASHJIR = "Vashj'ir", -- Needs review
	VAULTOFARCHAVON = "Volta di Archavon",
	WARLOCK = "Stregone",
	WARRIOR = "Guerriero",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WINTERVEIL = "Winter Veil", -- Requires localization
	WORLDEVENTS = "World Events", -- Requires localization
	THEBROKENISLES = "The Broken Isles",
	THEDREAMGROVE = "Bosco dei Sogni",
	DEMONHUNTER = "Cacciatore di Demoni",
	CONTESTCOMMING = "Contest comming shows wrong zone",
	HALLOFTHEGUARDIAN = "Sale dei Guardiani",
	MARDUMTHESHATTEREDABYSS = "Mardum, the Shattered Abyss",
	NETHERLIGHTTEMPLE = "Tempio di Lucefatua",
	SKYHOLD = "Rocca Celeste",
	THEHEARTOFAZERTH = "The Heart of Azeroth",
	THEWANDERINGISLE = "The Wandering Isle Monk",
	TRUESHOTLODGE = "Trueshot Lodge Hunter",
	MAWOFSOULS = "Fauci delle Anime",
	LEGIONUNCATEQUEST = "Legion Uncategorized Quests",
	RETURNTOKARAZHAN = "Ritorno a Karazhan",
	MACAREE = "Mac'Aree",
	DREADSCARRIFT = "Faglia Malosfregio",
	HELHEIM = "Helheim",
	EMERALDDREAMWAY = "Emerald Dreamway",
	BFA = "Battle For Azeroth",
	BFAUNCATEQUEST = "BFA Uncategorized Quests",
	ZANDALAR = "Zandalar",
	KULTIRAS = "Kul Tiras",
	THUNDERTOTEM = "Thunder Totem",
	KINGSREST = "Requie dei Re",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	THRUNDERROT = "The Underrot",
	THEDEATHOFCHROMIE = "The Deaths Of Chromie",
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	THEDRAGONSSPINE = "The Dragon`s Spine",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	CLASSCAMPAINS = "Class Campains",
	TERRACEOFENLESSSPRINGS = "Terrazza dell'Eterna Primavera",
	PLAYERVSPLAYER = "Player Vs Player",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
	WORLDPVP = "World Pvp",
	NYALOTHATHEWALKINGCITY = "Ny'alotha, la Città Risvegliata",
	VISIONSOFNZOTH = "Visions of N'Zoth",
	BLACKEMPIRECAMPAIGN = "Black Empire Campaign",
	WORLDQUEST = "World Quests",
		-- Shadowlands Code
	-- Shadowlands Code
	SHADOWLANDS = "Shadowlands",
	SHADOWLANDSUNCATEQUEST = "Shadowlands Uncategorized Quests",
	COVENANTCALLINGS = "Covenant Callings",
	KYRIAN = "Kyrian",
	NECROLORD = "Necrolord",
	NIGHTFAE = "Night Fae",
	VENTHYR = "Venthyr",
	MAINZONES = "Main Zones",
	OTHERCATEGORIES	= "Other Categories",
	NINEONECAMPAIGN = "9.1 Campaign",
	ABOMINABLESTICHING = "Cuciture Abominevoli",
	COVENANTASSAULTS = "Covenant Assaults",
	COVENANTSANCTUARY = "Covenant Sanctuary",
	COVENANTSANCTUM = "Covenant Sanctum",
	EMBERCOURT = "Ember Court",
	KEEPERSRESPITE = "Riposo del Custode",
	PATHOFASCENSION = "Path of Ascension",
	TAZAVESH = "Tazavesh",
	THEARCHIVISTSCODEX = "The Archivists' Codex",
	TORGHASTTOWEROFTHEDAMNED = "Torgast, Torre dei Dannati",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
	AZEROTHIANARCHIVES = "Azerothian Archives",
	AZMERLOTH = "Azmerloh",
	BRACKENHIDEWATERHOLE = "Brackenhide Waterhole",
	DRAGONISLE = "Dragon Isle",
	DRAGONFLIGHT = "Dragonflight",
	DRAGONSCALEBASECAMP = "Dragonscale Basecamp",
	DRAGONSCALEEXPEDITION = "Dragonscale Expedition",
	DUNGEONS = "Dungeons",
	EMERALDARDENS = "Emerald Gardens",
	HORNSWOGHOLLOW = "Hornswog Hollow",
	ISKAARATUSKARR = "Iskaara Tuskarr",
	LOSTRUINS = "Lost Ruins",
	MARUUKCENTAUR = "Maruuk Centaur",
	OBSIDIANCITADEL = "Cittadella d'Ossidiana", 
	PASSAGEOFTIME = "Passaggio del Tempo",
	PRIMALISTSTORMS = "Primalist Storms",
	PRIMORDIALALE = "Primordial Vale",
	RUBYLIFEPOOLS = "Pozze della Vita di Rubino",
	RUBYLIFESHRINE = "Ruby Lifeshrine",
	SHADOWLEDGE = "Shadow Legde",
	TEMPESTUNLEASHED = "Tempest Unleashed",
	THEPRIMAISTFUTURE = "The Primalist Future",
	THERONSWATCH = "Theron`s Watch",
	VALDRAKKENACCORD = "Valdrakken Accord",
	WHALLERSNOOK = "Whaler`s Nook",
	KORRAKSREVENGE = "Korrak`s Revenge",
	--TWW
	TWW = "The War Within",
	AWAKENINGTHEMACHINE = "Risveglio della Macchina",
	DEEPHAULRAVINE = "Gola Cavafonda",	
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NERUBARPALACE = "Palazzo dei Nerub'ar",
	NORTHRENDCUP = "Northrend Cup",
	RAMBLESHIRE = "Raminborgo",
	UPGRADESYSTEM = "Upgrade System",
	WARBANDS = "Warbands",
	ARATHIHIGHLANDSTWW = "Arathi Highlands TWW",
	DELVESHEADQUARTERS = "Quartier Generale delle Scorribande",
	DELVES = "Delves",
	THERAMORESFALLS = "Theramore`s  Fall",
	TIMERUNNING = "Timerunning",
	THEHARBINGER = "The Harbinger",
	GILNEASRECLAMATION = "Gilneas Reclamation",
	LITTLESCALESDAYCARE = "Little Scales Daycare",
	TIMERIFT = "Time Rift",
	AMIRDRASIL = "Amirdrasil",
	AMIRDRASSILTHEDREAMSHOPE = "Amirdrassil, Speranza del Sogno",
	THEOASIS = "Oasi",
	--MID
	MIDNIGHT = "Midnight",
	FOUNDERSPOINT = "Punta della Fondazione",
	NEIGHBORHOOD = "Neighborhood",
	RAZORWINDSHORES = "Sponde Brezza Aguzza",
	SLAYERSRISE = "Altura del Carnefice",
	WESTSANCTUM = "Santuario dell'Ovest",	
	}

end