if GetLocale() == "esES" then
qcLocalize = setmetatable({
	AHNQIRAJWAR = "Guerra de Ahn'Qiraj",
	ASSAULTONTHEDARKPORTAL = "Asalto al Portal Oscuro",
	CAMPING = "Acampando",
	CENTRALKALIMDOR = "Kalimdor central", -- Needs review
	CLASSES = "Clases",
	CLASSQUESTS = "Misiones de clase",
	CLEARUPDATECACHE = "Borrar caché de actualización",
	CONFIGSUBTITLE = "Estas opciones permiten modificar cómo Quest Completist maneja y filtra los datos",
	CONFIGTITLE = "Quest Completist - Configuración",
	CONTINENTS = "Continentes",
	DAYOFTHEDEAD = "Festividad de los Muertos",
	DEATHRISING = "Muerte emergente",
	ELEMENTALBONDS = "Vínculos elementales",
	FIRELANDSINVASION = "Invasión de las Tierras de Fuego",
	GARRISONCAMPAIGN = "Campaña de la ciudadela",
	GARRISONSUPPORT = "Apoyo de la ciudadela",
	HIDEDAILYQUEST = "Ocultar misiones diarias", -- Needs review
	HIDEINPROGRESSQUESTS = "Ocultar misiones en curso",
	HIDELOWLEVELQUESTS = "Ocultar misiones de nivel bajo",
	HIDENONACTIVESEASONALQUESTS = "Esconder misiones de eventos inactivos",
	HIDEOTHERFACTIONQUESTS = "Esconder otras misiones de facción",
	HIDEOTHERPROFESSIONQUESTS = "Esconder otras misiones de profesión",
	HIDEOTHERRACEANDCLASSQUESTS = "Esconder otras misiones de clase/raza",
	HIDECOMPLETEDQUESTS = "Ocultar misiones completadas", -- Needs review
	HIDEOTHERCOVENANTQUESTS = "Ocultar misiones de otras curias", -- Needs review
	HIDEWARBANDS = "Ocultar misiones hechas por otros personajes de la banda guerrera", -- Needs review
	HIDEUNAVAILABLE = "Ocultar misiones que ya no están disponibles", -- Needs review
	HIDEREQUIREMENTSNOTMET = "Ocultar misiones con requisitos sin cumplir", -- Needs review
	HIDENODATA = "Ocultar marcadores sin datos de misión", -- Needs review
	HIDEREPEATABLEQUEST = "Ocultar misiones repetibles", -- Needs review
	HIDEWORLDQUEST = "Ocultar misiones de mundo y semanales", -- Needs review
	INVASION = "Invasión",
	KHAZMODAN = "Khaz Modan", -- Requires localization
	LANDFALL = "Desembarco",
	LORDAERON = "Lordaeron", -- Requires localization
	LUNARFESTIVAL = "Festival Lunar",
	MIDSUMMER = "Verano",
	NORTHERNKALIMDOR = "Kalimdor del norte", -- Needs review
	PANDARENBREWMASTERS = "Maestros cerveceros pandaren",
	PANDARENCAMPAIGN = "Campaña pandaren",
	PERFORMSERVERQUERY = "Enviar consulta al servidor...",
	QUERYREQUESTED = "Se ha enviado una consulta al servidor...",
	QUESTLIST = "Lista de misiones", -- Needs review
	QUESTSFOUND = "%d misiones encontradas",
	SEASONAL = "Estacional",
	SHOWMAPICONS = "Mostrar iconos del mapa",
	SKETTIS = "Skettis", -- Requires localization
	SORTALPHA = "Ordenar: alfabéticamente",
	SORTLEVEL = "Ordenar: por nivel",
	SOUTHERNKALIMDOR = "Kalimdor del sur", -- Needs review
	SPECIALS = "Especiales",
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "Vega de Tuercespina",
	THEZANDALARI = "Los Zandalari",
	TOURNAMENT = "Torneo",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "Eventos semanales", -- Needs review
	WORLDEVENTS = "Eventos del Mundo",
	MACAREE = "Mac'Aree",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	ALLIANCEWARCAMPAIGN = "Campaña de guerra de la Alianza",
	HORDEWARCAMPAIGN = "Campaña de guerra de la Horda",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	HERITAGE = "Legado",
	RATEDPVP = "JcJ puntuado",
	WORLDPVP = "JcJ del mundo",
	BLACKEMPIRECAMPAIGN = "Campaña del Imperio Negro",
		-- Shadowlands Code
	-- Shadowlands Code
	MAINZONES = "Zonas principales", -- Needs review
	OTHERCATEGORIES = "Otras categorías", -- Needs review
	COVENANTASSAULTS = "Asaltos de curias",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
	--TWW
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NORTHRENDCUP = "Copa de Rasganorte",
	UPGRADESYSTEM = "Sistema de mejora",
	WARBANDS = "Bandas guerreras",
	TIMERUNNING = "Asalto temporal",
	THEHARBINGER = "La Presagista",
	GILNEASRECLAMATION = "La reclamación de Gilneas",
	TIMERIFT = "Time Rift",
	--MID
	NEIGHBORHOOD = "Neighborhood",
	PROGRESS = "%d/%d completadas (%d%%)", -- Needs review
	SERVERQUERYRESULT = "El servidor indica %d misiones completadas que Quest Completist conoce, %d de ellas marcadas como completadas por primera vez.", -- Needs review
	CACHECLEARED = "Caché vaciada.", -- Needs review
	CLEARINGCACHE = "Vaciando tu caché de actualización...", -- Needs review
	NODETAILS = "El juego no ofrece los detalles de la misión", -- Needs review
	QUESTID = "ID de misión:", -- Needs review
	STORYLINEPOSITION = "(%d de %d)", -- Needs review
	CAMPAIGNCHAPTER = "(capítulo %d de %d)", -- Needs review
	EARLIERQUESTS = "... %d anteriores", -- Needs review
	LATERQUESTS = "... %d más", -- Needs review
	THISQUEST = "esta misión", -- Needs review
	REQUIREDQUEST = "Misión necesaria:", -- Needs review
	REQUIREDFACTION = "Facción necesaria:", -- Needs review
	REQUIREDRENOWN = "Nivel de renombre necesario:", -- Needs review
	REQUIREDRANK = "Rango necesario:", -- Needs review
	REQUIREDSKILL = "Habilidad necesaria:", -- Needs review
	RANKLEVEL = "Rango %d", -- Needs review
	QUESTGIVER = "Ofrece la misión:", -- Needs review
	NOQUESTGIVER = "Desconocido, o misión aceptada automáticamente", -- Needs review
	REPAMOUNT = "%d de reputación", -- Needs review
	NEWDATAINTRO = "Quest Completist no conocía la siguiente información. Ayuda a mejorar la precisión del addon publicándola en CurseForge.", -- Needs review
	NEWDATAQUEST = " - La misión no existe en la base de datos.", -- Needs review
	NEWDATAFACTION = " - QC no sabía que tu FACCIÓN podía completar esta misión.", -- Needs review
	NEWDATARACE = " - QC no sabía que tu RAZA podía completar esta misión.", -- Needs review
	NEWDATACLASS = " - QC no sabía que tu CLASE podía completar esta misión.", -- Needs review
	NEWDATAALERT = "¡Datos nuevos encontrados - contribuye!", -- Needs review
	BREADCRUMBAVAILABLE = "¡1 misión de introducción disponible!", -- Needs review
	BREADCRUMBSAVAILABLE = "¡%d misiones de introducción disponibles!", -- Needs review
	BREADCRUMBQUESTS = "Misiones de introducción", -- Needs review
	MUTUALLYEXCLUSIVE = "Esta misión excluye a otras: solo puedes completar una de ellas. Las otras misiones son:", -- Needs review
	NOTINDATABASE = "Misión fuera de la base de datos", -- Needs review
	YOURSELF = "<Tú mismo>", -- Needs review
	OTHERQUESTS = "Otras misiones", -- Needs review
	PINDONE = "%d completadas", -- Needs review
	PINSHOWDONE = "Mayús para mostrar", -- Needs review
	PINWAYPOINT = "Haz clic para poner un punto de ruta de TomTom", -- Needs review
	WELCOME = "Gracias por usar Quest Completist. ¿Has visto un error en una misión? Infórmalo en CurseForge.", -- Needs review
	UNAVAILABLEACCEPTED = "La misión %d \"%s\" figura como ya no disponible, pero acabas de aceptarla. Se te muestra con normalidad; infórmalo para que se corrija la lista.", -- Needs review
	UNAVAILABLETURNEDIN = "La misión %d \"%s\" figura como ya no disponible, pero acabas de entregarla. Se te muestra con normalidad; infórmalo para que se corrija la lista.", -- Needs review
	TOGGLEFRAME = "Mostrar/ocultar ventana", -- Needs review
	}, {__index = qcLocalize})

end