if GetLocale() == "zhTW" then
qcLocalize = setmetatable({
	AHNQIRAJWAR = "安其拉之戰",
	ASSAULTONTHEDARKPORTAL = "襲擊黑暗之門",
	CAMPING = "紮營",
	CENTRALKALIMDOR = "卡林多中部", -- Needs review
	CLASSES = "職業", -- Needs review
	CLASSQUESTS = "職業任務", -- Needs review
	CLEARUPDATECACHE = "清除更新快取", -- Needs review
	CONFIGSUBTITLE = "這些選項允許你改變 Quest Completist 對其自身資料處理和過濾的方式", -- Needs review
	CONFIGTITLE = "Quest Completist - 設置", -- Needs review
	CONTINENTS = "地區", -- Needs review
	DAYOFTHEDEAD = "亡者節",
	DEATHRISING = "死亡崛起",
	ELEMENTALBONDS = "元素桎梏",
	FIRELANDSINVASION = "火源之界進軍行動",
	GARRISONCAMPAIGN = "要塞戰役",
	GARRISONSUPPORT = "要塞支援",
	HIDECOMPLETEDQUESTS = "隱藏已完成的任務", -- Needs review
	HIDEDAILYQUEST = "隱藏每日任務", -- Needs review
	HIDEINPROGRESSQUESTS = "隱藏進行中的任務", -- Needs review
	HIDELOWLEVELQUESTS = "隱藏低等級的任務", -- Needs review
	HIDENONACTIVESEASONALQUESTS = "隱藏尚未開始的季節性任務", -- Needs review
	HIDEOTHERFACTIONQUESTS = "隱藏其他陣營的任務", -- Needs review
	HIDEOTHERPROFESSIONQUESTS = "隱藏其他專業的任務", -- Needs review
	HIDEOTHERRACEANDCLASSQUESTS = "隱藏其他種族和職業任務", -- Needs review
	HIDEOTHERCOVENANTQUESTS = "隱藏其他誓盟的任務", -- Needs review
	HIDEWARBANDS = "隱藏戰隊中其他角色已完成的任務", -- Needs review
	HIDEUNAVAILABLE = "隱藏已無法取得的任務", -- Needs review
	HIDEREQUIREMENTSNOTMET = "隱藏未滿足條件的任務", -- Needs review
	HIDENODATA = "隱藏沒有任務資料的標記", -- Needs review
	HIDEREPEATABLEQUEST = "隱藏可重複任務", -- Needs review
	HIDEWORLDQUEST = "隱藏世界任務和每週任務", -- Needs review
	INVASION = "入侵",
	KHAZMODAN = "卡茲莫丹", -- Needs review
	LANDFALL = "登陸",
	LORDAERON = "洛丹倫", -- Needs review
	LUNARFESTIVAL = "新年慶典",
	MIDSUMMER = "仲夏",
	NORTHERNKALIMDOR = "卡林多北部", -- Needs review
	PANDARENBREWMASTERS = "熊貓人釀酒大師",
	PANDARENCAMPAIGN = "熊貓人戰役",
	PERFORMSERVERQUERY = "進行伺服器查詢中...", -- Needs review
	QUERYREQUESTED = "已經對伺服器進行查詢的要求...", -- Needs review
	QUESTLIST = "任務列表", -- Needs review
	QUESTSFOUND = "已找到 %d 個任務", -- Needs review
	SEASONAL = "季節性",
	SHOWMAPICONS = "顯示地圖小圖示", -- Needs review
	SKETTIS = "Skettis", -- Requires localization
	SORTALPHA = "排序：以字母順序", -- Needs review
	SORTLEVEL = "排序：以等級", -- Needs review
	SOUTHERNKALIMDOR = "卡林多南部", -- Needs review
	SPECIALS = "特殊", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "荊棘谷", -- Needs review
	THEZANDALARI = "贊達拉",
	TOURNAMENT = "聯賽",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "每週活動", -- Needs review
	WORLDEVENTS = "世界事件", -- Needs review
	MACAREE = "Mac'Aree",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	ALLIANCEWARCAMPAIGN = "聯盟陣營戰役",
	HORDEWARCAMPAIGN = "部落陣營戰役",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	HERITAGE = "傳承",
	RATEDPVP = "積分PvP",
	WORLDPVP = "世界PvP",
	BLACKEMPIRECAMPAIGN = "黑暗帝國戰役",
	-- Shadowlands Code
	-- Shadowlands Code
	MAINZONES = "主要區域", -- Needs review
	OTHERCATEGORIES = "其他分類", -- Needs review
	COVENANTASSAULTS = "誓盟進攻戰",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
	--TWW
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NORTHRENDCUP = "北裂境杯",
	UPGRADESYSTEM = "升級系統",
	WARBANDS = "戰隊",
	TIMERUNNING = "時光奔走",
	THEHARBINGER = "先驅者",
	GILNEASRECLAMATION = "收復吉爾尼斯",
	TIMERIFT = "Time Rift",
	--MID
	NEIGHBORHOOD = "Neighborhood",
	PROGRESS = "%d/%d 已完成 (%d%%)", -- Needs review
	SERVERQUERYRESULT = "伺服器回報了%d個Quest Completist已知的已完成任務，其中%d個是新標記為已完成的。", -- Needs review
	CACHECLEARED = "快取已清除。", -- Needs review
	CLEARINGCACHE = "正在清除更新快取……", -- Needs review
	NODETAILS = "遊戲未提供任務詳情", -- Needs review
	QUESTID = "任務ID：", -- Needs review
	STORYLINEPOSITION = "(%d/%d)", -- Needs review
	CAMPAIGNCHAPTER = "(第%d章，共%d章)", -- Needs review
	EARLIERQUESTS = "... 之前%d個", -- Needs review
	LATERQUESTS = "... 還有%d個", -- Needs review
	THISQUEST = "此任務", -- Needs review
	REQUIREDQUEST = "前置任務：", -- Needs review
	REQUIREDFACTION = "所需陣營：", -- Needs review
	REQUIREDRENOWN = "所需名望等級：", -- Needs review
	REQUIREDRANK = "所需聲望等級：", -- Needs review
	REQUIREDSKILL = "所需技能：", -- Needs review
	RANKLEVEL = "等級 %d", -- Needs review
	QUESTGIVER = "任務提供者：", -- Needs review
	NOQUESTGIVER = "未知，或自動接受的任務", -- Needs review
	REPAMOUNT = "%d聲望", -- Needs review
	NEWDATAINTRO = "Quest Completist之前不知道以下資訊。請在CurseForge上回報，協助提高插件的準確性。", -- Needs review
	NEWDATAQUEST = " - 資料庫中沒有此任務。", -- Needs review
	NEWDATAFACTION = " - QC不知道你的陣營可以完成此任務。", -- Needs review
	NEWDATARACE = " - QC不知道你的種族可以完成此任務。", -- Needs review
	NEWDATACLASS = " - QC不知道你的職業可以完成此任務。", -- Needs review
	NEWDATAALERT = "發現新資料 - 請提交回報！", -- Needs review
	BREADCRUMBAVAILABLE = "有1個引導任務可接！", -- Needs review
	BREADCRUMBSAVAILABLE = "有%d個引導任務可接！", -- Needs review
	BREADCRUMBQUESTS = "引導任務", -- Needs review
	MUTUALLYEXCLUSIVE = "此任務與其他任務互斥，你只能完成其中一個。其他任務為：", -- Needs review
	NOTINDATABASE = "資料庫中沒有此任務", -- Needs review
	YOURSELF = "<你自己>", -- Needs review
	OTHERQUESTS = "其他任務", -- Needs review
	PINDONE = "已完成 %d 個", -- Needs review
	PINSHOWDONE = "按住 Shift 顯示", -- Needs review
	PINWAYPOINT = "點擊設定 TomTom 路徑點", -- Needs review
	WELCOME = "感謝使用Quest Completist。發現任務資訊有誤？請在CurseForge上回報。", -- Needs review
	UNAVAILABLEACCEPTED = "任務%d「%s」被列為已無法取得，但你剛剛接受了它。它會對你正常顯示；請回報，以便修正清單。", -- Needs review
	UNAVAILABLETURNEDIN = "任務%d「%s」被列為已無法取得，但你剛剛交付了它。它會對你正常顯示；請回報，以便修正清單。", -- Needs review
	TOGGLEFRAME = "顯示/隱藏視窗", -- Needs review
	SHOWMINIMAPBUTTON = "顯示小地圖按鈕", -- Needs review
	MINIMAPLEFTCLICK = "左鍵點擊：顯示或隱藏任務列表", -- Needs review
	MINIMAPRIGHTCLICK = "右鍵點擊：開啟設定", -- Needs review
	MINIMAPDRAG = "拖曳：沿小地圖邊緣移動此按鈕", -- Needs review
	}, {__index = qcLocalize})

end