if GetLocale() == "ptBR" then
qcLocalize = setmetatable({
	AHNQIRAJTHEFALLENKINGDOM = "Ahn'Qiraj: O Reino Derrotado",
	ALCHEMY = "Alquimia",
	ARCHAEOLOGY = "Arqueologia",
	ASSAULTONTHEDARKPORTAL = "Assault on the Dark Portal", -- Requires localization
	AZEROTH = "Azeroth",
	BARADINHOLD = "Guarnição Baradin",
	BATTLEGROUNDS = "Campos de Batalha",
	BATTLEPETS = "Mascotes de Batalha",
	BLACKSMITHING = "Ferraria",
	BLACKWINGDESCENT = "Descenso do Asa Negra",
	BLACKWINGLAIR = "Covil Asa Negra",
	BRAWLERSGUILD = "Brawler's Guild", -- Requires localization
	BREWFEST = "CervaFest",
	CAVERNSOFTIME = "Cavernas do Tempo",
	CENTRALKALIMDOR = "Kalimdor Central", -- Needs review
	CHILDRENSWEEK = "Semana das Crianças",
	CLASSES = "Classes",
	CLASSQUESTS = "Missões de Classe",
	CLEARUPDATECACHE = "Limpar o cache de atualizações...",
	COILFANGRESERVOIR = "Reservatório Presacurva",
	CONFIGSUBTITLE = "Essas opções permitem mudar o jeito que o Quest Completist manipula e filtra os dados.",
	CONFIGTITLE = "Quest Completist - Configuração",
	CONTINENTS = "Continentes",
	COOKING = "Culinária",
	DARKMOONFAIRE = "Feira de Negraluna",
	DAYOFTHEDEAD = "Dia dos Mortos",
	DEATHKNIGHT = "Cavaleiro da Morte",
	DRAENOR = "Draenor",
	DRAGONSOUL = "Alma Dragônica",
	DRUID = "Druida",
	DUNGEONSANDRAIDS = "Masmorras e Raides",
	EASTERNKINGDOMS = "Reinos do Leste",
	ELEMENTALBONDS = "Prisão elemental",
	ENCHANTING = "Encantamento",
	ENGINEERING = "Engenharia",
	FIRELANDS = "Terras do Fogo",
	FIRELANDSINVASION = "Invasão às Terras do Fogo",
	FIRSTAID = "Primeiros Socorros",
	FISHING = "Pesca",
	GARRISONCAMPAIGN = "Garrison Campaign", -- Requires localization
	GARRISONSUPPORT = "Garrison Support", -- Requires localization
	GREENSTONEVILLAGE = "Aldeia Rocha Verde",
	GRUULSLAIR = "Covil de Gruul",
	HALLOWSEND = "Noturnália",
	HARVESTFESTIVAL = "Festival da Colheita",
	HELLFIRECITADEL = "Cidadela Fogo do Inferno",
	HERBALISM = "Herborismo",
	HIDECOMPLETEDQUESTS = "Ocultar as missões completadas",
	HIDEDAILYQUEST = "Ocultar missões diárias", -- Needs review
	HIDEINPROGRESSQUESTS = "Ocultar missões em andamento",
	HIDELOWLEVELQUESTS = "Ocultar missões de nível baixo",
	HIDENONACTIVESEASONALQUESTS = "Ocultar Missões de Eventos Mundiais não ativas",
	HIDENORMALQUEST = "Hide Normal Quests",
	HIDEOTHERFACTIONQUESTS = "Ocultar missões de outra facção",
	HIDEOTHERPROFESSIONQUESTS = "Ocultar missões de outra profissão",
	HIDEOTHERCOVENANTQUESTS = "Ocultar missões de outros pactos", -- Needs review
	HIDEWARBANDS = "Ocultar missões feitas por outros personagens do bando de guerra", -- Needs review
	HIDEUNAVAILABLE = "Ocultar missões que não estão mais disponíveis", -- Needs review
	HIDEREQUIREMENTSNOTMET = "Ocultar missões com requisitos não cumpridos", -- Needs review
	HIDENODATA = "Ocultar marcadores sem dados de missão", -- Needs review
	HIDEREPEATABLEQUEST = "Ocultar missões repetíveis", -- Needs review
	HIDEWORLDQUEST = "Ocultar missões mundiais e semanais", -- Needs review
	HIDEOTHERRACEANDCLASSQUESTS = "Ocultar missões de outra raça e classe",
	HUNTER = "Caçador",
	INSCRIPTION = "Escrivania",
	ISLEOFGIANTS = "Ilha de Gigantes",
	JADETEMPLEGROUNDS = "Jade Temple Grounds", -- Requires localization
	JEWELCRAFTING = "Joalheria",
	KALIMDOR = "Kalimdor",
	KHAZMODAN = "Khaz Modan", -- Requires localization
	LANDFALL = "Landfall", -- Requires localization
	LEATHERWORKING = "Couraria",
	LEGENDARY = "Lendário",
	LORDAERON = "Lordaeron", -- Requires localization
	LOVEISINTHEAIR = "O Amor Está No Ar",
	LUNARFESTIVAL = "Festival da Lua",
	MAGE = "Mago",
	MIDSUMMERFIREFESTIVAL = "Festival do Fogo do Solstício",
	MINING = "Mineração",
	MISCELLANEOUS = "Miscelânea",
	MOGUSHANVAULTS = "Galerias Mogu'shan",
	MONK = "Monge",
	NAGRAND = "Nagrand",
	NEWYEARSEVE = "Véspera de Ano Novo",
	NOBLEGARDEN = "Jardinova",
	NORTHERNKALIMDOR = "Kalimdor do Norte", -- Needs review
	NORTHREND = "Nortúndria",
	ONYXIASLAIR = "Covil de Onyxia",
	OPTIONS = "Opções",
	OUTLAND = "Terralém",
	PALACEOFTHEHEAVENS = "Palácio Mogu'shan",
	PALADIN = "Paladino",
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Pandaren Campaign", -- Requires localization
	PANDARIA = "Pandária",
	PEAKOFSERENITY = "Peak of Serenity", -- Requires localization
	PERFORMSERVERQUERY = "Consultar o servidor...",
	PILGRIMSBOUNTY = "Festa da Fartura",
	PRIEST = "Sacerdote",
	PROFESSIONS = "Profissões",
	QUERYREQUESTED = "Foi feita uma consulta ao servidor...",
	QUESTLIST = "Lista de Missões", -- Needs review
	QUESTSFOUND = "%d missões encontradas",
	RAIDS = "Raides",
	REGIONS = "Regions", -- Requires localization
	RIDING = "Riding", -- Requires localization
	ROGUE = "Ladino",
	RUINSOFGILNEASCITY = "Ruínas de Guilnéas",
	SCENARIO = "Scenario", -- Requires localization
	SEASONAL = "Eventos Mundiais",
	SERPENTSHRINECAVERN = "Caverna do Serpentário",
	SHADOWMOONVALLEY = "Vale da Lua Negra",
	SHAMAN = "Xamã",
	SHOWMAPICONS = "Mostrar ícones no mapa",
	SKETTIS = "Skettis", -- Requires localization
	SKINNING = "Esfolamento",
	SORTALPHA = "Classificar: Alfabeticamente",
	SORTLEVEL = "Classificar: Nível",
	SOUTHERNKALIMDOR = "Kalimdor do Sul", -- Needs review
	SPECIAL = "Especial",
	SPECIALS = "Especiais",
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "Selva do Espinhaço",
	TAILORING = "Alfaiataria",
	TEMPLEOFTHEREDCRANE = "Templo da Garça Vermelha",
	THEARBORETUM = "The Arboretum", -- Requires localization
	THEBASTIONOFTWILIGHT = "Bastião do Crepúsculo",
	THEBLACKMORASS = "Lamaçal Negro",
	THEEVERBLOOM = "Floretérnia",
	THEEYE = "O Olho",
	THEGATEOFTHESETTINGSUN = "Portal do Sol Poente",
	THEHALFHILLMARKET = "Mercado de Meia Colina",
	THEMAELSTROM = "Voragem",
	THEOBSIDIANSANCTUM = "O Santuário Obsidiano",
	THETEMPLEOFTHEJADESERPENT = "Templo da Serpente de Jade",
	THEVIOLETHOLD = "O Castelo Violeta",
	THEZANDALARI = "os Zandalári",
	THRONEOFTHEFOURWINDS = "Trono dos Quatro Ventos",
	TOURNAMENT = "Torneio",
	UPPERBLACKROCKSPIRE = "Pico da Rocha Negra Superior",
	UNCATEGORIZED = "Sem categoria", -- Needs review
	VASHJIR = "Vashj'ir",
	VAULTOFARCHAVON = "Abóbada de Arcavon",
	WARLOCK = "Bruxo",
	WARRIOR = "Guerreiro",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "Eventos semanais", -- Needs review
	WINTERVEIL = "Véu de Inverno",
	WORLDEVENTS = "Eventos Mundiais",
	THEBROKENISLES = "The Broken Isles",
	THEDREAMGROVE = "O Bosque Onírico",
	DEMONHUNTER = "Caçador de Demônios",
	CONTESTCOMMING = "Contest comming shows wrong zone",
	HALLOFTHEGUARDIAN = "Salão do Guardião",
	MARDUMTHESHATTEREDABYSS = "Mardum, the Shattered Abyss",
	NETHERLIGHTTEMPLE = "Templo Eterluz",
	SKYHOLD = "Fortaleza Celeste",
	THEHEARTOFAZERTH = "The Heart of Azeroth",
	THEWANDERINGISLE = "The Wandering Isle Monk",
	TRUESHOTLODGE = "Trueshot Lodge Hunter",
	MAWOFSOULS = "Gorja das Almas",
	LEGIONUNCATEQUEST = "Legion Uncategorized Quests",
	RETURNTOKARAZHAN = "Retorno a Karazhan",
	MACAREE = "Mac'Aree",
	DREADSCARRIFT = "Fenda Chagamedo",
	HELHEIM = "Helheim",
	EMERALDDREAMWAY = "Emerald Dreamway",
	BFA = "Battle For Azeroth",
	ZANDALAR = "Zandalar",
	KULTIRAS = "Kul Tiras",
	THUNDERTOTEM = "Thunder Totem",
	KINGSREST = "Repouso do Rei",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	THRUNDERROT = "The Underrot",
	THEDEATHOFCHROMIE = "The Deaths Of Chromie",
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	THEDRAGONSSPINE = "The Dragon`s Spine",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	TERRACEOFENLESSSPRINGS = "Terraço da Primavera Eterna",
	PLAYERVSPLAYER = "Player Vs Player",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
	WORLDPVP = "World Pvp",
	NYALOTHATHEWALKINGCITY = "Ny'alotha, a Cidade Desperta",
	VISIONSOFNZOTH = "Visions of N'Zoth",
	BLACKEMPIRECAMPAIGN = "Black Empire Campaign",
	WORLDQUEST = "World Quests",
		-- Shadowlands Code
	-- Shadowlands Code
	SHADOWLANDS = "Shadowlands",
	SHADOWLANDSUNCATEQUEST = "Shadowlands Uncategorized Quests",
	COVENANTCALLINGS = "Covenant Callings",
	KYRIAN = "Kyrian",
	NECROLORD = "Necrolord",
	NIGHTFAE = "Night Fae",
	VENTHYR = "Venthyr",
	MAINZONES = "Zonas principais", -- Needs review
	OTHERCATEGORIES = "Outras categorias", -- Needs review
	NINEONECAMPAIGN = "9.1 Campaign",
	ABOMINABLESTICHING = "Sutura de Abominação",
	COVENANTASSAULTS = "Covenant Assaults",
	COVENANTSANCTUARY = "Covenant Sanctuary",
	COVENANTSANCTUM = "Covenant Sanctum",
	EMBERCOURT = "Ember Court",
	KEEPERSRESPITE = "Repouso do Guardião",
	PATHOFASCENSION = "Path of Ascension",
	THEARCHIVISTSCODEX = "The Archivists' Codex",
	TORGHASTTOWEROFTHEDAMNED = "Thanator, a Torre dos Malditos",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
	AZEROTHIANARCHIVES = "Azerothian Archives",
	AZMERLOTH = "Azmerloh",
	BRACKENHIDEWATERHOLE = "Brackenhide Waterhole",
	DRAGONISLE = "Dragon Isle",
	DRAGONFLIGHT = "Dragonflight",
	DRAGONSCALEBASECAMP = "Dragonscale Basecamp",
	DRAGONSCALEEXPEDITION = "Dragonscale Expedition",
	DUNGEONS = "Dungeons",
	EMERALDARDENS = "Emerald Gardens",
	HORNSWOGHOLLOW = "Hornswog Hollow",
	ISKAARATUSKARR = "Iskaara Tuskarr",
	LOSTRUINS = "Lost Ruins",
	MARUUKCENTAUR = "Maruuk Centaur",
	OBSIDIANCITADEL = "Cidadela Obsidiana", 
	PASSAGEOFTIME = "Passagem do Tempo",
	PRIMALISTSTORMS = "Primalist Storms",
	PRIMORDIALALE = "Primordial Vale",
	RUBYLIFEPOOLS = "Poços da Vida Rubi",
	RUBYLIFESHRINE = "Ruby Lifeshrine",
	SHADOWLEDGE = "Shadow Legde",
	TEMPESTUNLEASHED = "Tempest Unleashed",
	THEPRIMAISTFUTURE = "The Primalist Future",
	THERONSWATCH = "Theron`s Watch",
	VALDRAKKENACCORD = "Valdrakken Accord",
	KORRAKSREVENGE = "Korrak`s Revenge",
	--TWW
	TWW = "The War Within",
	AWAKENINGTHEMACHINE = "Despertando a Máquina",
	DEEPHAULRAVINE = "Ravina Cargafunda",	
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NERUBARPALACE = "Palácio Nerub-ar",
	NORTHRENDCUP = "Northrend Cup",
	RAMBLESHIRE = "Campo Aberto",
	UPGRADESYSTEM = "Upgrade System",
	WARBANDS = "Warbands",
	ARATHIHIGHLANDSTWW = "Arathi Highlands TWW",
	DELVESHEADQUARTERS = "Quartel-general do Imersor",
	DELVES = "Delves",
	THERAMORESFALLS = "Theramore`s  Fall",
	TIMERUNNING = "Timerunning",
	THEHARBINGER = "The Harbinger",
	GILNEASRECLAMATION = "Gilneas Reclamation",
	LITTLESCALESDAYCARE = "Little Scales Daycare",
	TIMERIFT = "Time Rift",
	AMIRDRASIL = "Amirdrasil",
	AMIRDRASSILTHEDREAMSHOPE = "Amirdrassil, a Esperança Onírica",
	THEOASIS = "Oásis",
	--MID
	MIDNIGHT = "Midnight",
	FOUNDERSPOINT = "Marco do Fundador",
	NEIGHBORHOOD = "Neighborhood",
	RAZORWINDSHORES = "Costa dos Ventos Cortantes",
	SLAYERSRISE = "Alto do Matador",
	WESTSANCTUM = "Sacrário do Oeste",	
	DEADMINES = "Minas Mortas",
	LOWERBLACKROCKSPIRE = "Pico da Rocha Negra Inferior",
	THETEMPLEOFATALHAKKAR = "O Templo de Atal'hakkar",
	THEBATTLEFORMOUNTHYJAL = "A Batalha pelo Monte Hyjal",
	SEATOFTHETRIUMVIRATE = "Sede do Triunvirato",
	TAZAVESHTHEVEILEDMARKET = "Tazavesh, o Mercado Oculto",
	ASSAULTONVIOLETHOLD = "Ataque ao Castelo Violeta",
	DIREMAULCAPITALGARDENS = "Gládio Cruel - Jardins Capitais",
	STRATHOLMEMAINGATE = "Stratholme – Portão Principal",
	TEMPLEOFAHNQIRAJ = "Templo de Ahn'Qiraj",
	DIREMAULWARPWOODQUARTER = "Gládio Cruel - Distrito Lenhatorta",
	DIREMAULGORDOKCOMMONS = "Gládio Cruel - Pátio Gordok",
	STRATHOLMESERVICEENTRANCE = "Stratholme – Entrada de Serviço",
	WINDRUNNERSPIRE = "Pico dos Correventos",
	MAGISTERSTERRACE = "Terraço dos Magísteres",
	MURDERROW = "Travessa do Assassino",
	THEVOIDSPIRE = "A Torre do Caos",
	THEBLINDINGVALE = "O Vale Ofuscante",
	DENOFNALORAKK = "Covil de Nalorakk",
	VOIDSCARARENA = "Arena da Chaga do Caos",
	THEDREAMRIFT = "A Fenda Onírica",
	MAISARACAVERNS = "Cavernas de Maisara",
	NEXUSPOINTXENAS = "Ponto de Nexus Xenas",
	PROGRESS = "%d/%d concluídas (%d%%)", -- Needs review
	SEARCHRESULTS = "Resultados da busca", -- Needs review
	SERVERQUERYRESULT = "O servidor informa %d missões concluídas que o Quest Completist conhece, %d delas marcadas como concluídas agora.", -- Needs review
	CACHECLEARED = "Cache limpo.", -- Needs review
	CLEARINGCACHE = "Limpando seu cache de atualização...", -- Needs review
	NODETAILS = "O jogo não fornece os detalhes da missão", -- Needs review
	QUESTID = "ID da missão:", -- Needs review
	STORYLINE = "Sequência de missões:", -- Needs review
	STORYLINEPOSITION = "(%d de %d)", -- Needs review
	EARLIERQUESTS = "... %d anteriores", -- Needs review
	LATERQUESTS = "... mais %d", -- Needs review
	THISQUEST = "esta missão", -- Needs review
	UNKNOWNQUEST = "Missão desconhecida", -- Needs review
	REQUIREDQUEST = "Missão necessária:", -- Needs review
	UNKNOWNFACTION = "Facção desconhecida", -- Needs review
	REQUIREDFACTION = "Facção necessária:", -- Needs review
	REQUIREDRENOWN = "Nível de renome necessário:", -- Needs review
	REQUIREDRANK = "Grau necessário:", -- Needs review
	RANKLEVEL = "Grau %d", -- Needs review
	DATAUNAVAILABLE = "Dados indisponíveis", -- Needs review
	QUESTGIVER = "Oferecida por:", -- Needs review
	UNKNOWNNPC = "PNJ desconhecido", -- Needs review
	NOQUESTGIVER = "Desconhecido, ou missão aceita automaticamente", -- Needs review
	REPAMOUNT = "%d de reputação", -- Needs review
	NEWDATAINTRO = "O Quest Completist não conhecia as informações a seguir. Ajude a melhorar a precisão do addon publicando-as no CurseForge.", -- Needs review
	NEWDATAQUEST = " - A missão não existe no banco de dados.", -- Needs review
	NEWDATAFACTION = " - O QC não sabia que sua FACÇÃO podia concluir esta missão.", -- Needs review
	NEWDATARACE = " - O QC não sabia que sua RAÇA podia concluir esta missão.", -- Needs review
	NEWDATACLASS = " - O QC não sabia que sua CLASSE podia concluir esta missão.", -- Needs review
	NEWDATAALERT = "Novos dados encontrados - contribua!", -- Needs review
	BREADCRUMBAVAILABLE = "1 missão introdutória disponível!", -- Needs review
	BREADCRUMBSAVAILABLE = "%d missões introdutórias disponíveis!", -- Needs review
	BREADCRUMBQUESTS = "Missões introdutórias", -- Needs review
	MUTUALLYEXCLUSIVE = "Esta missão exclui outras: você só pode concluir uma delas. As outras missões são:", -- Needs review
	NOTINDATABASE = "Missão fora do banco de dados", -- Needs review
	YOURSELF = "<Você mesmo>", -- Needs review
	OTHERQUESTS = "Outras missões", -- Needs review
	PINDONE = "%d concluídas", -- Needs review
	PINSHOWDONE = "Shift para mostrar", -- Needs review
	PINWAYPOINT = "Clique para definir um waypoint do TomTom", -- Needs review
	WELCOME = "Obrigado por usar o Quest Completist. Encontrou um erro em uma missão? Informe no CurseForge.", -- Needs review
	UNAVAILABLEACCEPTED = "A missão %d \"%s\" consta como não mais disponível, mas você acabou de aceitá-la. Ela aparece normalmente para você; informe para que a lista seja corrigida.", -- Needs review
	UNAVAILABLETURNEDIN = "A missão %d \"%s\" consta como não mais disponível, mas você acabou de entregá-la. Ela aparece normalmente para você; informe para que a lista seja corrigida.", -- Needs review
	TOGGLEFRAME = "Mostrar/ocultar janela", -- Needs review
	UNKNOWNZONE = "Zona desconhecida", -- Needs review
	}, {__index = qcLocalize})

end