if GetLocale() == "ruRU" then
qcLocalize = setmetatable({
	ALCHEMY = "Алхимия",
	ARCHAEOLOGY = "Археология",
	ASSAULTONTHEDARKPORTAL = "Штурм Темного портала",
	AZEROTH = "Азерот",
	BATTLEGROUNDS = "Поля сражений",
	BATTLEPETS = "Боевые питомцы",
	BLACKSMITHING = "Кузнечное дело",
	BLACKWINGLAIR = "Логово Крыла Тьмы",
	BRAWLERSGUILD = "Бойцовская гильдия",
	BREWFEST = "Хмельной фестиваль",
	CAVERNSOFTIME = "Пещеры Времени",
	CENTRALKALIMDOR = "Центральный Калимдор",
	CHILDRENSWEEK = "Детская неделя",
	CLASSES = "Классы",
	CLASSQUESTS = "Классовые задания",
	CLEARUPDATECACHE = "Очистить кэш обновлений",
	COILFANGRESERVOIR = "Резервуар Кривого Клыка",
	CONFIGSUBTITLE = "Эти настройки позволяют изменить способ, которым Quest Completist обрабатывает и фильтрует данные",
	CONFIGTITLE = "Quest Completist - Конфигурация",
	CONTINENTS = "Континенты",
	COOKING = "Кулинария",
	DARKMOONFAIRE = "Ярмарка Новолуния",
	DAYOFTHEDEAD = "День мертвых",
	DEATHKNIGHT = "Рыцарь смерти",
	DRAENOR = "Дренор",
	DRUID = "Друид",
	DUNGEONSANDRAIDS = "Подземелья и рейды",
	EASTERNKINGDOMS = "Восточные королевства",
	ELEMENTALBONDS = "Власть стихий",
	ENCHANTING = "Наложение чар",
	ENGINEERING = "Инженерное дело",
	FIRELANDS = "Огненные Просторы",
	FIRELANDSINVASION = "Нападение на Огненные Просторы",
	FIRSTAID = "Первая помощь",
	FISHING = "Рыбная ловля",
	GARRISONCAMPAIGN = "Гарнизонная кампания",
	GARRISONSUPPORT = "Поддержка гарнизона", -- Needs review
	GREENSTONEVILLAGE = "Деревня Зеленой Скалы",
	HALLOWSEND = "Тыквовин",
	HELLFIRECITADEL = "Цитадель Адского Пламени",
	HERBALISM = "Травничество",
	HIDECOMPLETEDQUESTS = "Скрывать выполненные задания",
	HIDEDAILYQUEST = "Скрывать ежедневные задания", -- Needs review
	HIDEINPROGRESSQUESTS = "Скрывать выполняемые в данный момент задания",
	HIDELOWLEVELQUESTS = "Скрывать задания низкого уровня",
	HIDENONACTIVESEASONALQUESTS = "Скрывать неактивные сезонные задания",
	HIDEOTHERFACTIONQUESTS = "Скрывать задания других фракций",
	HIDEOTHERPROFESSIONQUESTS = "Скрывать задания других профессий",
	HIDEOTHERRACEANDCLASSQUESTS = "Скрывать задания других рас и классов",
	HIDEOTHERCOVENANTQUESTS = "Скрывать задания других ковенантов", -- Needs review
	HIDEWARBANDS = "Скрывать задания, выполненные другими персонажами отряда", -- Needs review
	HIDEUNAVAILABLE = "Скрывать задания, которые больше недоступны", -- Needs review
	HIDEREQUIREMENTSNOTMET = "Скрывать задания с невыполненными условиями", -- Needs review
	HIDENODATA = "Скрывать метки без данных о задании", -- Needs review
	HIDEREPEATABLEQUEST = "Скрывать повторяемые задания", -- Needs review
	HIDEWORLDQUEST = "Скрывать локальные и еженедельные задания", -- Needs review
	HUNTER = "Охотник",
	INSCRIPTION = "Начертание",
	ISLEOFGIANTS = "Остров Великанов",
	JADETEMPLEGROUNDS = "Jade Temple Grounds", -- Requires localization
	JEWELCRAFTING = "Ювелирное дело",
	KALIMDOR = "Калимдор",
	KHAZMODAN = "Каз Модан",
	LANDFALL = "Высадка",
	LEATHERWORKING = "Кожевничество",
	LEGENDARY = "Легендарные",
	LORDAERON = "Лордерон",
	LOVEISINTHEAIR = "Любовная лихорадка",
	LUNARFESTIVAL = "Лунный фестиваль",
	MAGE = "Маг",
	MIDSUMMERFIREFESTIVAL = "Огненный солнцеворот",
	MINING = "Горное дело",
	MISCELLANEOUS = "Разные",
	MOGUSHANVAULTS = "Подземелья Могу'шан",
	MONK = "Монах",
	NAGRAND = "Награнд",
	NOBLEGARDEN = "Сад чудес",
	NORTHERNKALIMDOR = "Северный Калимдор",
	NORTHREND = "Нордскол",
	ONYXIASLAIR = "Логово Ониксии",
	OUTLAND = "Запределье",
	PALADIN = "Паладин",
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Пандаренская кампания",
	PANDARIA = "Пандария",
	PEAKOFSERENITY = "Peak of Serenity", -- Requires localization
	PERFORMSERVERQUERY = "Запросить с сервера...",
	PILGRIMSBOUNTY = "Пиршество странников",
	PRIEST = "Жрец",
	PROFESSIONS = "Профессии",
	QUERYREQUESTED = "Отправлен запрос к серверу...",
	QUESTLIST = "Список заданий", -- Needs review
	QUESTSFOUND = "Найдено %d заданий",
	RAIDS = "Рейды",
	RIDING = "Riding", -- Requires localization
	ROGUE = "Разбойник",
	SCENARIO = "Scenario", -- Requires localization
	SEASONAL = "Сезонные",
	SERPENTSHRINECAVERN = "Змеиное святилище",
	SHADOWMOONVALLEY = "Долина Призрачной Луны",
	SHAMAN = "Шаман",
	SHOWMAPICONS = "Показывать значки на карте",
	SKETTIS = "Skettis", -- Requires localization
	SKINNING = "Снятие шкур",
	SORTALPHA = "Упорядочить: по алфавиту",
	SORTLEVEL = "Упорядочить: по уровню",
	SOUTHERNKALIMDOR = "Южный Калимдор",
	SPECIAL = "Особые",
	SPECIALS = "События",
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "Тернистая долина",
	TAILORING = "Портняжное дело",
	THEARBORETUM = "The Arboretum", -- Requires localization
	THEBLACKMORASS = "Черные топи",
	THEEVERBLOOM = "Вечное Цветение",
	THEEYE = "Око",
	THEHALFHILLMARKET = "Рынок Полугорья",
	THEMAELSTROM = "Водоворот",
	THEOBSIDIANSANCTUM = "Обсидиановое святилище",
	THEVIOLETHOLD = "Аметистовая крепость",
	THEZANDALARI = "Зандаларские",
	TOURNAMENT = "Турнирные",
	UPPERBLACKROCKSPIRE = "Верхняя часть пика Черной горы",
	UNCATEGORIZED = "Без категории", -- Needs review
	VASHJIR = "Вайш'ир",
	WARLOCK = "Чернокнижник",
	WARRIOR = "Воин",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "Еженедельные события", -- Needs review
	WINTERVEIL = "Зимний Покров",
	WORLDEVENTS = "Игровые события",
	THEBROKENISLES = "The Broken Isles",
	THEDREAMGROVE = "Роща Снов",
	DEMONHUNTER = "Охотник на демонов",
	HALLOFTHEGUARDIAN = "Оплот Хранителя",
	MARDUMTHESHATTEREDABYSS = "Mardum, the Shattered Abyss",
	NETHERLIGHTTEMPLE = "Храм света Пустоты",
	SKYHOLD = "Небесная Цитадель",
	THEHEARTOFAZERTH = "The Heart of Azeroth",
	THEWANDERINGISLE = "The Wandering Isle Monk",
	TRUESHOTLODGE = "Trueshot Lodge Hunter",
	MAWOFSOULS = "Утроба Душ",
	LEGIONUNCATEQUEST = "Legion Uncategorized Quests",
	RETURNTOKARAZHAN = "Возвращение в Каражан",
	MACAREE = "Mac'Aree",
	DREADSCARRIFT = "Разлом Зловещего Шрама",
	HELHEIM = "Хельхейм",
	EMERALDDREAMWAY = "Emerald Dreamway",
	BFA = "Battle For Azeroth",
	ZANDALAR = "Zandalar",
	KULTIRAS = "Kul Tiras",
	THUNDERTOTEM = "Thunder Totem",
	KINGSREST = "Гробница королей",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	PLAYERVSPLAYER = "Player Vs Player",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
	WORLDPVP = "World Pvp",
	NYALOTHATHEWALKINGCITY = "Ни'алота",
	VISIONSOFNZOTH = "Visions of N'Zoth",
	BLACKEMPIRECAMPAIGN = "Black Empire Campaign",
	-- Shadowlands Code
	SHADOWLANDS = "Shadowlands",
	COVENANTCALLINGS = "Covenant Callings",
	KYRIAN = "Kyrian",
	NECROLORD = "Necrolord",
	NIGHTFAE = "Night Fae",
	VENTHYR = "Venthyr",
	MAINZONES = "Основные зоны", -- Needs review
	OTHERCATEGORIES = "Другие категории", -- Needs review
	NINEONECAMPAIGN = "9.1 Campaign",
	ABOMINABLESTICHING = "Сшивание поганищ",
	COVENANTASSAULTS = "Covenant Assaults",
	COVENANTSANCTUARY = "Covenant Sanctuary",
	COVENANTSANCTUM = "Covenant Sanctum",
	EMBERCOURT = "Ember Court",
	KEEPERSRESPITE = "Приют хранителя",
	PATHOFASCENSION = "Path of Ascension",
	THEARCHIVISTSCODEX = "The Archivists' Codex",
	TORGHASTTOWEROFTHEDAMNED = "Торгаст, Башня Проклятых",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
	-- Dragonflight Code
	AZEROTHIANARCHIVES = "Azerothian Archives",
	AZMERLOTH = "Azmerloh",
	DRAGONISLE = "Dragon Isle",
	DRAGONFLIGHT = "Dragonflight",
	DRAGONSCALEEXPEDITION = "Dragonscale Expedition",
	DUNGEONS = "Dungeons",
	ISKAARATUSKARR = "Iskaara Tuskarr",
	MARUUKCENTAUR = "Maruuk Centaur",
	OBSIDIANCITADEL = "Обсидиановая цитадель", 
	RUBYLIFEPOOLS = "Рубиновые Омуты Жизни",
	VALDRAKKENACCORD = "Valdrakken Accord",
	--TWW
	TWW = "The War Within",
	AWAKENINGTHEMACHINE = "Пробуждение Машины",
	DEEPHAULRAVINE = "Золотоносная падь",	
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NERUBARPALACE = "Неруб'арский дворец",
	NORTHRENDCUP = "Northrend Cup",
	RAMBLESHIRE = "Путеземье",
	UPGRADESYSTEM = "Upgrade System",
	WARBANDS = "Warbands",
	DELVESHEADQUARTERS = "Штаб исследователей",
	DELVES = "Delves",
	TIMERUNNING = "Timerunning",
	THEHARBINGER = "The Harbinger",
	GILNEASRECLAMATION = "Gilneas Reclamation",
	LITTLESCALESDAYCARE = "Little Scales Daycare",
	TIMERIFT = "Time Rift",
	AMIRDRASIL = "Amirdrasil",
	AMIRDRASSILTHEDREAMSHOPE = "Амирдрассил, Надежда Сна",
	THEOASIS = "\"Оазис\"",
	--MID
	MIDNIGHT = "Midnight",
	FOUNDERSPOINT = "Лагерь Основателя",
	NEIGHBORHOOD = "Neighborhood",
	RAZORWINDSHORES = "Берега Колючего Ветра",
	SLAYERSRISE = "Зубец убийцы",
	WESTSANCTUM = "Западное святилище",	
	DEADMINES = "Мертвые копи",
	LOWERBLACKROCKSPIRE = "Нижняя часть пика Черной горы",
	THETEMPLEOFATALHAKKAR = "Храм Атал'Хаккар",
	THEBATTLEFORMOUNTHYJAL = "Битва за гору Хиджал",
	SEATOFTHETRIUMVIRATE = "Престол Триумвирата",
	TAZAVESHTHEVEILEDMARKET = "Тайный рынок Тазавеш",
	ASSAULTONVIOLETHOLD = "Штурм Аметистовой крепости",
	DIREMAULCAPITALGARDENS = "Забытый город – центральный сад",
	STRATHOLMEMAINGATE = "Стратхольм – главные врата",
	TEMPLEOFAHNQIRAJ = "Храм Ан'Киража",
	DIREMAULWARPWOODQUARTER = "Забытый город – квартал Криводревов",
	DIREMAULGORDOKCOMMONS = "Забытый город – палаты Гордока",
	STRATHOLMESERVICEENTRANCE = "Стратхольм – черный ход",
	WINDRUNNERSPIRE = "Шпили Ветрокрылых",
	MAGISTERSTERRACE = "Терраса Магистров",
	MURDERROW = "Закоулок душегубов",
	THEVOIDSPIRE = "Шпиль Бездны",
	THEBLINDINGVALE = "Слепящая долина",
	DENOFNALORAKK = "Берлога Налоракка",
	VOIDSCARARENA = "Арена Шрама Бездны",
	THEDREAMRIFT = "Провал снов",
	MAISARACAVERNS = "Пещеры Маисара",
	NEXUSPOINTXENAS = "Узел Нексуса Зенас",
	PROGRESS = "Выполнено %d/%d (%d%%)", -- Needs review
	SEARCHRESULTS = "Результаты поиска", -- Needs review
	SERVERQUERYRESULT = "Сервер сообщает о %d выполненных заданиях, известных Quest Completist; %d из них отмечены как выполненные впервые.", -- Needs review
	CACHECLEARED = "Кэш очищен.", -- Needs review
	CLEARINGCACHE = "Очистка кэша обновлений...", -- Needs review
	NODETAILS = "Игра не предоставила сведений о задании", -- Needs review
	QUESTID = "ID задания:", -- Needs review
	STORYLINE = "Цепочка заданий:", -- Needs review
	STORYLINEPOSITION = "(%d из %d)", -- Needs review
	EARLIERQUESTS = "... %d предыдущих", -- Needs review
	LATERQUESTS = "... ещё %d", -- Needs review
	THISQUEST = "это задание", -- Needs review
	UNKNOWNQUEST = "Неизвестное задание", -- Needs review
	REQUIREDQUEST = "Требуется задание:", -- Needs review
	UNKNOWNFACTION = "Неизвестная фракция", -- Needs review
	REQUIREDFACTION = "Требуемая фракция:", -- Needs review
	REQUIREDRENOWN = "Требуемый уровень известности:", -- Needs review
	REQUIREDRANK = "Требуемый ранг:", -- Needs review
	RANKLEVEL = "Ранг %d", -- Needs review
	DATAUNAVAILABLE = "Данные недоступны", -- Needs review
	QUESTGIVER = "Выдаёт задание:", -- Needs review
	UNKNOWNNPC = "Неизвестный НИП", -- Needs review
	NOQUESTGIVER = "Неизвестно, или задание принимается автоматически", -- Needs review
	REPAMOUNT = "%d репутации", -- Needs review
	NEWDATAINTRO = "Quest Completist не знал следующих сведений. Помогите сделать аддон точнее: сообщите о них на CurseForge.", -- Needs review
	NEWDATAQUEST = " - Этого задания нет в базе данных.", -- Needs review
	NEWDATAFACTION = " - QC не знал, что ваша ФРАКЦИЯ может выполнить это задание.", -- Needs review
	NEWDATARACE = " - QC не знал, что ваша РАСА может выполнить это задание.", -- Needs review
	NEWDATACLASS = " - QC не знал, что ваш КЛАСС может выполнить это задание.", -- Needs review
	NEWDATAALERT = "Найдены новые данные - сообщите нам!", -- Needs review
	BREADCRUMBAVAILABLE = "Доступно 1 вводное задание!", -- Needs review
	BREADCRUMBSAVAILABLE = "Доступно вводных заданий: %d!", -- Needs review
	BREADCRUMBQUESTS = "Вводные задания", -- Needs review
	MUTUALLYEXCLUSIVE = "Это задание исключает другие: можно выполнить только одно из них. Другие задания:", -- Needs review
	NOTINDATABASE = "Задания нет в базе данных", -- Needs review
	YOURSELF = "<Вы сами>", -- Needs review
	OTHERQUESTS = "Другие задания", -- Needs review
	PINDONE = "Выполнено: %d", -- Needs review
	PINSHOWDONE = "Shift — показать", -- Needs review
	PINWAYPOINT = "Щелкните, чтобы поставить точку TomTom", -- Needs review
	WELCOME = "Спасибо, что пользуетесь Quest Completist. Заметили ошибку в задании? Сообщите о ней на CurseForge.", -- Needs review
	UNAVAILABLEACCEPTED = "Задание %d «%s» отмечено как недоступное, но вы только что его взяли. Для вас оно показывается как обычно; сообщите об этом, чтобы список исправили.", -- Needs review
	UNAVAILABLETURNEDIN = "Задание %d «%s» отмечено как недоступное, но вы только что его сдали. Для вас оно показывается как обычно; сообщите об этом, чтобы список исправили.", -- Needs review
	TOGGLEFRAME = "Показать/скрыть окно", -- Needs review
	UNKNOWNZONE = "Неизвестная зона", -- Needs review
	}, {__index = qcLocalize})

end