if GetLocale() == "zhCN" then
qcLocalize = setmetatable({
	AHNQIRAJWAR = "安其拉战争",
	ASSAULTONTHEDARKPORTAL = "进攻黑暗之门",
	CAMPING = "露营",
	CENTRALKALIMDOR = "卡利姆多中部", -- Needs review
	CLASSES = "职业", -- Needs review
	CLASSQUESTS = "职业任务", -- Needs review
	CLEARUPDATECACHE = "清除更新缓存……", -- Needs review
	CONFIGSUBTITLE = "这些选项可以改变Quest Completist处理和过滤数据的方式。", -- Needs review
	CONFIGTITLE = "Quest Completist - 设置", -- Needs review
	CONTINENTS = "大陆", -- Needs review
	DAYOFTHEDEAD = "悼念日",
	DEATHRISING = "亡者崛起",
	ELEMENTALBONDS = "元素誓约",
	FIRELANDSINVASION = "进攻火焰之地",
	GARRISONCAMPAIGN = "要塞战役",
	GARRISONSUPPORT = "要塞支援",
	HIDECOMPLETEDQUESTS = "隐藏已完成的任务", -- Needs review
	HIDEDAILYQUEST = "隐藏日常任务", -- Needs review
	HIDEINPROGRESSQUESTS = "隐藏进行中的任务", -- Needs review
	HIDELOWLEVELQUESTS = "隐藏低等级任务", -- Needs review
	HIDENONACTIVESEASONALQUESTS = "隐藏未开启的节日任务", -- Needs review
	HIDEOTHERFACTIONQUESTS = "隐藏另一阵营的任务", -- Needs review
	HIDEOTHERPROFESSIONQUESTS = "隐藏其他专业的任务", -- Needs review
	HIDEOTHERRACEANDCLASSQUESTS = "隐藏其他种族和职业的任务", -- Needs review
	HIDEOTHERCOVENANTQUESTS = "隐藏其他盟约的任务", -- Needs review
	HIDEWARBANDS = "隐藏战团中其他角色已完成的任务", -- Needs review
	HIDEUNAVAILABLE = "隐藏已无法获取的任务", -- Needs review
	HIDEREQUIREMENTSNOTMET = "隐藏未满足条件的任务", -- Needs review
	HIDENODATA = "隐藏没有任务数据的标记", -- Needs review
	HIDEREPEATABLEQUEST = "隐藏可重复任务", -- Needs review
	HIDEWORLDQUEST = "隐藏世界任务和每周任务", -- Needs review
	INVASION = "天灾入侵",
	KHAZMODAN = "卡兹莫丹", -- Needs review
	LANDFALL = "登陆",
	LORDAERON = "洛丹伦", -- Needs review
	LUNARFESTIVAL = "新年",
	MIDSUMMER = "仲夏",
	NORTHERNKALIMDOR = "卡利姆多北部", -- Needs review
	PANDARENBREWMASTERS = "熊猫人酒仙",
	PANDARENCAMPAIGN = "熊猫人战役",
	PERFORMSERVERQUERY = "查询服务器……", -- Needs review
	QUERYREQUESTED = "已请求服务器查询……", -- Needs review
	QUESTLIST = "任务列表", -- Needs review
	QUESTSFOUND = "找到%d个任务", -- Needs review
	SEASONAL = "季节活动",
	SHOWMAPICONS = "显示地图图标", -- Needs review
	SKETTIS = "Skettis", -- Requires localization
	SORTALPHA = "排序：按字母", -- Needs review
	SORTLEVEL = "排序：按等级", -- Needs review
	SOUTHERNKALIMDOR = "卡利姆多南部", -- Needs review
	SPECIALS = "特殊", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "Stranglethorn Vale", -- Requires localization
	THEZANDALARI = "赞达拉",
	TOURNAMENT = "锦标赛",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "每周活动", -- Needs review
	WORLDEVENTS = "World Events", -- Requires localization
	MACAREE = "Mac'Aree",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	ALLIANCEWARCAMPAIGN = "联盟阵营战役",
	HORDEWARCAMPAIGN = "部落阵营战役",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	HERITAGE = "传承",
	RATEDPVP = "评级PvP",
	WORLDPVP = "世界PvP",
	BLACKEMPIRECAMPAIGN = "黑暗帝国战役",
	-- Shadowlands Code
	MAINZONES = "主要区域", -- Needs review
	OTHERCATEGORIES = "其他分类", -- Needs review
	COVENANTASSAULTS = "盟约突袭",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
	-- Dragonflight Code
	--TWW
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NORTHRENDCUP = "诺森德杯",
	UPGRADESYSTEM = "升级系统",
	WARBANDS = "战团",
	TIMERUNNING = "时空奔行",
	THEHARBINGER = "先驱",
	GILNEASRECLAMATION = "收复吉尔尼斯",
	TIMERIFT = "Time Rift",
	--MID
	NEIGHBORHOOD = "Neighborhood",
	PROGRESS = "%d/%d 已完成 (%d%%)", -- Needs review
	SERVERQUERYRESULT = "服务器报告了%d个Quest Completist已知的已完成任务，其中%d个是新标记为已完成的。", -- Needs review
	CACHECLEARED = "缓存已清除。", -- Needs review
	CLEARINGCACHE = "正在清除更新缓存……", -- Needs review
	NODETAILS = "游戏未提供任务详情", -- Needs review
	QUESTID = "任务ID：", -- Needs review
	STORYLINEPOSITION = "(%d/%d)", -- Needs review
	CAMPAIGNCHAPTER = "(第%d章，共%d章)", -- Needs review
	EARLIERQUESTS = "... 之前%d个", -- Needs review
	LATERQUESTS = "... 还有%d个", -- Needs review
	THISQUEST = "此任务", -- Needs review
	REQUIREDQUEST = "前置任务：", -- Needs review
	REQUIREDFACTION = "所需阵营：", -- Needs review
	REQUIREDRENOWN = "所需名望等级：", -- Needs review
	REQUIREDRANK = "所需声望等级：", -- Needs review
	REQUIREDSKILL = "所需技能：", -- Needs review
	RANKLEVEL = "等级 %d", -- Needs review
	QUESTGIVER = "任务提供者：", -- Needs review
	NOQUESTGIVER = "未知，或自动接受的任务", -- Needs review
	REPAMOUNT = "%d声望", -- Needs review
	NEWDATAINTRO = "Quest Completist之前不知道以下信息。请在CurseForge上反馈，帮助提高插件的准确性。", -- Needs review
	NEWDATAQUEST = " - 数据库中没有此任务。", -- Needs review
	NEWDATAFACTION = " - QC不知道你的阵营可以完成此任务。", -- Needs review
	NEWDATARACE = " - QC不知道你的种族可以完成此任务。", -- Needs review
	NEWDATACLASS = " - QC不知道你的职业可以完成此任务。", -- Needs review
	NEWDATAALERT = "发现新数据 - 请提交反馈！", -- Needs review
	BREADCRUMBAVAILABLE = "有1个引导任务可接！", -- Needs review
	BREADCRUMBSAVAILABLE = "有%d个引导任务可接！", -- Needs review
	BREADCRUMBQUESTS = "引导任务", -- Needs review
	MUTUALLYEXCLUSIVE = "此任务与其他任务互斥，你只能完成其中一个。其他任务为：", -- Needs review
	NOTINDATABASE = "数据库中没有此任务", -- Needs review
	YOURSELF = "<你自己>", -- Needs review
	OTHERQUESTS = "其他任务", -- Needs review
	PINDONE = "已完成 %d 个", -- Needs review
	PINSHOWDONE = "按住 Shift 显示", -- Needs review
	PINWAYPOINT = "点击设置 TomTom 路径点", -- Needs review
	WELCOME = "感谢使用Quest Completist。发现任务信息有误？请在CurseForge上反馈。", -- Needs review
	UNAVAILABLEACCEPTED = "任务%d“%s”被列为已无法获取，但你刚刚接受了它。它会对你正常显示；请反馈，以便修正列表。", -- Needs review
	UNAVAILABLETURNEDIN = "任务%d“%s”被列为已无法获取，但你刚刚交付了它。它会对你正常显示；请反馈，以便修正列表。", -- Needs review
	TOGGLEFRAME = "显示/隐藏窗口", -- Needs review
	SHOWMINIMAPBUTTON = "显示小地图按钮", -- Needs review
	MINIMAPLEFTCLICK = "左键点击：显示或隐藏任务列表", -- Needs review
	MINIMAPRIGHTCLICK = "右键点击：打开设置", -- Needs review
	MINIMAPDRAG = "拖动：沿小地图边缘移动此按钮", -- Needs review
	RECORDGIVERS = "记录我遇到的任务提供者", -- Needs review
	RECORDGIVERSTIP = "简要记录你遇到的任务提供者以及遇到他们的位置。仅保存在这台电脑上，不会发送到任何地方。/qc report 可查看已记录的内容。", -- Needs review
	RECORDERNOTICE = "Quest Completist 现在会简要记录你遇到的任务提供者及其所在位置，仅保存在这台电脑上。/qc report 可查看；/qc record off 可停止。", -- Needs review
	RECORDERSTATUS = "记录任务提供者：%s。可用 /qc record on、/qc record off 或 /qc record clear 更改。", -- Needs review
	RECORDERCOUNTS = "目前已记录 %d 个任务提供者、%d 个任务，以及 %d 个不由提供者开始的任务。", -- Needs review
	RECORDERFULL = "记录已满，新记录会替换最旧的记录（目前已替换 %d 条）。", -- Needs review
	RECORDERERRORS = "记录任务提供者时发生了 %d 个错误；最近一个：%s", -- Needs review
	RECORDERHIDDEN = "游戏有 %d 次隐藏了说话者；这些任务已在没有提供者的情况下记录。", -- Needs review
	RECORDERFILE = "不会发送到任何地方。游戏会在你登出或重载界面时，把记录保存到你账号 SavedVariables 文件夹（游戏的 WTF 文件夹中的 Account 下）里的 QuestCompletist.lua。若想帮助改进地图，请把该文件附在插件 CurseForge 页面的评论中。", -- Needs review
	RECORDERCLEARED = "记录已清除。", -- Needs review
	}, {__index = qcLocalize})

end