if GetLocale() == "frFR" then
qcLocalize = setmetatable({
	AHNQIRAJTHEFALLENKINGDOM = "Ahn’Qiraj : le royaume Déchu",
	ALCHEMY = "Alchimie",
	ARCHAEOLOGY = "Archéologie",
	ASSAULTONTHEDARKPORTAL = "Assaut sur la Porte des ténèbres",
	AZEROTH = "Azeroth",
	BARADINHOLD = "Bastion de Baradin",
	BATTLEGROUNDS = "Champs de bataille",
	BATTLEPETS = "Mascotte de combat",
	BLACKSMITHING = "Forge",
	BLACKWINGDESCENT = "Descente de l’Aile noire",
	BLACKWINGLAIR = "Repaire de l’Aile noire",
	BRAWLERSGUILD = "Guilde des Bastonneurs",
	BREWFEST = "Fête des Brasseurs",
	CAVERNSOFTIME = "Grottes du Temps",
	CENTRALKALIMDOR = "Centre de Kalimdor",
	CHILDRENSWEEK = "Semaine des enfants",
	CLASSES = "Classes",
	CLASSQUESTS = "Quêtes de classes",
	CLEARUPDATECACHE = "Effacer le cache des quêtes...",
	COILFANGRESERVOIR = "Réservoir de Glissecroc (Zone)",
	COMBINEDMAPANDQUESTFILTERS = "Carte du monde - Quest Completist liste des quêtes options combiné - Filtres",
	CONFIGSUBTITLE = "Ces options vous permettent de modifier la façon dont Quests Completist gère et filtre les données.",
	CONFIGTITLE = "Quest Completist - Configuration",
	CONTINENTS = "Continents",
	COOKING = "Cuisine",
	DARKMOONFAIRE = "Foire de Sombrelune",
	DAYOFTHEDEAD = "Jour des morts",
	DEATHKNIGHT = "Chevalier de la mort",
	DRAENOR = "Draenor",
	DRAGONSOUL = "L’Âme des dragons",
	DRUID = "Druide",
	DUNGEONSANDRAIDS = "Donjons & Raids",
	EASTERNKINGDOMS = "Royaumes de l'est",
	ELEMENTALBONDS = "Liens élémentaires",
	ENCHANTING = "Enchantement",
	ENGINEERING = "Ingénierie",
	FIRELANDS = "Terres de Feu",
	FIRELANDSINVASION = "Invasion des terres de Feu",
	FIRSTAID = "Secourisme",
	FISHING = "Pêche",
	GARRISONCAMPAIGN = "Campagne de Fief",
	GARRISONSUPPORT = "Support de Fief",
	GREENSTONEVILLAGE = "Pierre-Verte",
	GRUULSLAIR = "Repaire de Gruul",
	HALLOWSEND = "Sanssaint",
	HARVESTFESTIVAL = "Fête des moissons",
	HELLFIRECITADEL = "Citadelle des Flammes infernales",
	HERBALISM = "Herboristerie",
	HIDECOMPLETEDQUESTS = "Cacher les quêtes achevées",
	HIDEDAILYQUEST = "Cacher les quêtes journalières", -- Needs review
	HIDEINPROGRESSQUESTS = "Cacher les quêtes en cours",
	HIDELOWLEVELQUESTS = "Cacher les quêtes de bas niveau",
	HIDENONACTIVESEASONALQUESTS = "Cacher les quêtes saisonnière non disponible",
	HIDENORMALQUEST = "Hide Normal Quests",
	HIDEOTHERFACTIONQUESTS = "Cacher les quêtes des autres factions",
	HIDEOTHERPROFESSIONQUESTS = "Cacher les quêtes des autres métiers",
	HIDEOTHERRACEANDCLASSQUESTS = "Cacher les quêtes des autres classe / races                                                  |cff1784d1Translated by: Deadse-Voljin EU|r",
	HIDEOTHERCOVENANTQUESTS = "Cacher les quêtes des autres congrégations", -- Needs review
	HIDEWARBANDS = "Cacher les quêtes faites par d'autres personnages du bataillon", -- Needs review
	HIDEUNAVAILABLE = "Cacher les quêtes qui ne sont plus disponibles", -- Needs review
	HIDEREQUIREMENTSNOTMET = "Cacher les quêtes aux conditions non remplies", -- Needs review
	HIDENODATA = "Cacher les marqueurs sans données de quête", -- Needs review
	HIDEREPEATABLEQUEST = "Cacher les quêtes répétables", -- Needs review
	HIDEWEEKLYQUEST = "Hide Weekly Quests",
	HIDEWORLDQUEST = "Cacher les expéditions", -- Needs review
	HUNTER = "Chasseur",
	INSCRIPTION = "Calligraphie",
	ISLEOFGIANTS = "Île des Géants",
	JADETEMPLEGROUNDS = "Jade Temple Grounds", -- Requires localization
	JEWELCRAFTING = "Joaillerie",
	KALIMDOR = "Kalimdor",
	KHAZMODAN = "Khaz Modan",
	LANDFALL = "Accostage",
	LEATHERWORKING = "Travail du cuir",
	LEGENDARY = "Légendaire ",
	LORDAERON = "Lordaeron",
	LOVEISINTHEAIR = "De l'amour dans l'air",
	LUNARFESTIVAL = "Fête lunaire",
	MAGE = "Mage",
	MAPFILTERS = "Carte du monde - Filtres",
	MIDSUMMERFIREFESTIVAL = "Fête du Feu du solstice d'été",
	MINING = "Minage",
	MISCELLANEOUS = "Divers",
	MOGUSHANVAULTS = "Caveaux Mogu’shan",
	MONK = "Moine",
	NAGRAND = "Nagrand",
	NEWYEARSEVE = "Nouvel an",
	NOBLEGARDEN = "Le Jardin des nobles",
	NORTHERNKALIMDOR = "Nord de Kalimdor",
	NORTHREND = "Norfendre",
	ONYXIASLAIR = "Repaire d’Onyxia",
	OPTIONS = "Options",
	OUTLAND = "Outreterre",
	PALACEOFTHEHEAVENS = "Palace of the Heavens",
	PALADIN = "Paladin",
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Campagne Pandaren",
	PANDARIA = "Pandarie",
	PEAKOFSERENITY = "Peak of Serenity", -- Requires localization
	PERFORMSERVERQUERY = "Effectuer une requête serveur...",
	PILGRIMSBOUNTY = "Les Bienfaits du pèlerin",
	PRIEST = "Prêtre",
	PROFESSIONS = "Métiers",
	QUERYREQUESTED = "Une requête serveur a été demandé...",
	QUESTLISTFILTERS = "Quest Completist liste des quêtes - Filtres",
	QUESTSFOUND = "%d quêtes trouvées", -- Needs review
	RAIDS = "Raids",
	REGIONS = "Régions",
	RIDING = "Riding", -- Requires localization
	ROGUE = "Voleur",
	RUINSOFGILNEASCITY = "Ruines de Gilnéas (Ville)",
	SCENARIO = "Scenario", -- Requires localization
	SEASONAL = "Saisonnier",
	SERPENTSHRINECAVERN = "Caverne du sanctuaire du Serpent",
	SHADOWMOONVALLEY = "Vallée d’Ombrelune",
	SHAMAN = "Chaman",
	SHOWMAPICONS = "Afficher les points d'exclamations sur la carte du monde",
	SKETTIS = "Skettis", -- Requires localization
	SKINNING = "Dépeçage",
	SORTALPHA = "Trier par: Ordre alphabétique",
	SORTLEVEL = "Trier par: Niveau",
	SOUTHERNKALIMDOR = "Sud de Kalimdor",
	SPECIAL = "Spécial",
	SPECIALS = "Spécials",
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "Vallée de Strangleronce",
	TAILORING = "Couture",
	TEMPLEOFTHEREDCRANE = "Temple of the Red Crane",
	THEARBORETUM = "The Arboretum", -- Requires localization
	THEBASTIONOFTWILIGHT = "Le bastion du Crépuscule",
	THEBLACKMORASS = "Le Noir marécage",
	THEEVERBLOOM = "La Flore éternelle",
	THEEYE = "L’Œil",
	THEGATEOFTHESETTINGSUN = "The Gate of the Setting Sun",
	THEHALFHILLMARKET = "Micolline, Vallée des Quatre vents",
	THEMAELSTROM = "Le Maelström",
	THEOBSIDIANSANCTUM = "Le sanctum Obsidien",
	THETEMPLEOFTHEJADESERPENT = "The Temple of the Jade Serpent",
	THEVIOLETHOLD = "Le Fort Pourpre",
	THEZANDALARI = "Les zandalari",
	THRONEOFTHEFOURWINDS = "Trône des Quatre Vents",
	TOURNAMENT = "Tournoi",
	UPPERBLACKROCKSPIRE = "Sommet du pic Rochenoire",
	UNCATEGORIZED = "Non classé", -- Needs review
	VASHJIR = "Vashj’ir",
	VAULTOFARCHAVON = "Caveau d’Archavon",
	WARLOCK = "Démoniste",
	WARRIOR = "Guerrier",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "Évènements hebdomadaires", -- Needs review
	WINTERVEIL = "Voile d'hiver",
	WORLDEVENTS = "Évènements mondiaux",
	THEBROKENISLES = "Iles Brisees",
	THEDREAMGROVE = "La Sylverêve",
	DEMONHUNTER = "Chasseur de démons",
	CONTESTCOMMING = "Contest comming shows wrong zone",
	HALLOFTHEGUARDIAN = "Hall du Gardien",
	MARDUMTHESHATTEREDABYSS = "Mardum, the Shattered Abyss",
	NETHERLIGHTTEMPLE = "Temple Halo-du-Néant",
	SKYHOLD = "Séjour céleste",
	THEHEARTOFAZERTH = "The Heart of Azeroth",
	THEWANDERINGISLE = "The Wandering Isle Monk",
	TRUESHOTLODGE = "Trueshot Lodge Hunter",
	MAWOFSOULS = "La Gueule des âmes",
	LEGIONUNCATEQUEST = "Legion Uncategorized Quests",
	RETURNTOKARAZHAN = "Retour à Karazhan",
	MACAREE = "Mac'Aree",
	DREADSCARRIFT = "Faille de Scareffroi",
	HELHEIM = "Helheim",
	EMERALDDREAMWAY = "Emerald Dreamway",
	BFA = "Battle For Azeroth",
	ZANDALAR = "Zandalar",
	KULTIRAS = "Kul Tiras",
	THUNDERTOTEM = "Thunder Totem",
	KINGSREST = "Repos des rois",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	THRUNDERROT = "The Underrot",
	THEDEATHOFCHROMIE = "The Deaths Of Chromie",
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	THEDRAGONSSPINE = "The Dragon`s Spine",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	TERRACEOFENLESSSPRINGS = "Terrasse Printanière",
	PLAYERVSPLAYER = "Player Vs Player",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
	WORLDPVP = "World Pvp",
	NYALOTHATHEWALKINGCITY = "Ny’alotha, la cité en éveil",
	VISIONSOFNZOTH = "Visions of N'Zoth",
	BLACKEMPIRECAMPAIGN = "Black Empire Campaign",
	WORLDQUEST = "World Quests",
	-- Shadowlands Code
	SHADOWLANDS = "Shadowlands",
	SHADOWLANDSUNCATEQUEST = "Shadowlands Uncategorized Quests",
	COVENANTCALLINGS = "Covenant Callings",
	KYRIAN = "Kyrian",
	NECROLORD = "Necrolord",
	NIGHTFAE = "Night Fae",
	VENTHYR = "Venthyr",
	MAINZONES = "Zones principales", -- Needs review
	OTHERCATEGORIES = "Autres catégories", -- Needs review
	NINEONECAMPAIGN = "9.1 Campaign",
	ABOMINABLESTICHING = "Suture abominable",
	COVENANTASSAULTS = "Covenant Assaults",
	COVENANTSANCTUARY = "Covenant Sanctuary",
	COVENANTSANCTUM = "Covenant Sanctum",
	EMBERCOURT = "Ember Court",
	KEEPERSRESPITE = "Répit du gardien",
	PATHOFASCENSION = "Path of Ascension",
	THEARCHIVISTSCODEX = "The Archivists' Codex",
	TORGHASTTOWEROFTHEDAMNED = "Tourment, la tour des Damnés",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
	AZEROTHIANARCHIVES = "Azerothian Archives",
	AZMERLOTH = "Azmerloh",
	BRACKENHIDEWATERHOLE = "Brackenhide Waterhole",
	DRAGONISLE = "Dragon Isle",
	DRAGONFLIGHT = "Dragonflight",
	DRAGONSCALEBASECAMP = "Dragonscale Basecamp",
	DRAGONSCALEEXPEDITION = "Dragonscale Expedition",
	DUNGEONS = "Dungeons",
	EMERALDARDENS = "Emerald Gardens",
	HORNSWOGHOLLOW = "Hornswog Hollow",
	ISKAARATUSKARR = "Iskaara Tuskarr",
	LOSTRUINS = "Lost Ruins",
	MARUUKCENTAUR = "Maruuk Centaur",
	OBSIDIANCITADEL = "Citadelle d’Obsidienne", 
	PASSAGEOFTIME = "Passage du Temps",
	PRIMALISTSTORMS = "Primalist Storms",
	PRIMORDIALALE = "Primordial Vale",
	RUBYLIFEPOOLS = "Bassins de l’Essence rubis",
	RUBYLIFESHRINE = "Ruby Lifeshrine",
	SHADOWLEDGE = "Shadow Legde",
	TEMPESTUNLEASHED = "Tempest Unleashed",
	THEPRIMAISTFUTURE = "The Primalist Future",
	THERONSWATCH = "Theron`s Watch",
	VALDRAKKENACCORD = "Valdrakken Accord",
	KORRAKSREVENGE = "Korrak`s Revenge",
	--TWW
	TWW = "The War Within",
	AWAKENINGTHEMACHINE = "L’éveil de la machine",
	DEEPHAULRAVINE = "Ravin d’Abondabîme",	
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NERUBARPALACE = "Palais des Nérub’ar",
	NORTHRENDCUP = "Northrend Cup",
	RAMBLESHIRE = "Randonneraie",
	UPGRADESYSTEM = "Upgrade System",
	WARBANDS = "Warbands",
	ARATHIHIGHLANDSTWW = "Arathi Highlands TWW",
	DELVESHEADQUARTERS = "Quartier général des archéologues",
	DELVES = "Delves",
	THERAMORESFALLS = "Theramore`s  Fall",
	TIMERUNNING = "Timerunning",
	THEHARBINGER = "The Harbinger",
	GILNEASRECLAMATION = "Gilneas Reclamation",
	LITTLESCALESDAYCARE = "Little Scales Daycare",
	TIMERIFT = "Time Rift",
	AMIRDRASIL = "Amirdrasil",
	AMIRDRASSILTHEDREAMSHOPE = "Amirdrassil, l’Espoir du Rêve",
	THEOASIS = "L’Oasis",
	--MID
	MIDNIGHT = "Midnight",
	FOUNDERSPOINT = "Cap Fondateur",
	NEIGHBORHOOD = "Neighborhood",
	RAZORWINDSHORES = "Rivages de Tranchevent",
	SLAYERSRISE = "Colline Meurtrière",
	WESTSANCTUM = "Sanctum Occidental",	
	DEADMINES = "Les Mortemines",
	LOWERBLACKROCKSPIRE = "Bas du pic Rochenoire",
	THETEMPLEOFATALHAKKAR = "Le temple d’Atal’Hakkar",
	THEBATTLEFORMOUNTHYJAL = "La bataille du mont Hyjal",
	SEATOFTHETRIUMVIRATE = "Siège du triumvirat",
	TAZAVESHTHEVEILEDMARKET = "Tazavesh, le marché dissimulé",
	ASSAULTONVIOLETHOLD = "Assaut sur le fort Pourpre",
	DIREMAULCAPITALGARDENS = "Hache-Tripes – Grands jardins",
	STRATHOLMEMAINGATE = "Stratholme – Grande porte",
	TEMPLEOFAHNQIRAJ = "Temple d’Ahn’Qiraj",
	DIREMAULWARPWOODQUARTER = "Hache-Tripes – Quartier de Crochebois",
	DIREMAULGORDOKCOMMONS = "Hache-Tripes – Communs gordok",
	STRATHOLMESERVICEENTRANCE = "Stratholme – Entrée de service",
	WINDRUNNERSPIRE = "Flèche de Coursevent",
	MAGISTERSTERRACE = "Terrasse des Magistères",
	MURDERROW = "L’Allée du meurtre",
	THEVOIDSPIRE = "Flèche du Vide",
	THEBLINDINGVALE = "Le val Aveuglant",
	DENOFNALORAKK = "Antre de Nalorakk",
	VOIDSCARARENA = "Arène de la Cicatrice du Vide",
	THEDREAMRIFT = "Faille du Rêve",
	MAISARACAVERNS = "Cavernes de Maisara",
	NEXUSPOINTXENAS = "Point-nexus Xenas",
	PROGRESS = "%d/%d terminées (%d%%)", -- Needs review
	SEARCHRESULTS = "Résultats de la recherche", -- Needs review
	SERVERQUERYRESULT = "Le serveur signale %d quêtes terminées connues de Quest Completist, dont %d nouvellement marquées comme terminées.", -- Needs review
	CACHECLEARED = "Cache vidé.", -- Needs review
	CLEARINGCACHE = "Vidage de votre cache de mise à jour...", -- Needs review
	NODETAILS = "Le jeu ne fournit pas les détails de la quête", -- Needs review
	QUESTID = "ID de quête :", -- Needs review
	STORYLINE = "Suite de quêtes :", -- Needs review
	STORYLINEPOSITION = "(%d sur %d)", -- Needs review
	EARLIERQUESTS = "... %d précédentes", -- Needs review
	LATERQUESTS = "... %d de plus", -- Needs review
	THISQUEST = "cette quête", -- Needs review
	UNKNOWNQUEST = "Quête inconnue", -- Needs review
	REQUIREDQUEST = "Quête requise :", -- Needs review
	UNKNOWNFACTION = "Faction inconnue", -- Needs review
	REQUIREDFACTION = "Faction requise :", -- Needs review
	REQUIREDRENOWN = "Niveau de renom requis :", -- Needs review
	REQUIREDRANK = "Rang requis :", -- Needs review
	RANKLEVEL = "Rang %d", -- Needs review
	DATAUNAVAILABLE = "Données indisponibles", -- Needs review
	QUESTGIVER = "Donneur de quête :", -- Needs review
	UNKNOWNNPC = "PNJ inconnu", -- Needs review
	NOQUESTGIVER = "Inconnu, ou quête acceptée automatiquement", -- Needs review
	REPAMOUNT = "%d de réputation", -- Needs review
	NEWDATAINTRO = "Quest Completist ignorait les informations suivantes. Aidez à améliorer la précision de l'addon en les signalant sur CurseForge.", -- Needs review
	NEWDATAQUEST = " - La quête n'existe pas dans la base de données.", -- Needs review
	NEWDATAFACTION = " - QC ignorait que votre FACTION pouvait terminer cette quête.", -- Needs review
	NEWDATARACE = " - QC ignorait que votre RACE pouvait terminer cette quête.", -- Needs review
	NEWDATACLASS = " - QC ignorait que votre CLASSE pouvait terminer cette quête.", -- Needs review
	NEWDATAALERT = "Nouvelles données trouvées - contribuez !", -- Needs review
	BREADCRUMBAVAILABLE = "1 quête d'introduction disponible !", -- Needs review
	BREADCRUMBSAVAILABLE = "%d quêtes d'introduction disponibles !", -- Needs review
	BREADCRUMBQUESTS = "Quêtes d'introduction", -- Needs review
	MUTUALLYEXCLUSIVE = "Cette quête en exclut d'autres : vous ne pouvez en terminer qu'une seule. Les autres quêtes sont :", -- Needs review
	NOTINDATABASE = "Quête absente de la base de données", -- Needs review
	YOURSELF = "<Vous-même>", -- Needs review
	OTHERQUESTS = "Autres quêtes", -- Needs review
	PINDONE = "%d terminées", -- Needs review
	PINSHOWDONE = "Maj pour afficher", -- Needs review
	PINWAYPOINT = "Cliquez pour placer un point de passage TomTom", -- Needs review
	WELCOME = "Merci d'utiliser Quest Completist. Vous avez repéré une erreur sur une quête ? Signalez-la sur CurseForge.", -- Needs review
	UNAVAILABLEACCEPTED = "La quête %d « %s » est indiquée comme n'étant plus disponible, mais vous venez de l'accepter. Elle s'affiche normalement pour vous ; signalez-le pour que la liste soit corrigée.", -- Needs review
	UNAVAILABLETURNEDIN = "La quête %d « %s » est indiquée comme n'étant plus disponible, mais vous venez de la rendre. Elle s'affiche normalement pour vous ; signalez-le pour que la liste soit corrigée.", -- Needs review
	TOGGLEFRAME = "Afficher/masquer la fenêtre", -- Needs review
	UNKNOWNZONE = "Zone inconnue", -- Needs review
	}, {__index = qcLocalize})

end