if GetLocale() == "ptBR" then
qcLocalize = setmetatable({
	AHNQIRAJWAR = "Guerra de Ahn'Qiraj",
	ASSAULTONTHEDARKPORTAL = "Assault on the Dark Portal", -- Requires localization
	CAMPING = "Acampamento",
	CENTRALKALIMDOR = "Kalimdor Central", -- Needs review
	CLASSES = "Classes",
	CLASSQUESTS = "Missões de Classe",
	CLEARUPDATECACHE = "Limpar o cache de atualizações...",
	CONFIGSUBTITLE = "Essas opções permitem mudar o jeito que o Quest Completist manipula e filtra os dados.",
	CONFIGTITLE = "Quest Completist - Configuração",
	CONTINENTS = "Continentes",
	DAYOFTHEDEAD = "Dia dos Mortos",
	ELEMENTALBONDS = "Prisão elemental",
	FIRELANDSINVASION = "Invasão às Terras do Fogo",
	GARRISONCAMPAIGN = "Garrison Campaign", -- Requires localization
	GARRISONSUPPORT = "Garrison Support", -- Requires localization
	HIDECOMPLETEDQUESTS = "Ocultar as missões completadas",
	HIDEDAILYQUEST = "Ocultar missões diárias", -- Needs review
	HIDEINPROGRESSQUESTS = "Ocultar missões em andamento",
	HIDELOWLEVELQUESTS = "Ocultar missões de nível baixo",
	HIDENONACTIVESEASONALQUESTS = "Ocultar Missões de Eventos Mundiais não ativas",
	HIDEOTHERFACTIONQUESTS = "Ocultar missões de outra facção",
	HIDEOTHERPROFESSIONQUESTS = "Ocultar missões de outra profissão",
	HIDEOTHERCOVENANTQUESTS = "Ocultar missões de outros pactos", -- Needs review
	HIDEWARBANDS = "Ocultar missões feitas por outros personagens do bando de guerra", -- Needs review
	HIDEUNAVAILABLE = "Ocultar missões que não estão mais disponíveis", -- Needs review
	HIDEREQUIREMENTSNOTMET = "Ocultar missões com requisitos não cumpridos", -- Needs review
	HIDENODATA = "Ocultar marcadores sem dados de missão", -- Needs review
	HIDEREPEATABLEQUEST = "Ocultar missões repetíveis", -- Needs review
	HIDEWORLDQUEST = "Ocultar missões mundiais e semanais", -- Needs review
	INVASION = "Invasão",
	HIDEOTHERRACEANDCLASSQUESTS = "Ocultar missões de outra raça e classe",
	KHAZMODAN = "Khaz Modan", -- Requires localization
	LANDFALL = "Landfall", -- Requires localization
	LORDAERON = "Lordaeron", -- Requires localization
	LUNARFESTIVAL = "Festival da Lua",
	MIDSUMMER = "Solstício",
	NORTHERNKALIMDOR = "Kalimdor do Norte", -- Needs review
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Pandaren Campaign", -- Requires localization
	PERFORMSERVERQUERY = "Consultar o servidor...",
	QUERYREQUESTED = "Foi feita uma consulta ao servidor...",
	QUESTLIST = "Lista de Missões", -- Needs review
	QUESTSFOUND = "%d missões encontradas",
	SEASONAL = "Sazonal",
	SHOWMAPICONS = "Mostrar ícones no mapa",
	SKETTIS = "Skettis", -- Requires localization
	SORTALPHA = "Classificar: Alfabeticamente",
	SORTLEVEL = "Classificar: Nível",
	SOUTHERNKALIMDOR = "Kalimdor do Sul", -- Needs review
	SPECIALS = "Especiais",
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "Selva do Espinhaço",
	THEZANDALARI = "os Zandalári",
	TOURNAMENT = "Torneio",
	TREASUREMAP = "Mapa do Tesouro",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "Eventos semanais", -- Needs review
	WORLDEVENTS = "Eventos Mundiais",
	MACAREE = "Mac'Aree",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
	WORLDPVP = "World Pvp",
	BLACKEMPIRECAMPAIGN = "Black Empire Campaign",
		-- Shadowlands Code
	-- Shadowlands Code
	MAINZONES = "Zonas principais", -- Needs review
	OTHERCATEGORIES = "Outras categorias", -- Needs review
	COVENANTASSAULTS = "Covenant Assaults",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
	--TWW
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NORTHRENDCUP = "Northrend Cup",
	UPGRADESYSTEM = "Upgrade System",
	WARBANDS = "Warbands",
	TIMERUNNING = "Timerunning",
	THEHARBINGER = "The Harbinger",
	GILNEASRECLAMATION = "Gilneas Reclamation",
	TIMERIFT = "Time Rift",
	--MID
	NEIGHBORHOOD = "Neighborhood",
	PROGRESS = "%d/%d concluídas (%d%%)", -- Needs review
	SERVERQUERYRESULT = "O servidor informa %d missões concluídas que o Quest Completist conhece, %d delas marcadas como concluídas agora.", -- Needs review
	CACHECLEARED = "Cache limpo.", -- Needs review
	CLEARINGCACHE = "Limpando seu cache de atualização...", -- Needs review
	NODETAILS = "O jogo não fornece os detalhes da missão", -- Needs review
	QUESTID = "ID da missão:", -- Needs review
	STORYLINEPOSITION = "(%d de %d)", -- Needs review
	EARLIERQUESTS = "... %d anteriores", -- Needs review
	LATERQUESTS = "... mais %d", -- Needs review
	THISQUEST = "esta missão", -- Needs review
	REQUIREDQUEST = "Missão necessária:", -- Needs review
	REQUIREDFACTION = "Facção necessária:", -- Needs review
	REQUIREDRENOWN = "Nível de renome necessário:", -- Needs review
	REQUIREDRANK = "Grau necessário:", -- Needs review
	REQUIREDSKILL = "Habilidade necessária:", -- Needs review
	RANKLEVEL = "Grau %d", -- Needs review
	QUESTGIVER = "Oferecida por:", -- Needs review
	NOQUESTGIVER = "Desconhecido, ou missão aceita automaticamente", -- Needs review
	REPAMOUNT = "%d de reputação", -- Needs review
	NEWDATAINTRO = "O Quest Completist não conhecia as informações a seguir. Ajude a melhorar a precisão do addon publicando-as no CurseForge.", -- Needs review
	NEWDATAQUEST = " - A missão não existe no banco de dados.", -- Needs review
	NEWDATAFACTION = " - O QC não sabia que sua FACÇÃO podia concluir esta missão.", -- Needs review
	NEWDATARACE = " - O QC não sabia que sua RAÇA podia concluir esta missão.", -- Needs review
	NEWDATACLASS = " - O QC não sabia que sua CLASSE podia concluir esta missão.", -- Needs review
	NEWDATAALERT = "Novos dados encontrados - contribua!", -- Needs review
	BREADCRUMBAVAILABLE = "1 missão introdutória disponível!", -- Needs review
	BREADCRUMBSAVAILABLE = "%d missões introdutórias disponíveis!", -- Needs review
	BREADCRUMBQUESTS = "Missões introdutórias", -- Needs review
	MUTUALLYEXCLUSIVE = "Esta missão exclui outras: você só pode concluir uma delas. As outras missões são:", -- Needs review
	NOTINDATABASE = "Missão fora do banco de dados", -- Needs review
	YOURSELF = "<Você mesmo>", -- Needs review
	OTHERQUESTS = "Outras missões", -- Needs review
	PINDONE = "%d concluídas", -- Needs review
	PINSHOWDONE = "Shift para mostrar", -- Needs review
	PINWAYPOINT = "Clique para definir um waypoint do TomTom", -- Needs review
	WELCOME = "Obrigado por usar o Quest Completist. Encontrou um erro em uma missão? Informe no CurseForge.", -- Needs review
	UNAVAILABLEACCEPTED = "A missão %d \"%s\" consta como não mais disponível, mas você acabou de aceitá-la. Ela aparece normalmente para você; informe para que a lista seja corrigida.", -- Needs review
	UNAVAILABLETURNEDIN = "A missão %d \"%s\" consta como não mais disponível, mas você acabou de entregá-la. Ela aparece normalmente para você; informe para que a lista seja corrigida.", -- Needs review
	TOGGLEFRAME = "Mostrar/ocultar janela", -- Needs review
	}, {__index = qcLocalize})

end