if GetLocale() == "koKR" then
qcLocalize = setmetatable({
	AHNQIRAJWAR = "안퀴라즈 전쟁",
	ASSAULTONTHEDARKPORTAL = "어둠의 문 공격 작전",
	CAMPING = "야영",
	CENTRALKALIMDOR = "중부 칼림도어", -- Needs review
	CLASSES = "직업", -- Needs review
	CLASSQUESTS = "직업 퀘스트", -- Needs review
	CLEARUPDATECACHE = "업데이트 캐쉬 초기화", -- Needs review
	CONFIGSUBTITLE = "Quest Completist에서 항목 분류를 통해서 원하는 정보를 빠르게 볼 수 있습니다.", -- Needs review
	CONFIGTITLE = "Quest Completist - 설정", -- Needs review
	CONTINENTS = "대륙", -- Needs review
	DAYOFTHEDEAD = "망자의 날",
	DEATHRISING = "엄습하는 죽음",
	ELEMENTALBONDS = "정령의 속박",
	FIRELANDSINVASION = "불의 땅 침공",
	GARRISONCAMPAIGN = "주둔지 대장정",
	GARRISONSUPPORT = "주둔지 지원",
	HIDECOMPLETEDQUESTS = "완료된 퀘스트 숨김", -- Needs review
	HIDEDAILYQUEST = "일일 퀘스트 숨김", -- Needs review
	HIDEINPROGRESSQUESTS = "진행중인 퀘스트 숨김", -- Needs review
	HIDELOWLEVELQUESTS = "저레벨 퀘스트 숨김", -- Needs review
	HIDENONACTIVESEASONALQUESTS = "진행중이지 않은 계절 축제 퀘스트 숨김", -- Needs review
	HIDEOTHERFACTIONQUESTS = "상대진영 퀘스트 숨김", -- Needs review
	HIDEOTHERPROFESSIONQUESTS = "다른 전문기술 퀘스트 숨김", -- Needs review
	HIDEOTHERRACEANDCLASSQUESTS = "다른 종족 및 직업 퀘스트 숨김", -- Needs review
	HIDEOTHERCOVENANTQUESTS = "다른 성약의 단 퀘스트 숨김", -- Needs review
	HIDEWARBANDS = "전투부대의 다른 캐릭터가 완료한 퀘스트 숨김", -- Needs review
	HIDEUNAVAILABLE = "더 이상 받을 수 없는 퀘스트 숨김", -- Needs review
	HIDEREQUIREMENTSNOTMET = "조건을 충족하지 못한 퀘스트 숨김", -- Needs review
	HIDENODATA = "퀘스트 정보가 없는 표시 숨김", -- Needs review
	HIDEREPEATABLEQUEST = "반복 퀘스트 숨김", -- Needs review
	HIDEWORLDQUEST = "전역 퀘스트 및 주간 퀘스트 숨김", -- Needs review
	INVASION = "침공",
	KHAZMODAN = "카즈 모단", -- Needs review
	LANDFALL = "상륙지",
	LORDAERON = "로데론", -- Needs review
	LUNARFESTIVAL = "설날",
	MIDSUMMER = "한여름 불꽃축제",
	NORTHERNKALIMDOR = "북부 칼림도어", -- Needs review
	PANDARENBREWMASTERS = "판다렌 양조사",
	PANDARENCAMPAIGN = "판다리아 대장정",
	PERFORMSERVERQUERY = "서버 질의를 진행합니다...", -- Needs review
	QUERYREQUESTED = "서버 질의에 응답했습니다...", -- Needs review
	QUESTLIST = "퀘스트 목록", -- Needs review
	QUESTSFOUND = "%d 퀘스트 찾음", -- Needs review
	SEASONAL = "이벤트",
	SHOWMAPICONS = "지도 아이콘 표시", -- Needs review
	SKETTIS = "Skettis", -- Requires localization
	SORTALPHA = "정렬 : 가나다 순", -- Needs review
	SORTLEVEL = "정렬 : 레벨 순", -- Needs review
	SOUTHERNKALIMDOR = "남부 칼림도어", -- Needs review
	SPECIALS = "특수", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "가시덤불 골짜기",
	THEZANDALARI = "잔달라 부족",
	TOURNAMENT = "마상시합",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "주간 이벤트", -- Needs review
	WORLDEVENTS = "월드 이벤트", -- Needs review
	MACAREE = "Mac'Aree",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	ALLIANCEWARCAMPAIGN = "얼라이언스 전쟁 대장정",
	HORDEWARCAMPAIGN = "호드 전쟁 대장정",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	HERITAGE = "유산",
	RATEDPVP = "평점제 플레이어 간 전투",
	WORLDPVP = "야외 플레이어 간 전투",
	BLACKEMPIRECAMPAIGN = "검은 제국 대장정",
		-- Shadowlands Code
	-- Shadowlands Code
	MAINZONES = "주요 지역", -- Needs review
	OTHERCATEGORIES = "기타 분류", -- Needs review
	COVENANTASSAULTS = "성약의 단 습격",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
	--TWW
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NORTHRENDCUP = "노스렌드 우승컵",
	UPGRADESYSTEM = "강화 시스템",
	WARBANDS = "전투부대",
	TIMERUNNING = "시간질주",
	THEHARBINGER = "전령",
	GILNEASRECLAMATION = "길니아스 탈환",
	TIMERIFT = "Time Rift",
	--MID
	NEIGHBORHOOD = "Neighborhood",
	PROGRESS = "%d/%d 완료 (%d%%)", -- Needs review
	SERVERQUERYRESULT = "서버에 Quest Completist가 아는 완료한 퀘스트가 %d개 있으며, 그중 %d개를 새로 완료로 표시했습니다.", -- Needs review
	CACHECLEARED = "캐시를 비웠습니다.", -- Needs review
	CLEARINGCACHE = "업데이트 캐시를 비우는 중...", -- Needs review
	NODETAILS = "게임에서 퀘스트 정보를 받지 못했습니다", -- Needs review
	QUESTID = "퀘스트 ID:", -- Needs review
	STORYLINEPOSITION = "(%d/%d)", -- Needs review
	CAMPAIGNCHAPTER = "(%d/%d장)", -- Needs review
	EARLIERQUESTS = "... 이전 %d개", -- Needs review
	LATERQUESTS = "... %d개 더", -- Needs review
	THISQUEST = "이 퀘스트", -- Needs review
	REQUIREDQUEST = "필요 퀘스트:", -- Needs review
	REQUIREDFACTION = "필요 세력:", -- Needs review
	REQUIREDRENOWN = "필요 명성 레벨:", -- Needs review
	REQUIREDRANK = "필요 등급:", -- Needs review
	REQUIREDSKILL = "필요 기술:", -- Needs review
	RANKLEVEL = "%d등급", -- Needs review
	QUESTGIVER = "퀘스트 제공자:", -- Needs review
	NOQUESTGIVER = "알 수 없음 또는 자동 수락 퀘스트", -- Needs review
	REPAMOUNT = "평판 %d", -- Needs review
	NEWDATAINTRO = "Quest Completist가 다음 정보를 알지 못했습니다. CurseForge에 알려 주시면 애드온의 정확도를 높이는 데 도움이 됩니다.", -- Needs review
	NEWDATAQUEST = " - 데이터베이스에 없는 퀘스트입니다.", -- Needs review
	NEWDATAFACTION = " - QC는 당신의 진영이 이 퀘스트를 완료할 수 있다는 것을 몰랐습니다.", -- Needs review
	NEWDATARACE = " - QC는 당신의 종족이 이 퀘스트를 완료할 수 있다는 것을 몰랐습니다.", -- Needs review
	NEWDATACLASS = " - QC는 당신의 직업이 이 퀘스트를 완료할 수 있다는 것을 몰랐습니다.", -- Needs review
	NEWDATAALERT = "새 데이터 발견 - 제보해 주세요!", -- Needs review
	BREADCRUMBAVAILABLE = "연결 퀘스트 1개를 받을 수 있습니다!", -- Needs review
	BREADCRUMBSAVAILABLE = "연결 퀘스트 %d개를 받을 수 있습니다!", -- Needs review
	BREADCRUMBQUESTS = "연결 퀘스트", -- Needs review
	MUTUALLYEXCLUSIVE = "이 퀘스트는 다른 퀘스트와 함께 완료할 수 없어, 그중 하나만 완료할 수 있습니다. 다른 퀘스트:", -- Needs review
	NOTINDATABASE = "데이터베이스에 없는 퀘스트", -- Needs review
	YOURSELF = "<자신>", -- Needs review
	OTHERQUESTS = "기타 퀘스트", -- Needs review
	PINDONE = "%d개 완료", -- Needs review
	PINSHOWDONE = "Shift로 보기", -- Needs review
	PINWAYPOINT = "클릭하여 TomTom 웨이포인트 설정", -- Needs review
	WELCOME = "Quest Completist를 사용해 주셔서 감사합니다. 퀘스트 정보에 오류가 있나요? CurseForge에 알려 주세요.", -- Needs review
	UNAVAILABLEACCEPTED = "퀘스트 %d \"%s\"은(는) 더 이상 받을 수 없는 퀘스트로 표시되어 있지만 방금 수락했습니다. 당신에게는 정상적으로 표시됩니다. 목록을 바로잡을 수 있도록 알려 주세요.", -- Needs review
	UNAVAILABLETURNEDIN = "퀘스트 %d \"%s\"은(는) 더 이상 받을 수 없는 퀘스트로 표시되어 있지만 방금 완료했습니다. 당신에게는 정상적으로 표시됩니다. 목록을 바로잡을 수 있도록 알려 주세요.", -- Needs review
	TOGGLEFRAME = "창 표시/숨기기", -- Needs review
	SHOWMINIMAPBUTTON = "미니맵 버튼 표시", -- Needs review
	MINIMAPLEFTCLICK = "왼쪽 클릭: 퀘스트 목록 표시/숨기기", -- Needs review
	MINIMAPRIGHTCLICK = "오른쪽 클릭: 설정 열기", -- Needs review
	MINIMAPDRAG = "드래그: 미니맵 주위로 버튼 이동", -- Needs review
	RECORDGIVERS = "만난 퀘스트 제공자 기록", -- Needs review
	RECORDGIVERSTIP = "만난 퀘스트 제공자와 만난 위치를 간단히 기록합니다. 이 컴퓨터에만 저장되며 어디로도 전송되지 않습니다. /qc report로 기록 내용을 볼 수 있습니다.", -- Needs review
	RECORDERNOTICE = "Quest Completist가 이제 만난 퀘스트 제공자와 만난 위치를 이 컴퓨터에만 간단히 기록합니다. /qc report로 확인하고, /qc record off로 중지할 수 있습니다.", -- Needs review
	RECORDERSTATUS = "퀘스트 제공자 기록: %s. /qc record on, /qc record off 또는 /qc record clear로 변경할 수 있습니다.", -- Needs review
	RECORDERCOUNTS = "지금까지 퀘스트 제공자 %d명, 퀘스트 %d개, 제공자 없이 시작된 퀘스트 %d개를 기록했습니다.", -- Needs review
	RECORDERFULL = "기록이 가득 차서 새 기록이 들어올 때마다 가장 오래된 기록이 교체됩니다 (현재까지 %d개).", -- Needs review
	RECORDERERRORS = "퀘스트 제공자 기록 중 오류가 %d번 발생했습니다. 마지막 오류: %s", -- Needs review
	RECORDERHIDDEN = "게임이 말하는 대상을 %d번 숨겼으며, 해당 퀘스트는 제공자 없이 기록되었습니다.", -- Needs review
	RECORDERFILE = "어디로도 전송되지 않습니다. 게임은 로그아웃하거나 UI를 다시 불러올 때 기록을 계정의 SavedVariables 폴더(게임의 WTF 폴더 안 Account 아래)에 있는 QuestCompletist.lua에 저장합니다. 지도 개선에 도움을 주시려면 해당 파일을 애드온의 CurseForge 페이지 댓글에 첨부해 주세요.", -- Needs review
	RECORDERCLEARED = "기록이 삭제되었습니다.", -- Needs review
	SHOWCONTINENTICONS = "대륙 지도에 지역 아이콘 표시", -- Needs review
	SHOWCONTINENTICONSTIP = "대륙 지도에서 아직 할 퀘스트가 남은 각 지역을 표시하고, 마우스를 올리면 개수를 보여 줍니다. 일일, 주간, 반복 퀘스트는 세지 않습니다. 지도 아이콘 표시도 켜져 있어야 합니다.", -- Needs review
	}, {__index = qcLocalize})

end