if GetLocale() == "itIT" then
qcLocalize = setmetatable({
	AHNQIRAJWAR = "Guerra di Ahn'Qiraj",
	ASSAULTONTHEDARKPORTAL = "Assalto al Portale Oscuro",
	CAMPING = "Camping",
	CENTRALKALIMDOR = "Kalimdor centrale", -- Needs review
	CLASSES = "Classi", -- Needs review
	CLASSQUESTS = "Missioni di classe", -- Needs review
	CLEARUPDATECACHE = "Svuota la cache degli aggiornamenti...", -- Needs review
	CONFIGSUBTITLE = "Queste opzioni permettono di cambiare il modo in cui Quest Completist gestisce e filtra i suoi dati.", -- Needs review
	CONFIGTITLE = "Quest Completist - Configurazione", -- Needs review
	CONTINENTS = "Continenti", -- Needs review
	DAYOFTHEDEAD = "Giorno dei Morti",
	DEATHRISING = "Morte Incombente",
	ELEMENTALBONDS = "Legami Elementali",
	FIRELANDSINVASION = "Invasione delle Terre del Fuoco",
	GARRISONCAMPAIGN = "Campagna della Guarnigione",
	GARRISONSUPPORT = "Supporto alla Guarnigione",
	HIDECOMPLETEDQUESTS = "Nascondi missioni completate", -- Needs review
	HIDEDAILYQUEST = "Nascondi missioni giornaliere", -- Needs review
	HIDEINPROGRESSQUESTS = "Nascondi missioni in corso", -- Needs review
	HIDELOWLEVELQUESTS = "Nascondi missioni di basso livello", -- Needs review
	HIDENONACTIVESEASONALQUESTS = "Nascondi missioni stagionali non attive", -- Needs review
	HIDEOTHERFACTIONQUESTS = "Nascondi missioni dell'altra fazione", -- Needs review
	HIDEOTHERPROFESSIONQUESTS = "Nascondi missioni di altre professioni", -- Needs review
	HIDEOTHERRACEANDCLASSQUESTS = "Nascondi missioni di altre razze e classi", -- Needs review
	HIDEOTHERCOVENANTQUESTS = "Nascondi missioni delle altre congreghe", -- Needs review
	HIDEWARBANDS = "Nascondi missioni completate da altri personaggi della brigata", -- Needs review
	HIDEUNAVAILABLE = "Nascondi missioni non più disponibili", -- Needs review
	HIDEREQUIREMENTSNOTMET = "Nascondi missioni con requisiti non soddisfatti", -- Needs review
	HIDENODATA = "Nascondi segnalini senza dati sulla missione", -- Needs review
	HIDEREPEATABLEQUEST = "Nascondi missioni ripetibili", -- Needs review
	HIDEWORLDQUEST = "Nascondi missioni mondiali e settimanali", -- Needs review
	INVASION = "Invasione",
	KHAZMODAN = "Khaz Modan", -- Requires localization
	LANDFALL = "Sbarco",
	LORDAERON = "Lordaeron", -- Requires localization
	LUNARFESTIVAL = "Celebrazione della Luna",
	MIDSUMMER = "Mezza Estate",
	NORTHERNKALIMDOR = "Kalimdor settentrionale", -- Needs review
	PANDARENBREWMASTERS = "Mastri Birrai Pandaren",
	PANDARENCAMPAIGN = "Campagna: Pandaren",
	PERFORMSERVERQUERY = "Interroga il server...", -- Needs review
	QUERYREQUESTED = "Un'interrogazione al server è stata richiesta", -- Needs review
	QUESTLIST = "Elenco missioni", -- Needs review
	QUESTSFOUND = "%d missioni trovate", -- Needs review
	SEASONAL = "Stagionale",
	SHOWMAPICONS = "Mostra icone sulla mappa", -- Needs review
	SKETTIS = "Skettis", -- Requires localization
	SORTALPHA = "Ordina: alfabeticamente", -- Needs review
	SORTLEVEL = "Ordina: per livello", -- Needs review
	SOUTHERNKALIMDOR = "Kalimdor meridionale", -- Needs review
	SPECIALS = "Speciali", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "Valle di Rovotorto", -- Needs review
	THEZANDALARI = "Zandalar",
	TOURNAMENT = "Torneo",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "Eventi settimanali", -- Needs review
	WORLDEVENTS = "World Events", -- Requires localization
	MACAREE = "Mac'Aree",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	ALLIANCEWARCAMPAIGN = "Campagna di Guerra dell'Alleanza",
	HORDEWARCAMPAIGN = "Campagna di Guerra dell'Orda",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	HERITAGE = "Retaggio",
	RATEDPVP = "PvP classificato",
	WORLDPVP = "PvP nel mondo di gioco",
	BLACKEMPIRECAMPAIGN = "Campagna dell'Impero Nero",
		-- Shadowlands Code
	-- Shadowlands Code
	MAINZONES = "Zone principali", -- Needs review
	OTHERCATEGORIES = "Altre categorie", -- Needs review
	COVENANTASSAULTS = "Assalti delle Congreghe",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
	--TWW
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NORTHRENDCUP = "Coppa Nordania",
	UPGRADESYSTEM = "Sistema di potenziamento",
	WARBANDS = "Brigate",
	TIMERUNNING = "Corse nel Tempo",
	THEHARBINGER = "L'Aralda",
	GILNEASRECLAMATION = "La Riconquista di Gilneas",
	TIMERIFT = "Time Rift",
	--MID
	NEIGHBORHOOD = "Neighborhood",
	PROGRESS = "%d/%d completate (%d%%)", -- Needs review
	SERVERQUERYRESULT = "Il server segnala %d missioni completate note a Quest Completist, di cui %d appena segnate come completate.", -- Needs review
	CACHECLEARED = "Cache svuotata.", -- Needs review
	CLEARINGCACHE = "Svuotamento della cache degli aggiornamenti...", -- Needs review
	NODETAILS = "Il gioco non fornisce i dettagli della missione", -- Needs review
	QUESTID = "ID missione:", -- Needs review
	STORYLINEPOSITION = "(%d di %d)", -- Needs review
	CAMPAIGNCHAPTER = "(Capitolo %d di %d)", -- Needs review
	EARLIERQUESTS = "... %d precedenti", -- Needs review
	LATERQUESTS = "... altre %d", -- Needs review
	THISQUEST = "questa missione", -- Needs review
	REQUIREDQUEST = "Missione richiesta:", -- Needs review
	REQUIREDFACTION = "Fazione richiesta:", -- Needs review
	REQUIREDRENOWN = "Livello di fama richiesto:", -- Needs review
	REQUIREDRANK = "Grado richiesto:", -- Needs review
	REQUIREDSKILL = "Abilità richiesta:", -- Needs review
	RANKLEVEL = "Grado %d", -- Needs review
	QUESTGIVER = "Assegnata da:", -- Needs review
	NOQUESTGIVER = "Sconosciuto, o missione accettata automaticamente", -- Needs review
	REPAMOUNT = "%d reputazione", -- Needs review
	NEWDATAINTRO = "Quest Completist non conosceva le seguenti informazioni. Aiuta a migliorare la precisione dell'addon segnalandole su CurseForge.", -- Needs review
	NEWDATAQUEST = " - La missione non esiste nel database.", -- Needs review
	NEWDATAFACTION = " - QC non sapeva che la tua FAZIONE potesse completare questa missione.", -- Needs review
	NEWDATARACE = " - QC non sapeva che la tua RAZZA potesse completare questa missione.", -- Needs review
	NEWDATACLASS = " - QC non sapeva che la tua CLASSE potesse completare questa missione.", -- Needs review
	NEWDATAALERT = "Trovati nuovi dati - contribuisci!", -- Needs review
	BREADCRUMBAVAILABLE = "1 missione introduttiva disponibile!", -- Needs review
	BREADCRUMBSAVAILABLE = "%d missioni introduttive disponibili!", -- Needs review
	BREADCRUMBQUESTS = "Missioni introduttive", -- Needs review
	MUTUALLYEXCLUSIVE = "Questa missione ne esclude altre: puoi completarne solo una. Le altre missioni sono:", -- Needs review
	NOTINDATABASE = "Missione non presente nel database", -- Needs review
	YOURSELF = "<Te stesso>", -- Needs review
	OTHERQUESTS = "Altre missioni", -- Needs review
	PINDONE = "%d completate", -- Needs review
	PINSHOWDONE = "Maiusc per mostrare", -- Needs review
	PINWAYPOINT = "Clicca per impostare un waypoint di TomTom", -- Needs review
	WELCOME = "Grazie per aver scelto Quest Completist. Hai notato un errore in una missione? Segnalalo su CurseForge.", -- Needs review
	UNAVAILABLEACCEPTED = "La missione %d \"%s\" risulta non più disponibile, ma l'hai appena accettata. Per te viene mostrata normalmente; segnalalo così che l'elenco possa essere corretto.", -- Needs review
	UNAVAILABLETURNEDIN = "La missione %d \"%s\" risulta non più disponibile, ma l'hai appena consegnata. Per te viene mostrata normalmente; segnalalo così che l'elenco possa essere corretto.", -- Needs review
	TOGGLEFRAME = "Mostra/nascondi finestra", -- Needs review
	SHOWMINIMAPBUTTON = "Mostra pulsante della minimappa", -- Needs review
	MINIMAPLEFTCLICK = "Clic sinistro: mostra o nascondi l'elenco missioni", -- Needs review
	MINIMAPRIGHTCLICK = "Clic destro: apri le opzioni", -- Needs review
	MINIMAPDRAG = "Trascina: sposta questo pulsante intorno alla minimappa", -- Needs review
	RECORDGIVERS = "Annota i datori di missioni che incontro", -- Needs review
	RECORDGIVERSTIP = "Tiene una breve nota dei datori di missioni che incontri e di dove li hai incontrati. Viene salvata solo su questo computer e non viene inviato nulla da nessuna parte. /qc report mostra cosa contiene.", -- Needs review
	RECORDERNOTICE = "Quest Completist ora tiene una breve nota dei datori di missioni che incontri e di dove li incontri, solo su questo computer. /qc report la mostra; /qc record off la ferma.", -- Needs review
	RECORDERSTATUS = "Annotazione dei datori di missioni: %s. /qc record on, /qc record off o /qc record clear la cambia.", -- Needs review
	RECORDERCOUNTS = "Finora annotati: %d datori di missioni, %d missioni e %d missioni iniziate senza un datore.", -- Needs review
	RECORDERFULL = "Le note sono piene, quindi le più vecchie vengono sostituite man mano che ne arrivano di nuove (%d finora).", -- Needs review
	RECORDERERRORS = "L'annotazione dei datori di missioni ha incontrato %d errori; l'ultimo: %s", -- Needs review
	RECORDERHIDDEN = "Per %d volte il gioco ha nascosto chi stava parlando; quelle missioni sono state annotate senza il datore.", -- Needs review
	RECORDERFILE = "Non viene inviato nulla da nessuna parte. Il gioco salva le note al logout o al ricaricamento, nel file QuestCompletist.lua nella cartella SavedVariables del tuo account (nella cartella WTF del gioco, sotto Account). Per aiutare a migliorare la mappa, allega quel file a un commento sulla pagina CurseForge dell'addon.", -- Needs review
	RECORDERCLEARED = "Le note sono state cancellate.", -- Needs review
	SHOWCONTINENTICONS = "Mostra icone di zona sulle mappe dei continenti", -- Needs review
	SHOWCONTINENTICONSTIP = "Segna ogni zona di una mappa continente in cui hai ancora missioni da fare e mostra i conteggi quando ci passi sopra con il mouse. Le missioni giornaliere, settimanali e ripetibili non vengono contate. Deve essere attiva anche l'opzione Mostra icone sulla mappa.", -- Needs review
	}, {__index = qcLocalize})

end