if GetLocale() == "ruRU" then
qcLocalize = setmetatable({
	ASSAULTONTHEDARKPORTAL = "Штурм Темного портала",
	CENTRALKALIMDOR = "Центральный Калимдор",
	CLASSES = "Классы",
	CLASSQUESTS = "Классовые задания",
	CLEARUPDATECACHE = "Очистить кэш обновлений",
	CONFIGSUBTITLE = "Эти настройки позволяют изменить способ, которым Quest Completist обрабатывает и фильтрует данные",
	CONFIGTITLE = "Quest Completist - Конфигурация",
	CONTINENTS = "Континенты",
	DAYOFTHEDEAD = "День мертвых",
	ELEMENTALBONDS = "Власть стихий",
	FIRELANDSINVASION = "Нападение на Огненные Просторы",
	GARRISONCAMPAIGN = "Гарнизонная кампания",
	GARRISONSUPPORT = "Поддержка гарнизона", -- Needs review
	HIDECOMPLETEDQUESTS = "Скрывать выполненные задания",
	HIDEDAILYQUEST = "Скрывать ежедневные задания", -- Needs review
	HIDEINPROGRESSQUESTS = "Скрывать выполняемые в данный момент задания",
	HIDELOWLEVELQUESTS = "Скрывать задания низкого уровня",
	HIDENONACTIVESEASONALQUESTS = "Скрывать неактивные сезонные задания",
	HIDEOTHERFACTIONQUESTS = "Скрывать задания других фракций",
	HIDEOTHERPROFESSIONQUESTS = "Скрывать задания других профессий",
	HIDEOTHERRACEANDCLASSQUESTS = "Скрывать задания других рас и классов",
	HIDEOTHERCOVENANTQUESTS = "Скрывать задания других ковенантов", -- Needs review
	HIDEWARBANDS = "Скрывать задания, выполненные другими персонажами отряда", -- Needs review
	HIDEUNAVAILABLE = "Скрывать задания, которые больше недоступны", -- Needs review
	HIDEREQUIREMENTSNOTMET = "Скрывать задания с невыполненными условиями", -- Needs review
	HIDENODATA = "Скрывать метки без данных о задании", -- Needs review
	HIDEREPEATABLEQUEST = "Скрывать повторяемые задания", -- Needs review
	HIDEWORLDQUEST = "Скрывать локальные и еженедельные задания", -- Needs review
	KHAZMODAN = "Каз Модан",
	LANDFALL = "Высадка",
	LORDAERON = "Лордерон",
	LUNARFESTIVAL = "Лунный фестиваль",
	MIDSUMMER = "Огненный солнцеворот",
	NORTHERNKALIMDOR = "Северный Калимдор",
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Пандаренская кампания",
	PERFORMSERVERQUERY = "Запросить с сервера...",
	QUERYREQUESTED = "Отправлен запрос к серверу...",
	QUESTLIST = "Список заданий", -- Needs review
	QUESTSFOUND = "Найдено %d заданий",
	SEASONAL = "Сезонные",
	SHOWMAPICONS = "Показывать значки на карте",
	SKETTIS = "Skettis", -- Requires localization
	SORTALPHA = "Упорядочить: по алфавиту",
	SORTLEVEL = "Упорядочить: по уровню",
	SOUTHERNKALIMDOR = "Южный Калимдор",
	SPECIALS = "События",
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "Тернистая долина",
	THEZANDALARI = "Зандаларские",
	TOURNAMENT = "Турнирные",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "Еженедельные события", -- Needs review
	WORLDEVENTS = "Игровые события",
	MACAREE = "Mac'Aree",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
	WORLDPVP = "World Pvp",
	BLACKEMPIRECAMPAIGN = "Black Empire Campaign",
	-- Shadowlands Code
	MAINZONES = "Основные зоны", -- Needs review
	OTHERCATEGORIES = "Другие категории", -- Needs review
	COVENANTASSAULTS = "Covenant Assaults",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
	-- Dragonflight Code
	--TWW
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NORTHRENDCUP = "Northrend Cup",
	UPGRADESYSTEM = "Upgrade System",
	WARBANDS = "Warbands",
	TIMERUNNING = "Timerunning",
	THEHARBINGER = "The Harbinger",
	GILNEASRECLAMATION = "Gilneas Reclamation",
	TIMERIFT = "Time Rift",
	--MID
	NEIGHBORHOOD = "Neighborhood",
	PROGRESS = "Выполнено %d/%d (%d%%)", -- Needs review
	SERVERQUERYRESULT = "Сервер сообщает о %d выполненных заданиях, известных Quest Completist; %d из них отмечены как выполненные впервые.", -- Needs review
	CACHECLEARED = "Кэш очищен.", -- Needs review
	CLEARINGCACHE = "Очистка кэша обновлений...", -- Needs review
	NODETAILS = "Игра не предоставила сведений о задании", -- Needs review
	QUESTID = "ID задания:", -- Needs review
	STORYLINEPOSITION = "(%d из %d)", -- Needs review
	EARLIERQUESTS = "... %d предыдущих", -- Needs review
	LATERQUESTS = "... ещё %d", -- Needs review
	THISQUEST = "это задание", -- Needs review
	REQUIREDQUEST = "Требуется задание:", -- Needs review
	REQUIREDFACTION = "Требуемая фракция:", -- Needs review
	REQUIREDRENOWN = "Требуемый уровень известности:", -- Needs review
	REQUIREDRANK = "Требуемый ранг:", -- Needs review
	REQUIREDSKILL = "Требуемый навык:", -- Needs review
	RANKLEVEL = "Ранг %d", -- Needs review
	QUESTGIVER = "Выдаёт задание:", -- Needs review
	NOQUESTGIVER = "Неизвестно, или задание принимается автоматически", -- Needs review
	REPAMOUNT = "%d репутации", -- Needs review
	NEWDATAINTRO = "Quest Completist не знал следующих сведений. Помогите сделать аддон точнее: сообщите о них на CurseForge.", -- Needs review
	NEWDATAQUEST = " - Этого задания нет в базе данных.", -- Needs review
	NEWDATAFACTION = " - QC не знал, что ваша ФРАКЦИЯ может выполнить это задание.", -- Needs review
	NEWDATARACE = " - QC не знал, что ваша РАСА может выполнить это задание.", -- Needs review
	NEWDATACLASS = " - QC не знал, что ваш КЛАСС может выполнить это задание.", -- Needs review
	NEWDATAALERT = "Найдены новые данные - сообщите нам!", -- Needs review
	BREADCRUMBAVAILABLE = "Доступно 1 вводное задание!", -- Needs review
	BREADCRUMBSAVAILABLE = "Доступно вводных заданий: %d!", -- Needs review
	BREADCRUMBQUESTS = "Вводные задания", -- Needs review
	MUTUALLYEXCLUSIVE = "Это задание исключает другие: можно выполнить только одно из них. Другие задания:", -- Needs review
	NOTINDATABASE = "Задания нет в базе данных", -- Needs review
	YOURSELF = "<Вы сами>", -- Needs review
	OTHERQUESTS = "Другие задания", -- Needs review
	PINDONE = "Выполнено: %d", -- Needs review
	PINSHOWDONE = "Shift — показать", -- Needs review
	PINWAYPOINT = "Щелкните, чтобы поставить точку TomTom", -- Needs review
	WELCOME = "Спасибо, что пользуетесь Quest Completist. Заметили ошибку в задании? Сообщите о ней на CurseForge.", -- Needs review
	UNAVAILABLEACCEPTED = "Задание %d «%s» отмечено как недоступное, но вы только что его взяли. Для вас оно показывается как обычно; сообщите об этом, чтобы список исправили.", -- Needs review
	UNAVAILABLETURNEDIN = "Задание %d «%s» отмечено как недоступное, но вы только что его сдали. Для вас оно показывается как обычно; сообщите об этом, чтобы список исправили.", -- Needs review
	TOGGLEFRAME = "Показать/скрыть окно", -- Needs review
	}, {__index = qcLocalize})

end