if GetLocale() == "esES" then
qcLocalize = setmetatable({
	AHNQIRAJTHEFALLENKINGDOM = "Ahn'Qiraj: el Reino Caído",
	ALCHEMY = "Alquimia",
	ARCHAEOLOGY = "Arqueología",
	ASSAULTONTHEDARKPORTAL = "Assault on the Dark Portal", -- Requires localization
	AZEROTH = "Azeroth",
	BARADINHOLD = "Bastión de Baradin",
	BATTLEGROUNDS = "Campos de Batalla",
	BATTLEPETS = "Duelo de mascotas",
	BLACKSMITHING = "Herrería",
	BLACKWINGDESCENT = "Descenso de Alanegra",
	BLACKWINGLAIR = "Guarida de Alanegra",
	BRAWLERSGUILD = "Brawler's Guild", -- Requires localization
	BREWFEST = "Fiesta de la Cerveza",
	CAVERNSOFTIME = "Cavernas del tiempo",
	CENTRALKALIMDOR = "Kalimdor central", -- Needs review
	CHILDRENSWEEK = "Semana de los niños",
	CLASSES = "Clases",
	CLASSQUESTS = "Misiones de clase",
	CLEARUPDATECACHE = "Borrar caché de actualización",
	COILFANGRESERVOIR = "Reserva Colmillo Torcido",
	COMBINEDMAPANDQUESTFILTERS = "Filtros combinados de misiones y mapas",
	CONFIGSUBTITLE = "Estas opciones permiten modificar cómo Quest Completist maneja y filtra los datos",
	CONFIGTITLE = "Quest Completist - Configuración",
	CONTINENTS = "Continentes",
	COOKING = "Cocina",
	DARKMOONFAIRE = "Feria de la Luna Negra",
	DAYOFTHEDEAD = "Festividad de los Muertos",
	DEATHKNIGHT = "Caballero de la Muerte",
	DRAENOR = "Draenor",
	DRAGONSOUL = "Alma de Dragón",
	DRUID = "Druida",
	DUNGEONSANDRAIDS = "Mazmorras y Bandas",
	EASTERNKINGDOMS = "Reinos del Este",
	ELEMENTALBONDS = "Vínculos elementales",
	ENCHANTING = "Encantamiento",
	ENGINEERING = "Ingeniería",
	FIRELANDS = "Tierras de Fuego",
	FIRELANDSINVASION = "Invasión de las Tierras de Fuego",
	FIRSTAID = "Primeros Auxilios",
	FISHING = "Pesca",
	GARRISONCAMPAIGN = "Garrison Campaign", -- Requires localization
	GARRISONSUPPORT = "Garrison Support", -- Requires localization
	GREENSTONEVILLAGE = "Aldea Verdemar",
	GRUULSLAIR = "Guarida de Gruul",
	HALLOWSEND = "Halloween",
	HARVESTFESTIVAL = "Festival de la Cosecha",
	HELLFIRECITADEL = "Ciudadela del Fuego Infernal",
	HERBALISM = "Herboristería",
	WORLDQUEST = "World Quests",
	HIDEDAILYQUEST = "Ocultar misiones diarias", -- Needs review
	HIDEINPROGRESSQUESTS = "Ocultar misiones en curso",
	HIDELOWLEVELQUESTS = "Ocultar misiones de nivel bajo",
	HIDENONACTIVESEASONALQUESTS = "Esconder misiones de eventos inactivos",
	HIDENORMALQUEST = "Hide Normal Quests",
	HIDEOTHERFACTIONQUESTS = "Esconder otras misiones de facción",
	HIDEOTHERPROFESSIONQUESTS = "Esconder otras misiones de profesión",
	HIDEOTHERRACEANDCLASSQUESTS = "Esconder otras misiones de clase/raza",
	HIDECOMPLETEDQUESTS = "Ocultar misiones completadas", -- Needs review
	HIDEOTHERCOVENANTQUESTS = "Ocultar misiones de otras curias", -- Needs review
	HIDEWARBANDS = "Ocultar misiones hechas por otros personajes de la banda guerrera", -- Needs review
	HIDEUNAVAILABLE = "Ocultar misiones que ya no están disponibles", -- Needs review
	HIDEREQUIREMENTSNOTMET = "Ocultar misiones con requisitos sin cumplir", -- Needs review
	HIDENODATA = "Ocultar marcadores sin datos de misión", -- Needs review
	HIDEREPEATABLEQUEST = "Ocultar misiones repetibles", -- Needs review
	HIDEWEEKLYQUEST = "Hide Weekly Quests",
	HIDEWORLDQUEST = "Ocultar misiones de mundo", -- Needs review
	HUNTER = "Cazador",
	INSCRIPTION = "Inscripción",
	ISLEOFGIANTS = "Isla de los Gigantes",
	JADETEMPLEGROUNDS = "Jade Temple Grounds", -- Requires localization
	JEWELCRAFTING = "Joyería",
	KALIMDOR = "Kalimdor",
	KHAZMODAN = "Khaz Modan", -- Requires localization
	LANDFALL = "Landfall", -- Requires localization
	LEATHERWORKING = "Peletería",
	LEGENDARY = "Legendario",
	LORDAERON = "Lordaeron", -- Requires localization
	LOVEISINTHEAIR = "Amor en el aire",
	LUNARFESTIVAL = "Festival Lunar",
	MAGE = "Mago",
	MAPFILTERS = "Filtros de mapa",
	MIDSUMMERFIREFESTIVAL = "Festival de Fuego del Solsticio de Verano",
	MINING = "Minería",
	MISCELLANEOUS = "Miscelánea",
	MOGUSHANVAULTS = "Cámaras Mogu'shan",
	MONK = "Monje",
	NAGRAND = "Nagrand",
	NEWYEARSEVE = "Nochevieja",
	NOBLEGARDEN = "Jardín Noble",
	NORTHERNKALIMDOR = "Kalimdor del norte", -- Needs review
	NORTHREND = "Rasganorte",
	ONYXIASLAIR = "Guarida de Onyxia",
	OPTIONS = "Opciones",
	OUTLAND = "Terrallende",
	PALACEOFTHEHEAVENS = "Palacio Mogu'shan",
	PALADIN = "Paladín",
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Pandaren Campaign", -- Requires localization
	PANDARIA = "Pandaria",
	PEAKOFSERENITY = "Peak of Serenity", -- Requires localization
	PERFORMSERVERQUERY = "Enviar consulta al servidor...",
	PILGRIMSBOUNTY = "Generosidad del Peregrino",
	PRIEST = "Sacerdote",
	PROFESSIONS = "Profesiones",
	QUERYREQUESTED = "Se ha enviado una consulta al servidor...",
	QUESTLISTFILTERS = "Filtros de lista de misiones",
	QUESTSFOUND = "%d misiones encontradas",
	RAIDS = "Bandas",
	REGIONS = "Regions", -- Requires localization
	RIDING = "Riding", -- Requires localization
	ROGUE = "Pícaro",
	RUINSOFGILNEASCITY = "Ruinas de la Ciudad de Gilneas",
	SCENARIO = "Scenario", -- Requires localization
	SEASONAL = "Vacacionales",
	SERPENTSHRINECAVERN = "Caverna Santuario Serpiente",
	SHADOWMOONVALLEY = "Valle Sombraluna",
	SHAMAN = "Chamán",
	SHOWMAPICONS = "Mostrar iconos del mapa",
	SKETTIS = "Skettis", -- Requires localization
	SKINNING = "Desuello",
	SORTALPHA = "Ordenar: alfabéticamente",
	SORTLEVEL = "Ordenar: por nivel",
	SOUTHERNKALIMDOR = "Kalimdor del sur", -- Needs review
	SPECIAL = "Especial",
	SPECIALS = "Especiales",
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STRANGLETHORNVALE = "Vega de Tuercespina",
	TAILORING = "Sastrería",
	TEMPLEOFTHEREDCRANE = "Templo de la Grulla Roja",
	THEARBORETUM = "The Arboretum", -- Requires localization
	THEBASTIONOFTWILIGHT = "El Bastión del Crepúsculo",
	THEBLACKMORASS = "La Ciénaga Negra",
	THEEVERBLOOM = "El Vergel Eterno",
	THEEYE = "El Ojo",
	THEGATEOFTHESETTINGSUN = "Puerta del Sol Poniente",
	THEHALFHILLMARKET = "El Mercado de Alcor",
	THEMAELSTROM = "La Vorágine",
	THEOBSIDIANSANCTUM = "El Sagrario Obsidiana",
	THETEMPLEOFTHEJADESERPENT = "Templo del Dragón de Jade",
	THEVIOLETHOLD = "El Bastión Violeta",
	THEZANDALARI = "Los Zandalari",
	THRONEOFTHEFOURWINDS = "Trono de los Cuatro Vientos",
	TOURNAMENT = "Torneo",
	UPPERBLACKROCKSPIRE = "Cumbre de Roca Negra Superior",
	UNCATEGORIZED = "Sin categoría", -- Needs review
	VASHJIR = "Vashj'ir",
	VAULTOFARCHAVON = "La Cámara de Archavon",
	WARLOCK = "Brujo",
	WARRIOR = "Guerrero",
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WEEKLYEVENTS = "Eventos semanales", -- Needs review
	WINTERVEIL = "Festival de Invierno",
	WORLDEVENTS = "Eventos del Mundo",
	THEBROKENISLES = "The Broken Isles",
	THEDREAMGROVE = "Arboleda de los Sueños",
	DEMONHUNTER = "Cazador de demonios",
	CONTESTCOMMING = "Contest comming shows wrong zone",
	HALLOFTHEGUARDIAN = "Salón del Guardián",
	MARDUMTHESHATTEREDABYSS = "Mardum, the Shattered Abyss",
	NETHERLIGHTTEMPLE = "Templo de la Luz Abisal",
	SKYHOLD = "Bastión Celestial",
	THEHEARTOFAZERTH = "The Heart of Azeroth",
	THEWANDERINGISLE = "The Wandering Isle Monk",
	TRUESHOTLODGE = "Trueshot Lodge Hunter",
	MAWOFSOULS = "Fauce de Almas",
	LEGIONUNCATEQUEST = "Legion Uncategorized Quests",
	RETURNTOKARAZHAN = "Regreso a Karazhan",
	MACAREE = "Mac'Aree",
	DREADSCARRIFT = "Falla Cicatriz del Terror",
	HELHEIM = "Helheim",
	EMERALDDREAMWAY = "Emerald Dreamway",
	BFA = "Battle For Azeroth",
	ZANDALAR = "Zandalar",
	KULTIRAS = "Kul Tiras",
	THUNDERTOTEM = "Thunder Totem",
	KINGSREST = "Reposo de los Reyes",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	THRUNDERROT = "The Underrot",
	THEDEATHOFCHROMIE = "The Deaths Of Chromie",
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	THEDRAGONSSPINE = "The Dragon`s Spine",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	TERRACEOFENLESSSPRINGS = "Veranda de la Primavera Eterna",
	PLAYERVSPLAYER = "Player Vs Player",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
	WORLDPVP = "World Pvp",
	NYALOTHATHEWALKINGCITY = "Ny'alotha, Ciudad del Despertar",
	VISIONSOFNZOTH = "Visions of N'Zoth",
	BLACKEMPIRECAMPAIGN = "Black Empire Campaign",
		-- Shadowlands Code
	-- Shadowlands Code
	SHADOWLANDS = "Shadowlands",
	SHADOWLANDSUNCATEQUEST = "Shadowlands Uncategorized Quests",
	COVENANTCALLINGS = "Covenant Callings",
	KYRIAN = "Kyrian",
	NECROLORD = "Necrolord",
	NIGHTFAE = "Night Fae",
	VENTHYR = "Venthyr",
	MAINZONES = "Zonas principales", -- Needs review
	OTHERCATEGORIES = "Otras categorías", -- Needs review
	NINEONECAMPAIGN = "9.1 Campaign",
	ABOMINABLESTICHING = "Costura abominable",
	COVENANTASSAULTS = "Covenant Assaults",
	COVENANTSANCTUARY = "Covenant Sanctuary",
	COVENANTSANCTUM = "Covenant Sanctum",
	EMBERCOURT = "Ember Court",
	KEEPERSRESPITE = "Respiro del Guardián",
	PATHOFASCENSION = "Path of Ascension",
	THEARCHIVISTSCODEX = "The Archivists' Codex",
	TORGHASTTOWEROFTHEDAMNED = "Torghast, Torre de los Condenados",
	ZERETHMORTISCAMPAIGN = "Zereth Mortis Campaign",
-- Dragonflight Code
	AZEROTHIANARCHIVES = "Azerothian Archives",
	AZMERLOTH = "Azmerloh",
	BRACKENHIDEWATERHOLE = "Brackenhide Waterhole",
	DRAGONISLE = "Dragon Isle",
	DRAGONFLIGHT = "Dragonflight",
	DRAGONSCALEBASECAMP = "Dragonscale Basecamp",
	DRAGONSCALEEXPEDITION = "Dragonscale Expedition",
	DUNGEONS = "Dungeons",
	EMERALDARDENS = "Emerald Gardens",
	HORNSWOGHOLLOW = "Hornswog Hollow",
	ISKAARATUSKARR = "Iskaara Tuskarr",
	LOSTRUINS = "Lost Ruins",
	MARUUKCENTAUR = "Maruuk Centaur",
	OBSIDIANCITADEL = "Ciudadela Obsidiana", 
	PASSAGEOFTIME = "Pasadizo del Tiempo",
	PRIMALISTSTORMS = "Primalist Storms",
	PRIMORDIALALE = "Primordial Vale",
	RUBYLIFEPOOLS = "Estanques de Vida Rubí",
	RUBYLIFESHRINE = "Ruby Lifeshrine",
	SHADOWLEDGE = "Shadow Legde",
	TEMPESTUNLEASHED = "Tempest Unleashed",
	THEPRIMAISTFUTURE = "The Primalist Future",
	THERONSWATCH = "Theron`s Watch",
	VALDRAKKENACCORD = "Valdrakken Accord",
	KORRAKSREVENGE = "Korrak`s Revenge",
	--TWW
	TWW = "The War Within",
	AWAKENINGTHEMACHINE = "Despertar la máquina",
	DEEPHAULRAVINE = "Barranco de Cargahonda",	
	DHARBANDAR = "Dhar Bandar",	
	EARTHEN = "Earthen",
	MOURNINGRISE = "Mourning Rise",
	NERUBARPALACE = "Palacio Nerub'ar",
	NORTHRENDCUP = "Northrend Cup",
	RAMBLESHIRE = "Villatrueno",
	UPGRADESYSTEM = "Upgrade System",
	WARBANDS = "Warbands",
	ARATHIHIGHLANDSTWW = "Arathi Highlands TWW",
	DELVESHEADQUARTERS = "Cuartel de los Exploradores de las Profundidades",
	DELVES = "Delves",
	THERAMORESFALLS = "Theramore`s  Fall",
	TIMERUNNING = "Timerunning",
	THEHARBINGER = "The Harbinger",
	GILNEASRECLAMATION = "Gilneas Reclamation",
	LITTLESCALESDAYCARE = "Little Scales Daycare",
	TIMERIFT = "Time Rift",
	AMIRDRASIL = "Amirdrasil",
	AMIRDRASSILTHEDREAMSHOPE = "Amirdrassil, la Esperanza del Sueño",
	THEOASIS = "Oasis",
	--MID
	MIDNIGHT = "Midnight",
	FOUNDERSPOINT = "Punto de la Fundadora",
	NEIGHBORHOOD = "Neighborhood",
	RAZORWINDSHORES = "Costas del Ventajo",
	SLAYERSRISE = "Alto del Asesino",
	WESTSANCTUM = "Sagrario del Oeste",	
	DEADMINES = "Minas de la Muerte",
	LOWERBLACKROCKSPIRE = "Cumbre de Roca Negra Inferior",
	THETEMPLEOFATALHAKKAR = "El Templo de Atal'Hakkar",
	THEBATTLEFORMOUNTHYJAL = "La Batalla del Monte Hyjal",
	SEATOFTHETRIUMVIRATE = "Trono del Triunvirato",
	TAZAVESHTHEVEILEDMARKET = "Tazavesh, el Mercado Velado",
	ASSAULTONVIOLETHOLD = "Asalto al Bastión Violeta",
	DIREMAULCAPITALGARDENS = "La Masacre: Jardines de la Capital",
	STRATHOLMEMAINGATE = "Stratholme: Entrada Principal",
	TEMPLEOFAHNQIRAJ = "Templo de Ahn'Qiraj",
	DIREMAULWARPWOODQUARTER = "La Masacre: Barrio Alabeo",
	DIREMAULGORDOKCOMMONS = "La Masacre: Ágora de Gordok",
	STRATHOLMESERVICEENTRANCE = "Stratholme: Entrada de Servicio",
	WINDRUNNERSPIRE = "Aguja Brisaveloz",
	MAGISTERSTERRACE = "Bancal del Magister",
	MURDERROW = "Frontal de la Muerte",
	THEVOIDSPIRE = "La Aguja del Vacío",
	THEBLINDINGVALE = "El Valle Cegador",
	DENOFNALORAKK = "Guarida de Nalorakk",
	VOIDSCARARENA = "Arena Lacravacua",
	THEDREAMRIFT = "La Falla Onírica",
	MAISARACAVERNS = "Cavernas de Maisara",
	NEXUSPOINTXENAS = "Punto de Nexo: Xenas",
	PROGRESS = "%d/%d completadas (%d%%)", -- Needs review
	SEARCHRESULTS = "Resultados de la búsqueda", -- Needs review
	SERVERQUERYRESULT = "El servidor indica %d misiones completadas que Quest Completist conoce, %d de ellas marcadas como completadas por primera vez.", -- Needs review
	CACHECLEARED = "Caché vaciada.", -- Needs review
	CLEARINGCACHE = "Vaciando tu caché de actualización...", -- Needs review
	NODETAILS = "El juego no ofrece los detalles de la misión", -- Needs review
	QUESTID = "ID de misión:", -- Needs review
	STORYLINE = "Cadena de misiones:", -- Needs review
	STORYLINEPOSITION = "(%d de %d)", -- Needs review
	EARLIERQUESTS = "... %d anteriores", -- Needs review
	LATERQUESTS = "... %d más", -- Needs review
	ONQUEST = "Tienes esta misión", -- Needs review
	COMPLETED = "Completada", -- Needs review
	NOTCOMPLETED = "No completada", -- Needs review
	UNKNOWNQUEST = "Misión desconocida", -- Needs review
	REQUIREDQUEST = "Misión necesaria:", -- Needs review
	UNKNOWNFACTION = "Facción desconocida", -- Needs review
	REQUIREDFACTION = "Facción necesaria:", -- Needs review
	REQUIREDRENOWN = "Nivel de renombre necesario:", -- Needs review
	RENOWNMET = "%d (requisito cumplido)", -- Needs review
	RENOWNNOTMET = "%d (requisito no cumplido)", -- Needs review
	DATAUNAVAILABLE = "Datos no disponibles", -- Needs review
	QUESTGIVER = "Ofrece la misión:", -- Needs review
	UNKNOWNNPC = "PNJ desconocido", -- Needs review
	NOQUESTGIVER = "Desconocido, o misión aceptada automáticamente", -- Needs review
	REPAMOUNT = "%d de reputación", -- Needs review
	NEWDATAINTRO = "Quest Completist no conocía la siguiente información. Ayuda a mejorar la precisión del addon publicándola en CurseForge.", -- Needs review
	NEWDATAQUEST = " - La misión no existe en la base de datos.", -- Needs review
	NEWDATAFACTION = " - QC no sabía que tu FACCIÓN podía completar esta misión.", -- Needs review
	NEWDATARACE = " - QC no sabía que tu RAZA podía completar esta misión.", -- Needs review
	NEWDATACLASS = " - QC no sabía que tu CLASE podía completar esta misión.", -- Needs review
	NEWDATAALERT = "¡Datos nuevos encontrados - contribuye!", -- Needs review
	BREADCRUMBAVAILABLE = "¡1 misión de introducción disponible!", -- Needs review
	BREADCRUMBSAVAILABLE = "¡%d misiones de introducción disponibles!", -- Needs review
	BREADCRUMBQUESTS = "Misiones de introducción", -- Needs review
	MUTUALLYEXCLUSIVE = "Esta misión excluye a otras: solo puedes completar una de ellas. Las otras misiones son:", -- Needs review
	NOTINDATABASE = "Misión fuera de la base de datos", -- Needs review
	YOURSELF = "<Tú mismo>", -- Needs review
	OTHERQUESTS = "Otras misiones", -- Needs review
	PINDONE = "%d completadas", -- Needs review
	PINSHOWDONE = "Mayús para mostrar", -- Needs review
	WELCOME = "Gracias por usar Quest Completist. ¿Has visto un error en una misión? Infórmalo en CurseForge.", -- Needs review
	UNAVAILABLEACCEPTED = "La misión %d \"%s\" figura como ya no disponible, pero acabas de aceptarla. Se te muestra con normalidad; infórmalo para que se corrija la lista.", -- Needs review
	UNAVAILABLETURNEDIN = "La misión %d \"%s\" figura como ya no disponible, pero acabas de entregarla. Se te muestra con normalidad; infórmalo para que se corrija la lista.", -- Needs review
	TOGGLEFRAME = "Mostrar/ocultar ventana", -- Needs review
	UNKNOWNZONE = "Zona desconocida", -- Needs review
	}, {__index = qcLocalize})

end