<#
Writes QuestCompletist\qcUnavailableQuests.lua, the quests players can no longer get, from the
reviewed decisions in docs\plans\unavailable-quest-decisions.csv (see docs\plans\unavailable-quests.md).

Each FLAG row becomes [QuestID]=Reason: 1 = obsolete (reviewed), 2 = not in the game client. Other
decisions (KEEP) stay in the CSV as a record and aren't written. The file is generated in quest ID
order, one entry per line; edit the CSV and rerun rather than editing the file.

Refuses to write anything if a FLAG row names a quest that isn't in data\quests.jsonl, a task quest
(world quests and bonus objectives are generally still live; tools\QuestV2CliTask.csv), a quest ID
twice, or a reason other than 1 or 2.
#>
param(
    [string]$ToolsDir = $PSScriptRoot,
    [string]$DataDir = (Join-Path $PSScriptRoot '..\data'),
    [string]$AddonDir = (Join-Path $PSScriptRoot '..\QuestCompletist'),
    [string]$Decisions = "$PSScriptRoot\..\docs\plans\unavailable-quest-decisions.csv"
)
. "$PSScriptRoot\AddonData.ps1"

$inDatabase = New-Object System.Collections.Generic.HashSet[string]
foreach ($quest in (Read-QuestData $DataDir)) { [void]$inDatabase.Add([string]$quest.id) }

$isTask = New-Object System.Collections.Generic.HashSet[string]
foreach ($row in Import-Csv "$ToolsDir\QuestV2CliTask.csv") { [void]$isTask.Add($row.ID) }

$flags = [ordered]@{}
$problems = New-Object System.Collections.Generic.List[string]
foreach ($row in Import-Csv $Decisions) {
    if ($row.Decision -ne "FLAG") { continue }
    $id = $row.QuestID
    if ($flags.Contains($id)) { $problems.Add("$id is listed twice"); continue }
    if ($row.Reason -notin @("1", "2")) { $problems.Add("$id has reason '$($row.Reason)', not 1 or 2"); continue }
    if (-not $inDatabase.Contains($id)) { $problems.Add("$id isn't in quests.jsonl"); continue }
    if ($isTask.Contains($id)) { $problems.Add("$id is a task quest"); continue }
    $flags[$id] = $row.Reason
}
if ($problems.Count) { throw "Nothing written:`n  " + ($problems -join "`n  ") }

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("-- Generated by tools\Build-UnavailableQuests.ps1 from docs\plans\unavailable-quest-decisions.csv;")
$lines.Add("-- edit that file and rerun instead of editing this one. Quests players can no longer get:")
$lines.Add("-- 1 = obsolete (reviewed), 2 = not in the game client. See docs\plans\unavailable-quests.md.")
$lines.Add("qcUnavailableQuests = {")
foreach ($id in ($flags.Keys | Sort-Object { [int]$_ })) { $lines.Add("[$id]=$($flags[$id]),") }
$lines.Add("}")

$text = ($lines -join "`r`n") + "`r`n"
[System.IO.File]::WriteAllText("$AddonDir\qcUnavailableQuests.lua", $text, (New-Object System.Text.UTF8Encoding $false))
"Wrote $($flags.Count) quests to $AddonDir\qcUnavailableQuests.lua"
